### ISSUE TITLE
Unable to install tigramite in windows

### ISSUE THREAD

**Issue by dharaik** [jakobrunge/tigramite#101]
Windows 10
pip 20.3.3
python 3.9.1

**installed packages:** 
numpy
scipy
scikit-learn
matplotlib
networkx 
cython 
mpi4py 

error while installing tigramite

pip install tigramite

C:\WINDOWS\system32>pip install tigramite
Collecting tigramite
  Using cached tigramite-4.2.1.4.tar.gz (231 kB)
Requirement already satisfied: numpy in c:\users\tejasvi chauhan\appdata\local\programs\python\python39\lib\site-packages (from tigramite) (1.19.4)
Requirement already satisfied: scipy in c:\users\tejasvi chauhan\appdata\local\programs\python\python39\lib\site-packages (from tigramite) (1.5.4)
Requirement already satisfied: six in c:\users\tejasvi chauhan\appdata\local\programs\python\python39\lib\site-packages (from tigramite) (1.15.0)
Using legacy 'setup.py install' for tigramite, since package 'wheel' is not installed.
Installing collected packages: tigramite
    Running setup.py install for tigramite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tejasvi chauhan\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tejasvi Chauhan\\AppData\\Local\\Temp\\pip-install-pilqogs6\\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tejasvi Chauhan\\AppData\\Local\\Temp\\pip-install-pilqogs6\\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-record-obvs3chs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tejasvi chauhan\appdata\local\programs\python\python39\Include\tigramite'
         cwd: C:\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\tigramite
    copying tigramite\data_processing.py -> build\lib.win-amd64-3.9\tigramite
    copying tigramite\models.py -> build\lib.win-amd64-3.9\tigramite
    copying tigramite\pcmci.py -> build\lib.win-amd64-3.9\tigramite
    copying tigramite\plotting.py -> build\lib.win-amd64-3.9\tigramite
    copying tigramite\__init__.py -> build\lib.win-amd64-3.9\tigramite
    creating build\lib.win-amd64-3.9\tigramite\independence_tests
    copying tigramite\independence_tests\cmiknn.py -> build\lib.win-amd64-3.9\tigramite\independence_tests
    copying tigramite\independence_tests\cmisymb.py -> build\lib.win-amd64-3.9\tigramite\independence_tests
    copying tigramite\independence_tests\gpdc.py -> build\lib.win-amd64-3.9\tigramite\independence_tests
    copying tigramite\independence_tests\independence_tests_base.py -> build\lib.win-amd64-3.9\tigramite\independence_tests
    copying tigramite\independence_tests\oracle_conditional_independence.py -> build\lib.win-amd64-3.9\tigramite\independence_tests
    copying tigramite\independence_tests\parcorr.py -> build\lib.win-amd64-3.9\tigramite\independence_tests
    copying tigramite\independence_tests\__init__.py -> build\lib.win-amd64-3.9\tigramite\independence_tests
    running build_ext
    building 'tigramite.tigramite_cython_code' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\Users
    creating build\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan
    creating build\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan\AppData
    creating build\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan\AppData\Local
    creating build\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan\AppData\Local\Temp
    creating build\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6
    creating build\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f
    creating build\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\tigramite
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tejasvi chauhan\appdata\local\programs\python\python39\include -Ic:\users\tejasvi chauhan\appdata\local\programs\python\python39\include -Ic:\users\tejasvi chauhan\appdata\local\programs\python\python39\lib\site-packages\numpy\core\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\tigramite\tigramite_cython_code.c /Fobuild\temp.win-amd64-3.9\Release\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\tigramite\tigramite_cython_code.obj
    tigramite_cython_code.c
    c:\users\tejasvi chauhan\appdata\local\programs\python\python39\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    C:\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\tigramite\tigramite_cython_code.c(5529): warning C4018: '<': signed/unsigned mismatch
    C:\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\tigramite\tigramite_cython_code.c(5541): warning C4018: '<': signed/unsigned mismatch
    C:\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-install-pilqogs6\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\tigramite\tigramite_cython_code.c : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tejasvi chauhan\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tejasvi Chauhan\\AppData\\Local\\Temp\\pip-install-pilqogs6\\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tejasvi Chauhan\\AppData\\Local\\Temp\\pip-install-pilqogs6\\tigramite_1bd7d08f9c144c28b0f1c929e47d912f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tejasvi Chauhan\AppData\Local\Temp\pip-record-obvs3chs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tejasvi chauhan\appdata\local\programs\python\python39\Include\tigramite' Check the logs for full command output.

**Comment by mbruhns** [comment]
It seems like your paths exceed the path limit of windows (260 characters). As a quick workaround I suggest changing this limit on your system. We will try to adapt the code to this restriction.

**Comment by dharaik** [comment]
@mbruhns  I just checked windows is already set to 'LongPathsEnabled' (value = 1) in the registry editor section 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem'. 

Should I try anything else?

**Comment by mbruhns** [comment]
Alright, have you tried installing tigramite in a conda environment?
If that does not work either you could also try installing it in an environment without cython.

**Comment by dharaik** [comment]
@mbruhns tried both. Still nothing. Tried wheels as well.

**Comment by mbruhns** [comment]
Have you tried a different C-compiler (gcc, clang)?

**Comment by monstrorivas** [comment]
I'm having the same issue on Windows as well. 
`pip install tigramite` fails to install but `pip install git+https://github.com/jakobrunge/tigramite.git` works

**Comment by amansingh2896** [comment]
@monstrorivas how to use pip install git+https://github.com/jakobrunge/tigramite.git to install tigramite, can you guide me? i am unable to install tigramite package in my windows

**Comment by sagarsimha** [comment]
@amansingh2896 @monstrorivas @tejasvichauhan The new update (developer branch) does not need Cython. Could you try it out on windows?
