### ISSUE TITLE
ValueError: nans after standardizing, possibly constant array!

### ISSUE THREAD

**Issue by vladbragoi** [jakobrunge/tigramite#102]
Hi Jakob,

I'm trying to run PCMCI+ with the following dataset (I'm reporting the first 50 rows which are enough to get the error):
```
	clock	rst	din	din_rdy	dout	dout_rdy
index						
0.0	1	1	103.0	1	0.0	0
5000.0	0	1	103.0	1	0.0	0
10000.0	1	1	103.0	1	0.0	0
15000.0	0	1	103.0	1	0.0	0
20000.0	1	1	103.0	1	0.0	0
25000.0	0	1	103.0	1	0.0	0
30000.0	1	1	103.0	1	0.0	0
35000.0	0	1	103.0	1	0.0	0
40000.0	1	1	103.0	1	0.0	0
45000.0	0	1	103.0	1	0.0	0
50000.0	1	1	103.0	1	0.0	0
55000.0	0	1	103.0	1	0.0	0
60000.0	1	1	103.0	1	0.0	0
65000.0	0	1	103.0	1	0.0	0
70000.0	1	1	103.0	1	0.0	0
75000.0	0	1	103.0	1	0.0	0
80000.0	1	1	103.0	1	0.0	0
85000.0	0	1	103.0	1	0.0	0
90000.0	1	1	103.0	1	0.0	0
95000.0	0	1	103.0	1	0.0	0
100000.0	1	1	103.0	1	0.0	0
105000.0	0	1	103.0	1	0.0	0
110000.0	1	1	103.0	1	0.0	0
115000.0	0	1	103.0	1	0.0	0
120000.0	1	1	103.0	1	0.0	0
125000.0	0	1	103.0	1	0.0	0
130000.0	1	1	103.0	1	0.0	0
135000.0	0	1	103.0	1	0.0	0
140000.0	1	1	103.0	1	0.0	0
145000.0	0	1	103.0	1	0.0	0
150000.0	1	1	103.0	1	0.0	0
155000.0	0	1	103.0	1	0.0	0
160000.0	1	1	103.0	1	0.0	0
165000.0	0	1	103.0	1	0.0	0
170000.0	1	1	103.0	1	0.0	0
175000.0	0	1	103.0	1	0.0	0
180000.0	1	1	103.0	1	0.0	0
185000.0	0	1	103.0	1	0.0	0
190000.0	1	1	103.0	1	0.0	0
195000.0	0	1	103.0	1	0.0	0
200000.0	1	1	103.0	1	0.0	0
205000.0	0	1	103.0	1	0.0	0
210000.0	1	1	103.0	1	0.0	0
215000.0	0	1	103.0	1	0.0	0
220000.0	1	1	103.0	1	0.0	0
225000.0	0	1	103.0	1	0.0	0
230000.0	1	1	103.0	1	0.0	0
235000.0	0	1	103.0	1	0.0	0
240000.0	1	1	103.0	1	0.0	0
245000.0	0	1	103.0	1	0.0	0
```
and with the following plot:
![wave](https://user-images.githubusercontent.com/24266220/103696396-8f262180-4f9e-11eb-9f5d-2c89121d4236.png)

Could you please help me to understand the problem?

Thank you

**Comment by vladbragoi** [comment]
Found the error. It was enough to remove some constant columns, but still have this issue: "ValueError: val_matrix needs to be symmetric for lag-zero", with the following val_matrix:
```
array([[[ 0.00000000e+00, -1.00000000e+00,  1.00000000e+00],
        [-2.33048694e-06,  0.00000000e+00,  0.00000000e+00],
        [-4.24717189e-04,  0.00000000e+00,  0.00000000e+00],
        [ 5.66698206e-05,  0.00000000e+00,  0.00000000e+00]],

       [[-2.33048694e-06, -1.09091315e-04,  0.00000000e+00],
        [ 0.00000000e+00,  7.00389198e-01, -6.98957964e-03],
        [ 4.63911018e-02,  2.64353642e-03,  2.76942402e-03],
        [-1.23997203e-03,  3.02182554e-06,  2.14638748e-05]],

       [[-4.24717189e-04, -7.70131762e-04,  0.00000000e+00],
        [ 4.63911018e-02, -8.89174838e-02,  2.23418551e-03],
        [ 0.00000000e+00,  2.26553953e-01, -2.52251035e-02],
        [ 9.35461339e-01,  1.52091146e-03, -2.67891304e-02]],

       [[ 5.66698206e-05, -6.61607076e-04,  0.00000000e+00],
        [-1.23997203e-03,  2.62637002e-04,  5.41756376e-04],
        [ 9.36605486e-01, -5.97841647e-03, -2.68010401e-02],
        [ 0.00000000e+00,  2.47323856e-01, -1.89595548e-01]]])
```
where the value in pos 2,3,0 (0.935461339) is different than the one in pos 3,2,0 (0.936605486).
I need some help to understand why this happens and how to solve it.

Thank you

**Comment by jakobrunge** [comment]
This shouldn't happen. Where does the error occur? Ideally you send me the data...

**Comment by vladbragoi** [comment]
I ran the pcmci+ with tau_max = 5 and pc_alpha=0.01 with the following dataset:
[ValueError.txt](https://github.com/jakobrunge/tigramite/files/5826492/ValueError.txt)

**Comment by jakobrunge** [comment]
Thanks for helping here, it was a bug in symmetrizing the p-values if they were exactly the same for [i,j] and [j,i]. It is now fixed.

**Comment by Wanff** [comment]
Hi, 

I also encountered the "nans after standardizing" error, despite the fact that there were no constant arrays in my data. 

Attached is the dataset:[gene_time_series.csv](https://github.com/jakobrunge/tigramite/files/6307285/gene_time_series.csv)

Here's the snippet I ran:

```
parcorr = ParCorr()
pcmci_parcorr = PCMCI(
    dataframe=dataframe, 
    cond_ind_test=parcorr,
    verbosity=1)

results = pcmci_parcorr.run_pcmci(tau_max=2, pc_alpha=0.2)
```

Thank you for your help, and let me know if you need anything else!

**Comment by sagarsimha** [comment]
@Wanff I ran pcmci with ParCorr on the dataset you provided. I did not encounter the error. Are you still facing the issue?

Note that we updated the package a week back. However, I have tested with the version which you may be using and did not see any errors.

**Comment by Wanff** [comment]
Hi, 

This might be a silly question, but in order for PCMCI to run, do there need to be more observations than variables? 

The reason it didn't work in the past when I ran it was because the input was in the shape (25 observations, 3206 variables) which was the truth. However, when I transposed it, PCMCI ran fine.

**Comment by jakobrunge** [comment]
The first dimension of the data must be time and the second the variables. Having more variables than time observations is not strictly ruled out, but if any of the independence tests has a condition dimension larger than the sample size, then an error is thrown.

**Comment by Wanff** [comment]
is the error thrown supposed to be nans after standardizing? i imagine a different error is supposed to be given?

**Comment by Mishu791** [comment]
I am having the same problem. I have run PCMCI and parCorr in a dataset where one column has only zero values. Is it just beacuse of the constant arrays of the data ? 

Well! after dropping the column i was able to run PCMCI and parCorr. 

So, is it a prerequisite that the arrays in a dataset should not be constant or same ???
