### ISSUE TITLE
Links changing in every run. 

### ISSUE THREAD

**Issue by dharaik** [jakobrunge/tigramite#103]
I tried running tigramite (CMIknn) on my dataset (dataset belong to climate/hydrology having variables like Precipitation, Temperature, etc.) but the links are changing on every new run. 

**CMIknn part:**

# CMI test nonlinear dependence
cmi_knn = CMIknn(significance='shuffle_test', knn=0.2, shuffle_neighbors=5, transform='ranks',n_jobs=-1)
pcmci = PCMCI(
    dataframe=dataframe, 
    cond_ind_test=cmi_knn,
    )
results = pcmci.run_pcmci(tau_max=10, pc_alpha=0.5)

attached are two results on the same dataset after running twice. 
**Run 1**
![Screenshot from 2021-01-27 13-43-21](https://user-images.githubusercontent.com/70380553/105965929-06d10300-60aa-11eb-981b-9152a357a238.png)

**Run 2**
![Screenshot from 2021-01-27 14-13-43](https://user-images.githubusercontent.com/70380553/105965940-09cbf380-60aa-11eb-9439-e061e359b089.png)

I tried different datasets and then I again found one dataset (few datasets results were stable) where this was happening, results change on every new run.
 What could be the reason?

**Comment by jakobrunge** [comment]
The CMIknn test uses a permutation shuffle test since no analytical null distribution is available. This introduces some small randomness. If you increase the number of sig_samples this would vanish. 
But this points us to introduce a "seed" feature in order to always yield deterministic results given a random seed.

**Comment by sagarsimha** [comment]
@tejasvichauhan We have now added a default random "seed" in all the conditional independence tests which will yield deterministic results. You can test the updated master branch for the same.
