### ISSUE TITLE
runtime with single core and parallel processing

### ISSUE THREAD

**Issue by dharaik** [jakobrunge/tigramite#104]
While setting **n_jobs = -1** in CMIknn, the runtime is more than **n_jobs = 1** case. 

Data size = 122,4
Runtimes (n_jobs = -1) 480 seconds
Runtime (n_jobs = 1) 390 seconds 

This happening for larger datasets also. 

I want to run this on a large dataset and that could run for many days. It would be better if I am able to parallelize (preferably on a cluster).

**Comment by dharaik** [comment]
The output shared above is from a dual core core i7 cpu.

**Comment by sagarsimha** [comment]
The CMIknn utilizes the scipy.spatial.cKDTree. The part where parallel processing comes in is at [query()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html) with n_jobs as a parameter. So, you need to check there.

Secondly, which time are you reporting, the total time (user+sys) or the wall time, and are you running from the Jupyter notebook? The wall time would be the one to compare. For a multiprocessing job, ideally, wall time < total time (cpu time). Doing trial runs via the pycharm shell on a 4 core i7, I see these times on average,

n_jobs = -1:
total time - 5 min 39s
wall time - 3 min 38s

n_jobs = 1:
total time = 4 min 22s
wall time = 4 min 22s

However, running them through jupyter notebook does report higher wall time for a multiprocessing job. This may be a behavior with Jupyter notebook.

Also, this article may be helpful as a related reference - https://pythonspeed.com/articles/parallelism-slower/
