### ISSUE TITLE
Feature selection

### ISSUE THREAD

**Issue by brunofacca** [jakobrunge/tigramite#105]
Hello. Thank you for this library.

Can it be used for feature selection (e.g., having a higher probability of selecting features with a causal relationship to the target as opposed to spurious correlations)? More specifically, I'd like to use to select continuous features with a causal relation binary labels (a classification problem) on a ultra-high dimensional dataset. If it can be used for that purpose, I'd be most grateful if you could kindly provide some guidelines on how to do it or an example.

Thank you.

**Comment by jakobrunge** [comment]
Sure it can, I guess you mean variable selection and this can be done, it's not different from causal discovery. Have a look at the tutorials.

**Comment by brunofacca** [comment]
Thank you.
