### ISSUE TITLE
Standardizing or making the data stationary?

### ISSUE THREAD

**Issue by FlorentijnD** [jakobrunge/tigramite#108]
Hi jakobrunge!

For PCMCI, the prerequisite is to have stationary data.
I did so for some features in my multivariate time series data set (by means of differencing), resulting in small absolute values for these time series.

Other variables were stationary to begin with, so these still have high absolute values (mean of the time series = 100 for example).

I was wondering whether this impacts the whole process, and whether quantification of the causal links is in any way affected by not making the stationary data standardized, explicitly?.

**Comment by jakobrunge** [comment]
Of course this impacts the whole process. If there is a causal reason for non-stationarity, then this is a fundamental problem that needs careful treatment to remove. You need to think about what causes the non-stationarity and then how to remove it. If it's a slowly varying driver of the mean or a seasonality, then you can can subtract it in some way. First differencing changes the variables you're looking at and therefore the causal question...

**Comment by FlorentijnD** [comment]
Thanks Jakob for your answer. I was meaning to ask whether _standardizing_ the stationary data makes sense in the case were some variables have small values due to the differencing operation in combination with others who have large absolute values because they were stationary to begin with?

**Comment by jakobrunge** [comment]
Standardizing makes almost no difference. The conditional independence 
tests are mostly invariant to linear transformations. It's part of the 
partial correlation test anyways. But depending on the case there can be 
small effects. Just try it...

Am 11. April 2021 19:24:28 schrieb FlorentijnD ***@***.***>:
