### ISSUE TITLE
plot_graph: take too much time to run

### ISSUE THREAD

**Issue by BeckyChanZC** [jakobrunge/tigramite#109]
I am trying to run the tigramite_tutorial_basics.ipynb, but when I run the step of tp.plot_graph, it takes to much time and after 1-2 days it is still running and plot no result. Has anyone had a similar problem? How to fix it?

**Comment by sagarsimha** [comment]
Hi. Could you provide details of your experimental setting such as number of variables, number of time samples, tau_max value if chosen and what kind of conditional independence test you are running?
