### ISSUE TITLE
The usage of CMIknn.get_dependence_measure

### ISSUE THREAD

**Issue by NawTun** [jakobrunge/tigramite#110]
Dear jakobrunge,I want to ask if the usage as following is right,
I want to get CMI(0 ,1| **3**),then I could use 
`CMIknn.get_dependence_measure(array=data, xyz=np.array([0, 1, 3]))`
if I want to get CMI(0 ,1|**3 ,4**),then I use
`CMI.get_dependence_measure(array=data, xyz=np.array([0, 1, 3, 4]))`
Am I right？

**Comment by jakobrunge** [comment]
No. Have a look at the doc strings. You would rather use
CMIknn.get_measure(X, Y, Z, tau_max)
where X, Y, Z are of the form [(variable, -time lag)] based on the order in the dataframe (that you need to set before).
