### ISSUE TITLE
GPDC run pcmci taking too long 

### ISSUE THREAD

**Issue by manmeet3591** [jakobrunge/tigramite#111]
I am having 8 variables with the length of each time series as 5840 data points. The ParrCorr run_pcmci finished in some minutes. With GPDC its taking infinitely long to run. I was running previously on my laptop, but it crashed. Now I am running on a utility node of Pratyush HPC (http://pratyush.tropmet.res.in/) but still its going on for past 2 days. Is there a way to increase the speed using parallelization. I have access to multi-core CPUs as well.

**Comment by manmeet3591** [comment]
I had a conversation with Jakob and he suggested to use https://github.com/jakobrunge/tigramite/blob/developer/tigramite/independence_tests/gpdc_torch.py for running on the GPU using pytorch.

**Comment by sagarsimha** [comment]
@manmeet3591 We have added further enhancements to gpdc_torch.py. Please check out the updated master branch. This handles >50k samples leveraging GPUs.
