### ISSUE TITLE
What is the best causal quantitative approach to use after determining the DAG with PCMCI? 

### ISSUE THREAD

**Issue by jcadecarli** [jakobrunge/tigramite#112]
Dear Dr. Runge and research colleges, what is the best or top causal quantitative approach to use after determining the DAG with PCMCI and/or PCMCI+?
I am working (for now) with synthetic time series with array lengths from 2000 to 3000. And 6 up to 10 variables, in most cases 6.
I am investigating the influence of control treatments on the production of petrochemicals. I would be glad to discuss further details of the experiments if someone is interested.

Thank you, Dr. Runge for your time and attention in the development of Tigramite and to all in this community.

**Comment by jakobrunge** [comment]
Checkout the LinearMediation class for linear and time-lagged causal effect estimates. I am currently working on non-parametric and also contemporaneous causal effect estimation. Stay tuned.

**Comment by sashastrelnikoff** [comment]
> Checkout the LinearMediation class for linear and time-lagged causal effect estimates. I am currently working on non-parametric and also contemporaneous causal effect estimation. Stay tuned.

Hi! I am just reaching out to see if there has been any update to tigramite regarding the contemporaneous causal effect estimation. If not, by any chance, is there a resource you could link to outlining a method of doing this? Thank you

**Comment by jakobrunge** [comment]
I have now implemented the new CausalEffect class, see the tutorial for an introduction!

**Comment by sashastrelnikoff** [comment]
Thanks for your response! Is there a method in CausalEffect to get the coefficients for a fitted linear model? I know that LinearMediation has .get_val_matrix() to get the coefficients, but I am looking to do the same thing just with contemporaneous links.

**Comment by jakobrunge** [comment]
Use the fit_wright_effect method with mediation='direct' and choose an intervention of 1 vs 0. Just like in the tutorial.
