### ISSUE TITLE
Issue with passing new data into prediction

### ISSUE THREAD

**Issue by mitchellthomas1** [jakobrunge/tigramite#113]
Hello Jakob,

Thank you for your great work on tigramite. One slight issue I seem to be having comes when I pass through new data to the predict() method in the Prediction class, and the outputted array seems to be the wrong shape. I believe this is because the call to new_data.construct_array() on line 1172 of models.py is missing the argument mask = self.test_mask. When I add that argument into the method call everything works as expected.

Thank you again for your great work!

**Comment by jakobrunge** [comment]
Right, currently the mask is not passed on. It was intended that the user does that after prediction. But I've added in the developer at line 1367: 

  if new_data.mask is None:
      # if no mask is supplied, use the same mask as for the fitted array
      new_data_mask = self.test_mask
  else:
      new_data_mask = new_data.mask

Note that the developer and master where both updated few days ago.
