### ISSUE TITLE
possible new error

### ISSUE THREAD

**Issue by microprediction** [jakobrunge/tigramite#114]
I noticed a scheduled job failed just now ....  

File "causality.py", line 60, in <module>
    tp.plot_time_series_graph(
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/tigramite/plotting.py", line 2190, in plot_time_series_graph
    _draw_network_with_curved_edges(
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/tigramite/plotting.py", line 1336, in _draw_network_with_curved_edges
    cb_e.outline.remove()
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/site-packages/matplotlib/artist.py", line 181, in remove
Error:     raise NotImplementedError('cannot remove artist')

**Comment by amitnextdoor** [comment]
I get a similar error. I cant find a good version of the package that doesnt show this error either. Maybe there was a breaking change in `matplotlib`?

```NotImplementedError                       Traceback (most recent call last)
<ipython-input-10-51ffee33ead1> in <module>
      4     var_names=var_names,
      5     link_colorbar_label='cross-MCI',
----> 6     node_colorbar_label='auto-MCI',
      7     ); plt.show()

~/anaconda3/envs/causalml/lib/python3.7/site-packages/tigramite/plotting.py in plot_graph(link_matrix, val_matrix, sig_thres, var_names, fig_ax, figsize, save_name, link_colorbar_label, node_colorbar_label, link_width, link_attribute, node_pos, arrow_linewidth, vmin_edges, vmax_edges, edge_ticks, cmap_edges, vmin_nodes, vmax_nodes, node_ticks, cmap_nodes, node_size, node_aspect, arrowhead_size, curved_radius, label_fontsize, alpha, node_label_size, link_label_fontsize, lag_array, network_lower_bound, show_colorbar, inner_edge_style)
   1871         link_colorbar_label=link_colorbar_label,
   1872         network_lower_bound=network_lower_bound,
-> 1873         show_colorbar=show_colorbar,
   1874         # label_fraction=label_fraction,
   1875     )

~/anaconda3/envs/causalml/lib/python3.7/site-packages/tigramite/plotting.py in _draw_network_with_curved_edges(fig, ax, G, pos, node_rings, node_labels, node_label_size, node_alpha, standard_size, node_aspect, standard_cmap, standard_color, log_sizes, cmap_links, cmap_links_edges, links_vmin, links_vmax, links_edges_vmin, links_edges_vmax, links_ticks, links_edges_ticks, link_label_fontsize, arrowstyle, arrowhead_size, curved_radius, label_fontsize, label_fraction, link_colorbar_label, inner_edge_curved, inner_edge_style, network_lower_bound, show_colorbar)
   1376             #     print('no ticks given')
   1377 
-> 1378             cb_e.outline.remove()
   1379             cax_e.set_xlabel(
   1380                 link_colorbar_label, labelpad=1, fontsize=label_fontsize, zorder=-10

~/anaconda3/envs/causalml/lib/python3.7/site-packages/matplotlib/artist.py in remove(self)
    179 
    180         else:
--> 181             raise NotImplementedError('cannot remove artist')
    182         # TODO: the fix for the collections relim problem is to move the
    183         # limits calculation into the artist itself, including the property of

NotImplementedError: cannot remove artist```

**Comment by amitnextdoor** [comment]
cc @jakobrunge

**Comment by jakobrunge** [comment]
I don't get any errors with matplotlib 3.1.3 in python 3.6, what is your setup?

**Comment by amitnextdoor** [comment]
I was on `matplotlib 3.4.1` and got this error. When I reverted to `3.1.3` it worked, so there must be a breaking change somewhere with higher versions. I could make a simple PR to pin the version to `3.1.3`, but it up to you obviously!

**Comment by sagarsimha** [comment]
@amitnextdoor @microprediction Only for matplotlib 3.4.0 and above, the outline object type has changed from artist to spine. Make the following changes,
In plotting.py -> 
Line 1378 - cb_e.outline.clear()
Line 1469 - cb_n.outline.clear()

**Comment by bsolino** [comment]
I'm experiencing the same issue, with matplotlib version 3.4.2.

I have tried @sagarsimha changes and they worked for me : )

**Comment by sagarsimha** [comment]
@amitnextdoor @microprediction @bsolino We will be pushing an update soon with the above changes and freezing on matplotlib>=3.4.0.

**Comment by sagarsimha** [comment]
@microprediction @amitnextdoor @bsolino  The issue has been fixed. Please check out the latest master branch.
