### ISSUE TITLE
Question: binary time series

### ISSUE THREAD

**Issue by dialuser** [jakobrunge/tigramite#116]
Hi Jakob, can tigramite be used on binary time series? Thanks. --Alex

**Comment by jakobrunge** [comment]
Sure you can try it, but I don't have much theoretical guarantees then. Just check it out with the ParCorr conditional independence test and if that doesn't work well, then use the CMIsymb test on integer-valued data.

**Comment by dialuser** [comment]
Hi Jakob, thanks for your answer. 

I saw an example in your tutorial notebook, https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_basics.ipynb, but the symbolic part got commented out. Is there any concern on it's not working well?

Basically, I'm interested in causal relations between extreme events in two time series. I wonder what would be the best way to approach this using tools in tigramite, other than converting continuous time series to symbolic time series.  Thanks.

**Comment by jakobrunge** [comment]
It is commented out only because it takes so long, but go ahead and try it!

**Comment by dialuser** [comment]
Thanks.
