### ISSUE TITLE
Using any independence test requires installing "optional" packages

### ISSUE THREAD

**Issue by bsolino** [jakobrunge/tigramite#119]
The way Independence Test `__init__.py` file is set, it's importing all the different independence tests whenever the module is accessed, even if it is to import another independence test. Because of this, the "optional" dependencies are actually required.

I've found a good way to solve this here: https://stackoverflow.com/a/563075. The idea is to use the `imp` module to check if the dependencies exist, and if so load the module. However, this works only in the case of python dependencies. Unfortunately, pytorch has OS dependencies that I can't easily solve that are making the import fail.

Another way to deal with this is to put the imports inside a try-catch statement, and ignore it if an exception arises. This has the consequence that if the module fails loading for any other reasons it would fail silently. In my case that is a desirable outcome, at least for GPDC Torch, but I'm not sure it's the solution you would prefer for your code. It's possible to filter this, but it feels a bit "hacky" because the only way to distinguish the exceptions is by looking at the exception text itself. E.g. https://stackoverflow.com/a/8881967

Finally, the easiest (but perhaps uglier and this brokes backwards compatibility) would be to remove the `__init__.py` file and import directly from the files. That is, instead of doing

```
from tigramite.independence_tests import ParCorr
```

do

```
from tigramite.independence_tests.parcorr import ParCorr
```

I could write a PR to solve this issue, as it's affecting me directly, but I would prefer to know which of the possible solutions is more desirable for you.

**Comment by jakobrunge** [comment]
Good point, we'll work on this, probably with "try-except" statements to not break the code.

**Comment by jakobrunge** [comment]
Done.
