### ISSUE TITLE
Matplotlib 3.4 deprecation warning: "figbox" is going to be removed

### ISSUE THREAD

**Issue by bsolino** [jakobrunge/tigramite#120]
I'm encountering a deprecation warning with Matplotlib 3.4.2. The attribute "figbox" is going to be removed.

The specific text of the warning is:

>MatplotlibDeprecationWarning: 
>The figbox attribute was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use get_subplotspec().get_position(self.figure) instead.

I'm encountering this is in the following lines:

```
tigramite/plotting.py:1357:
  ax.figbox.bounds[1] + 0.02,
/tigramite/plotting.py:1451: 
  ax.figbox.bounds[1] + 0.02 + ring * 0.11,
```

**Comment by sagarsimha** [comment]
The forthcoming update also addresses this.
