### ISSUE TITLE
PCMCI.get_lagged_dependencies returns a dict, not an array

### ISSUE THREAD

**Issue by jjakenichol** [jakobrunge/tigramite#123]
Found this after following this tutorial and chasing down the root cause: https://notebook.community/jakobrunge/tigramite/tutorials/tigramite_tutorial_basics

After running
```
correlations = pcmci.get_lagged_dependencies(tau_max=20)
lag_func_matrix = tp.plot_lagfuncs(val_matrix=correlations, setup_args={'var_names':var_names, 
                                    'x_base':5, 'y_base':.5})
```
I get this error:
```
    lag_func_matrix = tp.plot_lagfuncs(
    line 414, in plot_lagfuncs
    N, N, tau_max_plusone = val_matrix.shape
AttributeError: 'dict' object has no attribute 'shape'
```
The issue seems to be that `get_lagged_dependencies` is returning a dict, not an array like it says it should here https://jakobrunge.github.io/tigramite/index.html#tigramite.pcmci.PCMCI.get_lagged_dependencies

Looks like in `_run_mci_or_variants`, it returns a dictionary containing the matrix that get_lagged_dependencies thinks it's returning. I'm able to fix it on my side by accessing the matrix within the dict.

I imagine the tutorials are just out of date. It seems that the solution is probably just to update the documentation.

**Comment by jakobrunge** [comment]
Hi, the tutorial works fine since it extracts ['val_matrix']. Maybe you are using an old tutorial version?
The docs of "get_lagged_dependencies" state "Returns the matrices of test statistic values, p-values, and confidence intervals.", so that implies a dictionary and not an array being returned...
