### ISSUE TITLE
Real data examples

### ISSUE THREAD

**Issue by jimkeegan2** [jakobrunge/tigramite#124]
Hi Jakob,

I was wondering if you have any examples/tutorials using real time series data instead of the np.random.RandomState function? I am getting confused on how to implement my own data into the code. I have a .csv of time series values for 5 different climate variables (ex: precipitation, temperature, etc.). 

I am just a little lost on how to implement this tool on my own data.

Thanks, Jim

**Comment by sagarsimha** [comment]
Hi. Tigramite takes in data in the standard numpy ndarray format. Initially, you can use a data analysis library such as [Pandas](https://pandas.pydata.org/) to import the csv data in and do any of the necessary preprocessing and finally convert to numpy array to feed it in to Tigramite. 

Example:

data = pd.read_csv('data_time_series.csv', names=var_names)
data_numpy = data.to_numpy()

#First dimension - time, second - variables
data_numpy = data_numpy.transpose()

T, N = data_numpy.shape
var_names = range(N)
dataframe = pp.DataFrame(data_numpy, 
                         datatime = np.arange(T), 
                         var_names=var_names)

You can also use numpy directly to import the csv in. It is just a matter of convinience.

**Comment by jimkeegan2** [comment]
Thank you for getting back to me! That worked great!

I do have another question regarding the pcmci link coefficients and how those are selected for each variable? Do you have any guidance on that?

Much appreciated, Jim

**Comment by sagarsimha** [comment]
Please go through the papers listed on the Readme.
