### ISSUE TITLE
Is there an example of using the parallel script?

### ISSUE THREAD

**Issue by jjakenichol** [jakobrunge/tigramite#126]
Apologies if there is a better place to ask this kind of question.

For example, how might I substitute
```
cmi_knn = CMIknn(significance='shuffle_test', knn=0.1, shuffle_neighbors=5, transform='ranks')
pcmci_cmi_knn = PCMCI(
    dataframe=dataframe, 
    cond_ind_test=cmi_knn,
    verbosity=2)
results = pcmci_cmi_knn.run_pcmci(tau_max=2, pc_alpha=0.05)
```
or
```
parcorr = ParCorr(significance='analytic')
pcmci = PCMCI(
    dataframe=dataframe, 
    cond_ind_test=parcorr,
    verbosity=1)
results = pcmci.run_pcmci(tau_max=8, pc_alpha=None)
```
with the parallelized code? Is there an example I can work from?

Thank you!

**Comment by jakobrunge** [comment]
Yes, there is an example script in the github repo called ``run_pcmci_parallel.py``. It may need a little polishing, though.

**Comment by jjakenichol** [comment]
Thank you, on skimming I assumed only functions existed in that script.
