### ISSUE TITLE
Could not import packages for CMIknn and GPDC estimation

### ISSUE THREAD

**Issue by aaaaaaui** [jakobrunge/tigramite#127]
Hello Jakob,

Thank you for your great work on tigramite. When I run the pcmci,appear a bug,
Could not import packages for CMIknn and GPDC estimation
Could not import r-package RCIT,
![image](https://user-images.githubusercontent.com/77562566/124212712-05f14100-db22-11eb-8388-414bc90bb9a2.png)

What's going on？
Thank you again for your great work!

**Comment by jakobrunge** [comment]
Can you check whether this occurs with the current master?

**Comment by aaaaaaui** [comment]
Thank you,Jakob. This problem has been solved.
