### ISSUE TITLE
a question when running the prediction

### ISSUE THREAD

**Issue by aaaaaaui** [jakobrunge/tigramite#129]
Hello Jakob,

Thank you for your great work on tigramite. A bug when l running the prediction.
![image](https://user-images.githubusercontent.com/77562566/126068990-e7ea77f8-abe7-452d-b5aa-86c451473fbb.png)
![image](https://user-images.githubusercontent.com/77562566/126069001-701f2709-8e23-48d4-b4f5-2a61bb8b9f12.png)

 
Thank you again for your great work!

**Comment by jakobrunge** [comment]
I don't get this error in the tutorial, can you check whether you get it with the current master?

**Comment by anilky81** [comment]
getting the same error - not sure if I should make a new issue.

ValueError: shape mismatch: dataframe.values.shape = (200, 3) but mask.shape = (150, 3), must be identical

I got the latest master of the tutorial but still see the same issue. Probably has something to do with other package versions but am not able to locate the cause.

**Comment by sagarsimha** [comment]
Can you try with the latest developer branch and write back to us?

**Comment by anilky81** [comment]
tried with the latest developer branch but still see the same error.

**Comment by jakobrunge** [comment]
Can you give us a minimal working example?

**Comment by anilky81** [comment]
I was just trying to run the notebook in jupyterlab cell by cell and I encounter the error in cell [8]. Please suggest the information you would need in the minimal example and I can try to create one.

**Comment by jakobrunge** [comment]
Strange, I don't get this error in the developer branch. Did you use the original prediction tutorial?

**Comment by anilky81** [comment]
Tried both the master and the developer branches. I am not very familiar with python but my guess is that it is some library/package version that's causing the issue. I am just not able to pinpoint it. Thank you very much for the help.

**Comment by jakobrunge** [comment]
You have to checkout the developer branch and then install it with
python setup.py develop

**Comment by anilky81** [comment]
This worked perfectly. Thanks a lot.
