### ISSUE TITLE
Question: Running time of parallel processing

### ISSUE THREAD

**Issue by wmd20** [jakobrunge/tigramite#130]
Hi Jakob,

I notice that the parameter 'n_job'  means the tumber of jobs to schedule for parallel processing. If -1 is given all processors are used. But I found that parallel processing takes longer to run the program than single thread (n_job be set to 1). I feel so confused

Thank you very much for your kind consideration and I am looking forward to your early reply.
Single thread: 5.605 seconds
![image](https://user-images.githubusercontent.com/64463468/126586595-21b41edb-f6fc-461d-80c3-97ded6c273bf.png)
Parallel processing: 134.882 seconds
![image](https://user-images.githubusercontent.com/64463468/126586613-5ce59676-66bc-4b3d-9075-9be16519afa0.png)

**Comment by sagarsimha** [comment]
Hi. Please refer to this issue and discussion here https://github.com/jakobrunge/tigramite/issues/104

**Comment by wmd20** [comment]
Jakob, thank you for answering my question! 
You mentioned that the main computational cost of CMIknn comes from searching nearest neighbors in the high dimensional subspaces. I am thinking that whether it is possible to store the nearest neighbor first instead of searching for them?

**Comment by wmd20** [comment]
> Hi. Please refer to this issue and discussion here #104
Jakob, thank you for answering my question!
You mentioned that the main computational cost of CMIknn comes from searching nearest neighbors in the high dimensional subspaces. I am thinking that whether it is possible to store the nearest neighbor first instead of searching for them?

**Comment by sagarsimha** [comment]
I am not sure I understand what you mean. Do you mean to say that we compute nearest neighbor for each subspace individually?

**Comment by wmd20** [comment]
> I am not sure I understand what you mean. Do you mean to say that we compute nearest neighbor for each subspace individually?

Yes, but I am not sure whether it is possible to implement

**Comment by sagarsimha** [comment]
There is computational cost to constructing KDTree and searching them even in the subspaces. We'd have to compare the computational cost in both methods. There is ongoing work on speeding up searching in the subspace. Will elaborate on the details and update here once done.

**Comment by wmd20** [comment]
> There is computational cost to constructing KDTree and searching them even in the subspaces. We'd have to compare the computational cost in both methods. There is ongoing work on speeding up searching in the subspace. Will elaborate on the details and update here once done.
Jakob, thanks a lot. I have one more little question, I noticed the hyperparameter 'n_jobs' can implement parallel processing in the spatial.cKDTree function.  And there is an example script in the github repo called run_pcmci_parallel.py, Can I use them both when I run experiments? Thanks

**Comment by sagarsimha** [comment]
Ideally, yes, you can. But, true parallelization depends on how OS handles the requests based on the resources available.

**Comment by wmd20** [comment]
> Ideally, yes, you can. But, true parallelization depends on how OS handles the requests based on the resources available.

Ok, I see. Thank you very much for your help~
