### ISSUE TITLE
Question: run pcmci parallel

### ISSUE THREAD

**Issue by wmd20** [jakobrunge/tigramite#131]
Hi Jakob,

Sorry to bother you~

I noticed  you used the selected_variables parameter in the script in the github repo called run_pcmci_parallel.py, but there is an error when I try to run this pragram. It showed selected_variables is deprecated. Then how can I implement parallel processing if I do not use the parameter 'selected_variables'.

**Comment by jakobrunge** [comment]
Right, the script wasn't updated yet to move from "selected_variables" to "selected_links". We'll work on that...

**Comment by jakobrunge** [comment]
It's in the developer branch now. Would be great if you can test it!

**Comment by jjakenichol** [comment]
Hi Jakob,

I'm testing the developer branch now. I haven't altered the script. I'm getting an error on line 277:
`all_results[key][:, j, :] = results_in_j[key][:, j, :]`

The error is:

> all_results[key][:, j, :] = results_in_j[key][:, j, :]
> ValueError: could not convert string to float: ''

It fails when key is 'group' and j is 0.

I tried this print to look into it:
```
print(all_results[key][:, j, :])
print(results_in_j[key][:, j, :])
```

and those values are:
> [[0. 0. 0. 0.]
>  [0. 0. 0. 0.]
>  [0. 0. 0. 0.]]
> [['' '-->' '' '']
>  ['' '' '' '']
>  ['' '' '' '']]

So it seems like it's trying to assign a float array to a string array. I'm not versed well enough in the code yet to know what it's supposed to be doing.

Let me know if I can attempt any ideas or provide any more information.

**Comment by jjakenichol** [comment]
I found a work around. I changed the code block starting on line 273:
```
                    if key not in all_results.keys():
                        if key == 'p_matrix':
                            all_results[key] = numpy.ones(results_in_j[key].shape)
                        else:
                            all_results[key] = numpy.zeros(results_in_j[key].shape)
                        all_results[key][:, j, :] = results_in_j[key][:, j, :]
```

to this:
```
                    if key not in all_results.keys():
                        if key == 'p_matrix':
                            all_results[key] = numpy.ones(results_in_j[key].shape)
                        else:
                            # all_results[key] = numpy.zeros(results_in_j[key].shape)
                            all_results[key] = numpy.empty(results_in_j[key].shape, dtype="O")
                        all_results[key][:, j, :] = results_in_j[key][:, j, :]
```
That lets the whole program run on my cluster. `numpy.empty(results_in_j[key].shape, dtype="O")` initializes an empty array of type Object. That lets it accept assignment from any other array type.

I believe that replacing the whole code block with 
```
if key not in all_results.keys():
  all_results[key] = numpy.empty(results_in_j[key].shape, dtype="O")
  all_results[key][:, j, :] = results_in_j[key][:, j, :]
```
works too. It runs without errors either way, but I'm not sure if there are performance differences between being explicit about the dtype or letting it just be a python Object, which is what `dtype="O"` does.
