### ISSUE TITLE
Question: is it possible to run PCMCI on seasonal data?

### ISSUE THREAD

**Issue by jimkeegan2** [jakobrunge/tigramite#135]
Hi there! 
I am wondering if it is possible to run this on seasonal data? I am hoping to see the causal pathways between variables on a seasonal scale rather than annually. I could create a time series of just summer data and run it through but I am wondering if that would actually work and give good results. It would be interesting to look into how they may change between seasons or annually.
Please let me know if it would make sense to do this.
Thank you so much:
Jim

**Comment by sagarsimha** [comment]
Do look into the 'masking' functionality described in this tutorial.

https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_missing_masking.ipynb
