### ISSUE TITLE
could not install tigramite in windows

### ISSUE THREAD

**Issue by amansingh2896** [jakobrunge/tigramite#142]
LINK : fatal error LNK1104: cannot open file 'build\temp.win-amd64-3.8\Release\Users\IC3\AppData\Local\Temp\pip-install-v7nlp1rq\tigramite_ebe1ab9fa0f04c4ea4e283de07b9517b\tigramite\tigramite_cython_code.cp38-win_amd64.exp'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1104
ERROR: Command errored out with exit status 1: 'C:\Users\IC3\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IC3\\AppData\\Local\\Temp\\pip-install-v7nlp1rq\\tigramite_ebe1ab9fa0f04c4ea4e283de07b9517b\\setup.py'"'"'; __file__='"'"'C:\\Users\\IC3\\AppData\\Local\\Temp\\pip-install-v7nlp1rq\\tigramite_ebe1ab9fa0f04c4ea4e283de07b9517b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\IC3\AppData\Local\Temp\pip-record-q5e2snyq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\IC3\anaconda3\Include\tigramite' Check the logs for full command output.

**Comment by amansingh2896** [comment]
![error](https://user-images.githubusercontent.com/80960373/131081227-f68dffd7-e724-488e-9991-3749b15e0748.png)

**Comment by sagarsimha** [comment]
Are you running the latest version of Cython, 3.0?

**Comment by sagarsimha** [comment]
Also, we are soon releasing an update which would not require cython anymore.

**Comment by jakobrunge** [comment]
It's in the developer branch now. Would be great if you can test it!
