### ISSUE TITLE
error with GPDC

### ISSUE THREAD

**Issue by dirknbr** [jakobrunge/tigramite#147]
When I use the GPDC() test, I get this error

```
--> 568         val = dcor.distance_correlation(x_vals, y_vals, method='AVL')
    569         return val
    570 

NameError: name 'dcor' is not defined
```

I then installed and imported dcor but I still got the same error

Python 3.7

**Comment by sagarsimha** [comment]
Have you re-run setup.py after you installed dcor? You also need to re-import the kernel in case you are running on a jupyter notebook.

**Comment by dirknbr** [comment]
You are right, I think the restart fixed it.
