### ISSUE TITLE
The Direction of Causation

### ISSUE THREAD

**Issue by lannistercaer** [jakobrunge/tigramite#148]
HI, I have just tried PCMCI once with my dataset.

And I got a casual graph with no direction between any variables. I dont know what does that mean.

Is that because I did something wrong?

![image](https://user-images.githubusercontent.com/66576949/132543101-55a0702f-3fcc-4b7f-8f1c-ebb21104359f.png)

**Comment by sagarsimha** [comment]
Hi, please refer to this tutorial that explains the meaning of the edges without orientation - https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_pcmciplus.ipynb

Specifically, "graph[i,j,0]='o-o' and graph[j,i,0]='o-o' denotes an unoriented, contemporaneous adjacency $X^i_{t} - X^j_t$ indicating that the collider and orientation rules could not be applied (Markov equivalence)"

**Comment by lannistercaer** [comment]
hi, sagarsimha
 Thanks you for your answers 
 
"collider and orientation rules could not be applied (Markov equivalence)", does that mean orientation can not be figured out in this case.

**Comment by jakobrunge** [comment]
Basically yes, but read the papers:)
