### ISSUE TITLE
Error in plotting

### ISSUE THREAD

**Issue by amansingh2896** [jakobrunge/tigramite#152]
link_matrix = pcmci.return_significant_links(pq_matrix=results['p_matrix'],
                                                    val_matrix=results['val_matrix'], alpha_level=0.01)['link_matrix']

tp.plot_graph(val_matrix=results['val_matrix'],
              link_matrix=link_matrix,
              var_names=var_names,
              link_colorbar_label='cross-parcorr',
              node_colorbar_label='auto-parcorr')
plt.show()

IndexError                                Traceback (most recent call last)
<ipython-input-17-67ee05879879> in <module>
      3 
      4 
----> 5 tp.plot_graph(val_matrix=results['val_matrix'],
      6               link_matrix=link_matrix,
      7               var_names=var_names,

~\anaconda3\lib\site-packages\tigramite\plotting.py in plot_graph(link_matrix, val_matrix, sig_thres, var_names, fig_ax, figsize, save_name, link_colorbar_label, node_colorbar_label, link_width, link_attribute, node_pos, arrow_linewidth, vmin_edges, vmax_edges, edge_ticks, cmap_edges, vmin_nodes, vmax_nodes, node_ticks, cmap_nodes, node_size, node_aspect, arrowhead_size, curved_radius, label_fontsize, alpha, node_label_size, link_label_fontsize, lag_array, network_lower_bound, show_colorbar, inner_edge_style)
   1681 
   1682     if np.count_nonzero(link_matrix == "") == link_matrix.size or diagonal:
-> 1683         link_matrix[0, 1, 0] = "---"
   1684         no_links = True
   1685     else:
IndexError: index 1 is out of bounds for axis 1 with size 1
i can't remove this error can anyone help me out with this please

**Comment by sagarsimha** [comment]
Hi. "index 1 is out of bounds for axis 1 with size 1" in link_matrix seems to suggest that there is only one node (variable) in the data, at least for lag-zero. Can you check the data you fed in. In the newer update (on developer branch), we have replaced link_matrix with graph. Please try out the newer version while testing. If the problem persists, please send me the data so that I can reproduce the issue and look into it further.

**Comment by amansingh2896** [comment]
Hello sagarsimha i was able to do what you instructed.
Now i am dealing with a new error AttributeError: 'Polygon' object has no attribute 'clear'
can you please guide me through this

**Comment by sagarsimha** [comment]
https://github.com/jakobrunge/tigramite/issues/125
