### ISSUE TITLE
mismatch between results for return_significant_links and print_significant_links

### ISSUE THREAD

**Issue by lcastri** [jakobrunge/tigramite#156]
Hi Jakob,

I have a question about PCMCI+. 
I am using PCMCI+ on a system with 3 variables Dgh, V_h, G.
By using contemp_collider_rule = None, it orients the links: ($V_h$ -1) --> $Dgh$ <-- $G$  in the correct way (as you can see from the Collider orientation phase).
If I use print_significant_links the triple is still well oriented but then when I use return_significant_links the triple appears ambiguous. Why do I have this result?
Many thanks

Collider orientation phase

contemp_collider_rule = None
conflict_resolution = True

Orienting links among colliders:

    Collider ($V_h$ -1) --> $Dgh$ o-o $G$:
      Orient $G$ o-o $Dgh$ as $G$ --> $Dgh$ 

Updated adjacencies:

    Variable $Dgh$ has 3 link(s):
        ($Dgh$ -1)
        ($V_h$ -1)
        ($G$  0)

    Variable $V_h$ has 2 link(s):
        ($Dgh$ -1)
        ($V_h$ -1)

    Variable $G$ has 1 link(s):
        ($Dgh$ -1)

Rule orientation phase

Try rule(s) [1 2 3]

Updated adjacencies:

    Variable $Dgh$ has 3 link(s):
        ($Dgh$ -1)
        ($V_h$ -1)
        ($G$  0)

    Variable $V_h$ has 2 link(s):
        ($Dgh$ -1)
        ($V_h$ -1)

    Variable $G$ has 1 link(s):
        ($Dgh$ -1)

PCMCIplus algorithm finished.

Significant links at alpha = 0.01:

    Variable $Dgh$ has 3 link(s):
        ($Dgh$ -1): pval = 0.00000 | val =  0.340
        ($V_h$ -1): pval = 0.00000 | val =  0.163
        ($G$  0): pval = 0.00400 | val =  0.062

    Variable $V_h$ has 2 link(s):
        ($Dgh$ -1): pval = 0.00000 | val =  0.388
        ($V_h$ -1): pval = 0.00500 | val =  0.062

    Variable $G$ has 1 link(s):
        ($Dgh$ -1): pval = 0.00000 | val =  0.413

Returning results for optimal pc_alpha = 0.05

Scores for individual pc_alpha values:

   pc_alpha =    0.05 yields score = -830.76447
   pc_alpha =    0.01 yields score = -830.76447

Significant links at alpha = 0.01:

    Variable $Dgh$ has 3 link(s):
        ($Dgh$ -1): pval = 0.00000 | val =  0.340
        ($V_h$ -1): pval = 0.00000 | val =  0.218
        ($G$  0): pval = 0.00400 | val =  0.062

    Variable $V_h$ has 1 link(s):
        ($Dgh$ -1): pval = 0.00000 | val =  0.187

    Variable $G$ has 2 link(s):
        ($Dgh$ -1): pval = 0.00000 | val =  0.377
        ($Dgh$  0): pval = 0.00400 | val =  0.062

**Comment by jakobrunge** [comment]
Can you give us the data to reproduce?

**Comment by lcastri** [comment]
Hi Jakob,
this is the dataset .csv used for that simulation.
Thanks

[Simulation.zip](https://github.com/jakobrunge/tigramite/files/7496004/Simulation.zip)

**Comment by jakobrunge** [comment]
Can you give us the full script?

Am 8. November 2021 02:05:27 schrieb lcastri ***@***.***>:

**Comment by lcastri** [comment]
[code.tar.gz](https://github.com/jakobrunge/tigramite/files/7521805/code.tar.gz)

**Comment by sagarsimha** [comment]
@lcastri Hi. Have you found the solution to this?

**Comment by lcastri** [comment]
Hi, not yet. But, in the new version, I noticed that the method "return_significant_link" is marked as "DEPRECATED" so maybe the mismatch is not anymore present.
