### ISSUE TITLE
Parallel PCMCI+

### ISSUE THREAD

**Issue by jjakenichol** [jakobrunge/tigramite#157]
There is not a parallel implementation of PCMCI Plus, correct? Is one in the works? If not, I may work on that if I end up needing a nonlinear method for my work.

**Comment by jakobrunge** [comment]
The algorithm is harder to parallelize, that's why there currently isn't a script for it.

**Comment by jakobrunge** [comment]
Update: I just added a version to the developer branch. It only parallelizes the easier step 1 lagged condition selection on the lagged paraents, the rest is done on the master node...
Happy for feedback!

**Comment by jjakenichol** [comment]
Thanks! I'll have a look sometime soon.

**Comment by SaharaAli16** [comment]
Hi, I am running the parallel PCMCI+ version on my dataset that comprised 5 time-series variables and had a total of 15000 records. When I run this using ParCorr() test, the code works fine. But when I run it with GPDC(), I don't get any result and the program terminates after exhausting the max execution time specified. I was running this code through slurm jobs and even after 200 hours of execution, I got no results for a 'max_lag' of 15. Nothing gets printed out after this:

```
##
## Step 1: PC1 algorithm with lagged conditions
##

Parameters:
selected_links = {0: [], 1: [], 2: [], 3: [(0, 0), (0, -1), (0, -2), (0, -3), (0, -4), (0, -5), (0, -6), (0, -7), (0, -8), (0, -9), (0, -10), (0, -11), (0, -12), (0, -13), (0, -14), (0, -15), (0, -16), (0, -17),$
independence test = gp_dc
tau_min = 1
tau_max = 15
pc_alpha = [0.01]
max_conds_dim = None
max_combinations = 1
```

**Comment by jakobrunge** [comment]
GPDC is a more demanding method, try the GPU-version GPDCtorch.
