### ISSUE TITLE
ParCor changing value

### ISSUE THREAD

**Issue by augo92** [jakobrunge/tigramite#158]
Hello,
Can you please confirm whether or not one should expect some causal values to change for PCMCI+ when rerunning the same data set and using Partial Correlation (i.e., no Shuffle Test)? I am not changing any parameters in the data or the tigramite code, just rerunning.

Thanks,
Augo92

**Comment by jakobrunge** [comment]
That shouldn't happen. Can you send an example?

**Comment by augo92** [comment]
Let me confirm on my end that this is really what is happening. Either way, I'll let you know.

**Comment by augo92** [comment]
It was indeed an issue on my end, not the code. Sorry for the confusion. I will close the Issue.
