### ISSUE TITLE
How to handle features with variance = 0

### ISSUE THREAD

**Issue by scottfleming** [jakobrunge/tigramite#168]
Curious if you have any thoughts about how to handle features with constant values? [Currently](https://github.com/jakobrunge/tigramite/blob/master/tigramite/independence_tests/parcorr.py#L95) the default behavior is just to throw a `ValueError` saying that there are `nans after standardizing, possibly constant array!` It seems to me, though, that this might be better treated as a warning, and that the algorithm can subsequently just assume that any independence tests will reveal that the constant feature is completely independent of any other features? In other words, suppose that the feature vector were fixed to be all zeros, would any other downstream part of the analysis necessarily break?

**Comment by jakobrunge** [comment]
Constant features make no sense to include. But I can see, that in an automated pipeline this might occur and you want it to be treated differently... I'll think about it!

**Comment by jakobrunge** [comment]
We've now implemented ignoring constant arrays!
