### ISSUE TITLE
error: name 'dcor' is not defined error

### ISSUE THREAD

**Issue by amansingh2896** [jakobrunge/tigramite#170]
while using GPDC conditional independence test i am getting the error " name 'dcor' is not defined". can you help me out.

**Comment by sagarsimha** [comment]
dcor is only required when using GPDC. This is detailed in the Readme. You can install it from the conda channels. Look into the setup.py for the appropriate version to install.

**Comment by amansingh2896** [comment]
i installed dcor 0.5.3 package and imported but it's still showing the same error.

**Comment by sagarsimha** [comment]
Have you reinstalled with python setup.py develop, and reimport the kernel in case you are using a jupyter notebook?

**Comment by amansingh2896** [comment]
sir,
above problem got resolved but earlier i have used CMIknn method and i was able to run that but now when i am using it i am getting an error name 'tigramite_cython_code' is not defined this is a recent problem i am facing what can be the reason?

**Comment by sagarsimha** [comment]
In the latest developer, the cython code base dependency has been completely removed. This will soon be merged into the master as well.

**Comment by amansingh2896** [comment]
sorry i didn't understood I am a beginner to this. so like what is the solution or how long will it take to get resolved?

**Comment by sagarsimha** [comment]
Please use the latest code in the 'developer' branch. You will not face the error.

**Comment by amansingh2896** [comment]
It would be very helpful if you can share the link to the codes.

**Comment by sagarsimha** [comment]
https://github.com/jakobrunge/tigramite/tree/developer

**Comment by amansingh2896** [comment]
> https://github.com/jakobrunge/tigramite/tree/developer

using developer code when i tried running i got the error "run_pcmci() got an unexpected keyword argument 'alpha_level'"

**Comment by amansingh2896** [comment]
i am using version 4.2.2.1 of tigramite. as instructed by you when i ran the code i got an error 'run_pcmci() got an unexpected keyword argument 'alpha_level''

**Comment by sagarsimha** [comment]
I think you are referring to the tutorials of 4.3 while using code base of 4.2.2.1. Note that alpha_level is a new parameter in 4.3. 

https://github.com/jakobrunge/tigramite/blob/developer/tutorials/tigramite_tutorial_basics.ipynb

**Comment by raum96** [comment]
one last problem while running GPDC getting this 
C:\Users\IC3\anaconda3\lib\site-packages\sklearn\gaussian_process\_gpr.py:610: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
C:\Users\IC3\anaconda3\lib\site-packages\sklearn\gaussian_process\_gpr.py:610: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
also how to get link matrix for GPDC test?

**Comment by raum96** [comment]
one last problem How to get link matrix in earlier version i used to get link matrix by link_matrix but in newer version i can't use this. Can you help me in getting the link_matrix?

**Comment by sagarsimha** [comment]
link_matrix is now replaced with 'graph' object. have a look at the tutorials to know the usage. you can checkout the latest release available on master - v5.0.0
