### ISSUE TITLE
how to upgrade to version 4.3 in windows

### ISSUE THREAD

**Issue by raum96** [jakobrunge/tigramite#172]
Hello,
Currently i am using version 4.2.2.1 and i want to upgrade to version 4.3 so that i can use codes from developer branch. can someone tell me how to upgrade or how to run developer code in current version. Thankyou for helping

**Comment by sagarsimha** [comment]
You'd have to first pull the latest developer (4.3) and then merge with the master (4.2.2.1)

**Comment by raum96** [comment]
> You'd have to first pull the latest developer (4.3) and then merge with the master (4.2.2.1)

i installed the developer version through pip install git+https://github.com/jakobrunge/tigramite.git@developer. now when i chech the version of tigramite using pip3 list it is showing version 5.0.0 and when i ran the cmiknn code i got the error "query() got an unexpected keyword argument 'workers'". Have i downloaded the latest version and if yes then what is this error?

**Comment by raum96** [comment]
> > You'd have to first pull the latest developer (4.3) and then merge with the master (4.2.2.1)
> 
> i installed the developer version through pip install git+https://github.com/jakobrunge/tigramite.git@developer. now when i chech the version of tigramite using pip3 list it is showing version 5.0.0 and when i ran the cmiknn code i got the error "query() got an unexpected keyword argument 'workers'". Have i downloaded the latest version and if yes then what is this error?

@sagarishmha anything i am missing that i should do to remove it?

**Comment by sagarsimha** [comment]
'workers' is a parameter used within a method in scipy. Can you check that the versions of numpy, scipy and numba you are using are in accordance with the requirements mentioned here?
https://github.com/jakobrunge/tigramite/blob/developer/environment_py3.yml

**Comment by raum96** [comment]
> 'workers' is a parameter used within a method in scipy. Can you check that the versions of numpy, scipy and numba you are using are in accordance with the requirements mentioned here? https://github.com/jakobrunge/tigramite/blob/developer/environment_py3.yml

except numba everything is in accordance with it. i am trying to upgrade numba and then run it again
