### ISSUE TITLE
'Polygon' object has no attribute 'clear'

### ISSUE THREAD

**Issue by AviralKumarTiwari** [jakobrunge/tigramite#179]
Dear Sir,
When we are using following codes:

# Plot time series graph    
tp.plot_time_series_graph(
    figsize=(10, 6),
    val_matrix=results['val_matrix'],
    link_matrix=link_matrix,
    var_names=var_names,
    link_colorbar_label='MCI',
    ); plt.show()

we get an error msg that 
File "<ipython-input-20-181b02a9584c>", line 2, in <module>
    tp.plot_time_series_graph(

  File "C:\Users\aviral\anaconda3\lib\site-packages\tigramite\plotting.py", line 2234, in plot_time_series_graph
    node_labels = ["" for i in range(N * max_lag)]

  File "C:\Users\aviral\anaconda3\lib\site-packages\tigramite\plotting.py", line 1378, in _draw_network_with_curved_edges
    cb_e.outline.clear()

AttributeError: 'Polygon' object has no attribute 'clear'

Can you please help me solve the issue?
I even tried using  del cb_e.outline.[:]  option for cb_e.outline.clear() but it seems it does  not work.

**Comment by sagarsimha** [comment]
https://github.com/jakobrunge/tigramite/issues/125

**Comment by AviralKumarTiwari** [comment]
Dear Sir
Now I have another error:

---------------------------------------------------------------------------TypeError
                                Traceback (most recent call
last)<ipython-input-13-853c74aaac64> in <module>      1 q_matrix =
pcmci.get_corrected_pvalues(p_matrix=results['p_matrix'], tau_max=8,
fdr_method='fdr_bh')----> 2 pcmci.print_significant_links(      3
   p_matrix = results['p_matrix'],      4         q_matrix = q_matrix,
     5         val_matrix = results['val_matrix'],
TypeError: print_significant_links() got an unexpected keyword
argument 'q_matrix'

**Comment by sagarsimha** [comment]
https://github.com/jakobrunge/tigramite/issues/125

**Comment by BeckyChanZC** [comment]
I am having the same problem, even though I have upgraded matplotlib, it still shows 'Polygon' object has no attribute 'clear'. I also changed the code as required by the latest version 5.0. Why is there still a problem? Thank you very much.

**Comment by sagarsimha** [comment]
Do you still have this issue?
