### ISSUE TITLE
warning in GPDC

### ISSUE THREAD

**Issue by amansingh2896** [jakobrunge/tigramite#184]
Hello thankyou for a wonderful support,
I would ask for your help
while i am using GPDC conditional independence test i am not getting the results and my code is showing 
C:\Users\IC3\anaconda3\lib\site-packages\sklearn\gaussian_process\_gpr.py:610: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
In the previous version it used to run smooth but now its not running
what should i do to get the required results?
thanks for helping

**Comment by sagarsimha** [comment]
This seems to be a warning from within scikit-learn's GaussianProcessRegressor class. As a first step, can you confirm the version of scikit-learn you are using and if it is in accordance with the recommended version? There have been no new changes to the gpdc. If it persists, then please also send your code setup that is calling the gpdc

**Comment by amansingh2896** [comment]
my scikit-learn version is 1.0.2 which satisfies the basic requirement. what i did is i reinstalled scikit-learn with an older version .23.1 now the code is running but i am getting an error 
'str' object has no attribute 'decode

**Comment by amansingh2896** [comment]
in older version of tigramite this used to run smooth now i am facing a lot pf problem with it.

**Comment by sagarsimha** [comment]
I am able to run the GPDC test successfully without warnings with the latest tigramite version (5.0.0.2) and latest scikit-learn (1.0.2). 
Relooking at your issue, I feel it may have to do with your data pre-processing with newer scikit-learn libraries before you are passing it into tigramite. It is not clear from the warning you have posted above whether it is occurring within GPDC framework or before it. 
As I said before, please send the minimal data and your code setup, ideally on a jupyter notebook so that I can reproduce the issue and help you diagnose the problem.

**Comment by amansingh2896** [comment]
hello sir,
https://drive.google.com/drive/folders/1ab6lOZaEY0F-QhgI1iVnNqV-VM6O6lCY?usp=sharing
this is the google drive link where i have uploaded the data as well as the jupyter code.

**Comment by amansingh2896** [comment]
hello sir,
did you get the chance to see the warning? as far as i can understand warning is coming from scikit-learn but what makes me think is earlier it was not showing any error but now it's showing.
thankyou

**Comment by sagarsimha** [comment]
I had a look. I also tested with tigramite 4.3. The warning persists even in the previous version, which means it is not a tigramite version issue.

This **warning** seems to be a convergence issue that has to do with the scale of the data and the optimizer within sklearn. This will help understand the issue, also look into possible solutions
https://stackoverflow.com/questions/62658215/convergencewarning-lbfgs-failed-to-converge-status-1-stop-total-no-of-iter

GPDC internally does a standard scaling. So, you'd have to look into the GP optimizer. Increasing max_iter doesn't seem to be straightforward. n_restarts_optimizer may be a parameter to experiment on. You could also try supplying more time samples with the heuristic as detailed in the stackoverflow above.

https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html

**Comment by sagarsimha** [comment]
You can also experiment with the GPDCtorch(). It uses the gpytorch for gaussianprocessregression instead of the one in sklearn. It can work both with CPU and the GPU.

https://github.com/jakobrunge/tigramite/blob/master/tigramite/independence_tests/gpdc_torch.py
