### ISSUE TITLE
Getting tigramite on PyPI and anaconda cloud

### ISSUE THREAD

**Issue by ewengillies** [jakobrunge/tigramite#2]
To ensure tigramite can be used by many, we need to ensure it is distributed on conventional channels, like the Python Package Index.  Here is my breakdown of this goal:

 - [x] Ensure installation is working.
 - [x] Figure out which dependencies are needed.
 - [x] Test the current software.
 - [x] Tag and version the software.
 - [x] Release version on PyPI and anaconda cloud

**Comment by jakobrunge** [comment]
Yes, this was my plan, too!


Am 1. August 2017 13:21:26 schrieb Ewen Gillies <notifications@github.com>:
