### ISSUE TITLE
Error: 'tigramite_cython_code' is not defined

### ISSUE THREAD

**Issue by ghost** [jakobrunge/tigramite#21]
Hi,

After installing the required packages (including cython), when I run the setpu.py script, I see:
`skipping 'tigramite/tigramite_cython_code.c' Cython extension (up-to-date)`
in the output. After that,  when I try to run the notebook, I have the following error at the execution of the cell 17 (GPDC) and the cell 22 (CMIknn):

`name 'tigramite_cython_code' is not defined`

Did you already experience this problem ?

**Comment by jakobrunge** [comment]
Dear Moakra,
this is related to cython code not working. DId you install cython including gcc and did tigramite install without errors?
Btw, Tigramite is currently being re-written and will be updated soon (more under the hood, though).
~Jakob

**Comment by ghost** [comment]
Dear Jacob,

I solved the problem by running:
`pip install -e .`

instead of 
`python setup.py install`

Thank you!

**Comment by kfedotov-flc** [comment]
I've ran into this same issue. No errors when installing but do get those errors in the cells mentioned:


results = pcmci_gpdc.run_pcmci(tau_max=2, pc_alpha=0.1)

pcmci_gpdc._print_significant_links(

        p_matrix = results['p_matrix'], 

        val_matrix = results['val_matrix'],

        alpha_level = 0.01)
NameError                                 Traceback (most recent call last)
<ipython-input-15-1d47a4873c6c> in <module>()
----> 1 results = pcmci_gpdc.run_pcmci(tau_max=2, pc_alpha=0.1)
      2 pcmci_gpdc._print_significant_links(
      3         p_matrix = results['p_matrix'],
      4         val_matrix = results['val_matrix'],
      5         alpha_level = 0.01)

~/tigramite/tigramite/pcmci.py in run_pcmci(self, selected_links, tau_min, tau_max, save_iterations, pc_alpha, max_conds_dim, max_combinations, max_conds_py, max_conds_px, fdr_method)
   1383             pc_alpha=pc_alpha,
   1384             max_conds_dim=max_conds_dim,
-> 1385             max_combinations=max_combinations,
   1386             )
   1387 

~/tigramite/tigramite/pcmci.py in run_pc_stable(self, selected_links, tau_min, tau_max, save_iterations, pc_alpha, max_conds_dim, max_combinations)
    726                                             pc_alpha=pc_alpha,
    727                                             max_conds_dim=max_conds_dim,
--> 728                                             max_combinations=max_combinations,
    729                                             )
    730                 all_parents[j] = result['parents']

~/tigramite/tigramite/pcmci.py in _run_pc_stable_single(self, j, selected_links, tau_min, tau_max, save_iterations, pc_alpha, max_conds_dim, max_combinations)
    521                         Y=[(j, 0)],
    522                         Z=Z,
--> 523                         tau_max=tau_max,
    524                     )
    525 

~/tigramite/tigramite/independence_tests.py in run_test(self, X, Y, Z, tau_max)
    476 
    477         else:
--> 478             val = self.get_dependence_measure(array, xyz)
    479 
    480         if self.significance == 'analytic':

~/tigramite/tigramite/independence_tests.py in get_dependence_measure(self, array, xyz)
   1966         y = self._get_single_residuals(array, target_var=1)
   1967 
-> 1968         val = self._get_dcorr(numpy.array([x, y]))
   1969 
   1970         return val

~/tigramite/tigramite/independence_tests.py in _get_dcorr(self, array_resid)
   1998         x, y = self._trafo2uniform(array_resid)
   1999 
-> 2000         dc, val, dvx, dvy = tigramite_cython_code.dcov_all(x, y)
   2001 
   2002         return val

NameError: name 'tigramite_cython_code' is not defined

**Comment by shaypal5** [comment]
Ran into this myself. Had to `pip install cython`, and then explicitly run `python setup.py build_ext` and finally install in dev mode (`pip install` with the `-e` flag) to get all tests to pass without seeing this error.

See this travis build over my fork (and the difference of `.travis.yml` from the original one) :
https://travis-ci.org/shaypal5/tigramite/builds/495463841

Surprisingly, this exact combination was required; any subset did not work (see other travis builds on my fork).

From the little bit I know of how installing in dev mod works (it kinda symlinks the `sitepackages` package dir to the repo instead of packaging everything and putting it there), it might be that the files being built by the `build_ext` command are not packaged and installed into `sitepackges` on a regular `pip install`; presumably, then, the symlink-ish nature of the dev install makes them available, as they are built inside the local repo folder.

**Comment by yuditsabet** [comment]
Hi,
I have this error when run:
pcmci.run_pcmci(tau_min =1, tau_max=30, pc_alpha=0.1)

independence_tests.py:1144: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  beta_hat = numpy.linalg.lstsq(z, y)[0]
Traceback (most recent call last):
  File "tigramite_era_geo_corpar.py", line 53, in <module>
    results_pcmi = pcmci.run_pcmci(tau_min =1, tau_max=3, pc_alpha=0.1)
  File "/home/yuditsabet/.local/lib/python3.7/site-packages/tigramite/pcmci.py", line 1385, in run_pcmci
    max_combinations=max_combinations,
  File "/home/yuditsabet/.local/lib/python3.7/site-packages/tigramite/pcmci.py", line 718, in run_pc_stable
    print("\n## Variable %s" % self.var_names[j])
KeyError: 132

Besides, when run:
pcmci.run_gpdc(tau_min =1, tau_max=30, pc_alpha=0.1) not end
how long does it take if the process is not parallelized??

**Comment by 27Topquark** [comment]
Followed shaypal5 

got the following error after running python setup.py build_ext

cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\python3.6\include -IC:\python3.6\include -IC:\venv\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Stu
dio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\
ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits
\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tctigramite\tigramite_cython_code.c /Fobuild\temp.win-amd64-3.6\Release\tigr
amite\tigramite_cython_code.obj
error: command 'cl.exe' failed: No such file or directory

**Comment by MANIBIALOA** [comment]
Bonjou, moi j'obtiens l'erreur apres installation du package tigramite pip install tigramite ça me dit Error

**Comment by Capricornus-Jay** [comment]
Hi, When I run the GPDC test remotely, the name 'tigramite_cython_code' is not defined, I have run pip install cython, python setup.py build_ext and pip install -e. My local computer runs the above three entries fine, and remote Linux runs these three lines of code without error, but running on pycharm still reports the above error.

**Comment by tianxiongxie** [comment]
> Hi, When I run the GPDC test remotely, the name 'tigramite_cython_code' is not defined, I have run pip install cython, python setup.py build_ext and pip install -e. My local computer runs the above three entries fine, and remote Linux runs these three lines of code without error, but running on pycharm still reports the above error.

Hello, hava you solved this problem?

**Comment by Capricornus-Jay** [comment]
Hello , the remote environment is not solved, there are still problems.But the jupyter notebook can run GPDC without errors.



在 2021-05-08 23:52:30，"ibear" ***@***.***> 写道：

Hi, When I run the GPDC test remotely, the name 'tigramite_cython_code' is not defined, I have run pip install cython, python setup.py build_ext and pip install -e. My local computer runs the above three entries fine, and remote Linux runs these three lines of code without error, but running on pycharm still reports the above error.

Hello, hava you solved this problem?

**Comment by sagarsimha** [comment]
We are migrating all of the cython code to pure python with similar speed as cython. You can expect it in the forthcoming update. Will write back here once done.

**Comment by Capricornus-Jay** [comment]
Thank you for your reply, I appreciate it.



At 2021-06-08 18:31:26, "Sagar Nagaraj Simha" ***@***.***> wrote:

We are migrating all of the cython code to python environment. You can expect it in the forthcoming update. Will write back here once done.
