### ISSUE TITLE
Masking introducing discontinuities

### ISSUE THREAD

**Issue by sashastrelnikoff** [jakobrunge/tigramite#213]
When applying PCMCI with masking (assuming mask_type='xyz' for simplicity) does this effectively introduce an artificial discontinuity between the start and end points of the mask? For example, when filtering out the summer months in the masking tutorial, does this not introduce a discontinuity wherein the end of the previous winter season is stitched to the beginning of the next? If so, doesn't this make the masked data violate the stationarity assumption of PCMCI?

In order to preserve stationarity, I would imagine that it would make most sense for PCMCI to use the first tau_max data points of the beginning of each unmasked area only as delayed causes for the points _within the same mask_ after tau_max so as to not use the end of the previous mask as causes for the beginning of the next.

**Comment by jakobrunge** [comment]
That is exactly what's happening in Tigramite...
