### ISSUE TITLE
Sliding window analysis does not work with the CMIsymb CI test

### ISSUE THREAD

**Issue by gwinch97** [jakobrunge/tigramite#214]
Hi,

I just wanted to highlight that the sliding window analysis does not work with symbolic timeseries, or more specifically when using the CMIsymb CI test. This is because the datatype input to CMIsymb is integer whilst the sliding window method utilizes NaN values to discount current time window values.

Thus you either get the error "cannot convert float NaN to integer" when your data is of type int or "Input data must be of integer type, where each number indexes a symbol." when your data is of type float32. 

This would be fixable by utilizing some invalid value such as e.g. -99999 instead of NaN values at lines 4030-4032 in pcmci.py for discrete/symbolic data and then have a subsequent change in the run_pcmci method to reflect this. However, I'm not sure if I know the code well enough to implement this fix.

**Comment by jakobrunge** [comment]
Thanks for raising this. I fixed it by changing CMIsymb. It now issues a warning if a non-int array is passed instead of an error. Then the float array will be converted assuming users know what they do. So you should be able to convert your array to float and use sliding windows as it is.
