### ISSUE TITLE
Interventional data

### ISSUE THREAD

**Issue by christianreiser** [jakobrunge/tigramite#215]
In many applications, observational data is abundant, but some interventional data is also available.

I plan to **extend LPCMCI to further reduce the PAG by using interventional data** to get closer to the data-generating process.

**For example**
```
 if LPCMCIs output between variable A and B is Ao->B (unsure if A is an ancestor or not), and we additionally have data of a randomized intervention on A:
    if (on the interventional data on A, A is dependent on B): 
        then A is an ancestor of B: A→B
    else (if on this data A is independent of B):
        then A is not an ancestor of B: A<->B
```

**More general:**
```
For all intervened variables:
    For all adjacencies of the intervened variable:
        If (intervened variable is independent of adjacency in its interventional data):
            The intervened variable is not an ancestor of the adjacent variable
        Else: 
            The intervened variable is an ancestor of the adjacent variable.
```

**My questions are:**

1. Do you think it is possible to extend LPCMCI to use interventional data?
2. If yes, would it be best first to use only interventional data to remove -and orient links, then use this result to initialize LPCMCI instead of a fully connected graph. This would be identical to handling background knowledge if I understand your paper correctly. 
3. Do you have more thoughts about combining interventional and observational data?

Thank your fantastic work!

**Comment by jakobrunge** [comment]
Checkout the new link_assumptions parameter in all methods. See the LPCMCI tutorial.
