### ISSUE TITLE
Trouble running GPDC test through PyPI package on Colab

### ISSUE THREAD

**Issue by SaharaAli16** [jakobrunge/tigramite#226]
Hi,

I am running tigramite 5.0.0 on Google Colab by installing tigramite PyPI package. When I import GPDC independence test from tigramite and call the run_pcmci() function, I get the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-12-fa9d474017c4>](https://localhost:8080/#) in <module>()
----> 1 results = pcmci_gpdc.run_pcmci(tau_max=12, pc_alpha=0.1, alpha_level = 0.01)


[/usr/local/lib/python3.7/dist-packages/tigramite/independence_tests/gpdc.py](https://localhost:8080/#) in _get_dcorr(self, array_resid)
    565         # array_resid = self._remove_ties(array_resid, verbosity=4)
    566         x_vals, y_vals = self._trafo2uniform(array_resid)
--> 567         val = dcor.distance_correlation(x_vals, y_vals, method='AVL')
    568         return val
    569 

NameError: name 'dcor' is not defined
```

I am following the basic [tutorial ](https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_basics.ipynb)on running pcmci given at your github repo. I believe the PyPI package doesn't have the updated gpdc.py code. Can you look into this?

**Comment by sagarsimha** [comment]
You need to install dcor. Please look into the [Optional packages depending on used functions](https://github.com/jakobrunge/tigramite#optional-packages-depending-on-used-functions) and [Installation](https://github.com/jakobrunge/tigramite#installation) in Readme.

**Comment by SaharaAli16** [comment]
Got it. It's working fine now. Thanks.
