### ISSUE TITLE
Error when using mask in explaining correlations tutorial

### ISSUE THREAD

**Issue by emfons** [jakobrunge/tigramite#227]
In the new Explaining correlations tutorial, there is the option to use a mask for the dataframe, but when I do set the mask to non-None, the tutorial fails when trying to fit the prediction. When I set the mask to None though, the tutorial runs smoothly. 

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [39], in <cell line: 1>()
----> 1 prediction.fit(target_predictors=parents, tau_max=tau_max, return_data=False)
      3 # print(prediction.fitted_model)
      4 predicted = prediction.predict(target=[j for j in parents if len(parents[j]) > 0])

File /net/n2o/wolke/emfons/tigramite/tigramite/models.py:1379, in Prediction.fit(self, target_predictors, selected_targets, tau_max, return_data)
   1375     if target not in list(self.target_predictors):
   1376         raise ValueError("No predictors given for target %s" % target)
   1378 self.fitted_model = \
-> 1379     self.get_fit(all_parents=self.target_predictors,
   1380                  selected_variables=self.selected_targets,
   1381                  tau_max=tau_max,
   1382                  return_data=return_data)
   1383 return self

File /net/n2o/wolke/emfons/tigramite/tigramite/models.py:411, in Models.get_fit(self, all_parents, selected_variables, tau_max, cut_off, return_data)
    408 X = [(j, 0)]  # dummy
    409 Z = self.all_parents[j]
    410 array, xyz = \
--> 411     self.dataframe.construct_array(X, Y, Z,
    412                                    tau_max=self.tau_max,
    413                                    mask_type=self.mask_type,
    414                                    cut_off=cut_off,
    415                                    remove_overlaps=True,
    416                                    verbosity=self.verbosity)
    417 # Get the dimensions out of the constructed array
    418 dim, T = array.shape

File /net/n2o/wolke/emfons/tigramite/tigramite/data_processing.py:838, in DataFrame.construct_array(self, X, Y, Z, tau_max, extraZ, mask, mask_type, return_cleaned_xyz, do_checks, remove_overlaps, cut_off, verbosity)
    836     mask_ens_member = np.zeros((dim, len(ref_points_here)), dtype = ens_member_data.dtype)
    837     for i, (var, lag) in enumerate(XYZ):
--> 838         mask_ens_member[i, :] = _mask[ens_member_key][ref_points_here + lag, var]
    840 # Take care of masking
    841 use_indices_ens_member = np.ones(len(ref_points_here), dtype = 'int')

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Maybe this comes from the new _check_mask function? There's one comment that seems to indicate full compatibility of this function was not tested out. 

   # ########################################################################
        # ## HACK:
        # # (needed for compatibility with pcmci.py)
        # # (unsure about compatibility with models.py)
        # if _use_mask is self.mask:
        #     return _use_mask
        ########################################################################

**Comment by jakobrunge** [comment]
Should be fixed in the master now.

**Comment by AyinMostima** [comment]
> 现在应该在master中修复了。

This problem still seems to be unresolved...

**Comment by jakobrunge** [comment]
Ok, I looked at it again and found another bug, try now!

**Comment by AyinMostima** [comment]
> Ok, I looked at it again and found another bug, try now!

Thank you for your work, it's up and running~
