### ISSUE TITLE
Negative CMI in blue ?

### ISSUE THREAD

**Issue by ghost** [jakobrunge/tigramite#23]
Hi,

In the notebook you provide with tigramite, I see that the MCI can be negative (presented in blue). However, in the equation 4 and 5 of [your paper](https://arxiv.org/pdf/1210.2748.pdf), it shows that the MCI is positive. How is it possible to plot negative MCI values ?

Thanks in advance for your help!

**Comment by jakobrunge** [comment]
Dear Moakra

The MCI test stands for momentary conditional Independence test. MCI can be 
combined with any conditional dependence measure. If it's partial 
correlation, it can be positive or negative. If it's conditional mutual 
information (CMI), then I call the dependence measure momentary information 
transfer (MIT) as in the paper you mention. The theoretical MIT measure is 
positive indeed. However, the k-nearest-neighbor estimator (see  Frenzel 
2007 reference in documentation of tigramite) for CMI can become slightly 
negative, which should be interpreted as zero. This estimator has the 
advantage that it is asymptotically unbiased.

Best
Jakob


Am 13. Oktober 2018 05:06:07 schrieb moakra <notifications@github.com>:

**Comment by moakra** [comment]
I see. Thank you Jacob for your answer.
I have a quick question: My sensitive data contains 10 time series, with length 51 data points each only.

Given the length of these time series, can I apply the methods you used in your [paper](https://arxiv.org/abs/1702.07007) "Detecting causal associations in large nonlinear time series datasets" to analyse causal relationships between them ?

Again, thank you Jacob for your help!
