### ISSUE TITLE
issue with correlation example

### ISSUE THREAD

**Issue by andrewcz** [jakobrunge/tigramite#230]
Hi, trying to run through correlation example and getting the below error.

![pic-selected-220716-1409-12](https://user-images.githubusercontent.com/2296335/179338708-0372f910-ca76-494f-92aa-ba52f750569f.png)

**Comment by andrewcz** [comment]
@jakobrunge

**Comment by jakobrunge** [comment]
Should be fixed in the master now. Please test on your machine and let us know.
