### ISSUE TITLE
Slow for certain datasets

### ISSUE THREAD

**Issue by rfw-exp** [jakobrunge/tigramite#236]
For some datasets, LPCMCI can get stuck in the non-ancestral phase while checking all the subsets of S_search_XY for conditional independence (due to combinations growing very large very quickly). I can set max_q_global, but this will affect the ancestral phase and I don't really want to set max_p_non_ancestral because for some datasets I will need it incredibly low to run in a reasonable timeframe.
Are there any other options, maybe introduce a max_q_non_ancestral?

**Comment by jakobrunge** [comment]
This is still experimental, you can play around to see what works...
