### ISSUE TITLE
[Typo] Minor typo issue in neurips2020/lpcmci.py

### ISSUE THREAD

**Issue by AmanTiwari1503** [jakobrunge/tigramite#237]
Found the following typo error in the file - neurips2020/lpcmci.py in the `master` branch - 

Line 788 - `if test_X and len(S_seach_XY) < p_pc:`

Kindly correct the variable `S_seach_XY` to `S_search_XY`

**Comment by jakobrunge** [comment]
I don't see that typo in the current master branch...

**Comment by AmanTiwari1503** [comment]
Kindly refer to this line [https://github.com/jakobrunge/tigramite/blob/3e124011083c0e8401e1a648888d9ab26639843b/neurips2020/lpcmci.py#L788](https://github.com/jakobrunge/tigramite/blob/3e124011083c0e8401e1a648888d9ab26639843b/neurips2020/lpcmci.py#L788)
