### ISSUE TITLE
Issue with "Symbolic time series"

### ISSUE THREAD

**Issue by aa-fr-75** [jakobrunge/tigramite#24]
Hi Jakob
Your work on tigramite and PCMCI is impressive! Great Work! 
I have one question regarding Symbolic time series.
I am trying your jupiter notebook and get the following error:
"\lib\site-packages\tigramite-3.0b0-py2.7-win-amd64.egg\tigramite\independence_tests.pyc in _bincount_hist(self, symb_array, weights)
   2494         # Needed because numpy.bincount cannot process longs
   2495         if type(self.n_symbs ** dim) != int:
-> 2496             raise ValueError("Too many n_symbs and/or dimensions, "
   2497                              "numpy.bincount cannot process longs")
   2498         if self.n_symbs ** dim * 16. / 8. / 1024. ** 3 > 3.:

ValueError: Too many n_symbs and/or dimensions, numpy.bincount cannot process longs"
Is it something you are aware of? Do you have any simple workaround?
I will try to investigate that.
Thanks for your help!

**Comment by jakobrunge** [comment]
Hi, the error message means that the combination of too many kinds of 
symbols and high dimensions cannot be processed due to numpy limitations. 
Try to limit the number of symbols that the input data contains and/or the 
max_conds parameter.

Am 16. Oktober 2018 23:08:44 schrieb aa-fr-75 <notifications@github.com>:

**Comment by aa-fr-75** [comment]
Thanks Jakob
I try it without success.
Strange but type(self.n_symbs ** dim) is long with n_symbs=5  and dim=2.
If I remove the test, the jupyter code is working properly.
I believe that somehow symb_array is converted to long.
I will try to investigate that.

**Comment by jakobrunge** [comment]
Thanks, I will also look into this soon, it was a problem of older numpy, 
but maybe newer versions don't have that issue anymore...

Am 17. Oktober 2018 00:28:07 schrieb aa-fr-75 <notifications@github.com>:
