### ISSUE TITLE
Parallel PCMCI+ with GPDC()

### ISSUE THREAD

**Issue by SaharaAli16** [jakobrunge/tigramite#242]
Hi, I am running the parallel PCMCI+ version on my dataset that comprised 5 time-series variables and had a total of 15000 records. When I run this using ParCorr() test, the code works fine. But when I run it with GPDC(), I don't get any result and the program terminates after exhausting the max execution time specified. I was running this code through slurm jobs and even after 200 hours of execution, I got no results for a 'max_lag' of 15. Nothing gets printed out after this:
```
##
## Step 1: PC1 algorithm with lagged conditions
##

Parameters:
selected_links = {0: [], 1: [], 2: [], 3: [(0, 0), (0, -1), (0, -2), (0, -3), (0, -4), (0, -5), (0, -6), (0, -7), (0, -8), (0, -9), (0, -10), (0, -11), (0, -12), (0, -13), (0, -14), (0, -15), (0, -16), (0, -17),$
independence test = gp_dc
tau_min = 1
tau_max = 15
pc_alpha = [0.01]
max_conds_dim = None
max_combinations = 1
```

**Comment by jakobrunge** [comment]
This sample size is way too much for the sklearn implementation of gaussian 
processes in GPDC. Try GPDCtorch.

Am 16. September 2022 22:33:29 schrieb SaharaAli16 ***@***.***>:

**Comment by aashrith** [comment]
...

**Comment by sagarsimha** [comment]
> Hi, I am running the parallel PCMCI+ version on my dataset that comprised 5 time-series variables and had a total of 15000 records. When I run this using ParCorr() test, the code works fine. But when I run it with GPDC(), I don't get any result and the program terminates after exhausting the max execution time specified. I was running this code through slurm jobs and even after 200 hours of execution, I got no results for a 'max_lag' of 15. Nothing gets printed out after this:
> 
> ```
> ##
> ## Step 1: PC1 algorithm with lagged conditions
> ##
> 
> Parameters:
> selected_links = {0: [], 1: [], 2: [], 3: [(0, 0), (0, -1), (0, -2), (0, -3), (0, -4), (0, -5), (0, -6), (0, -7), (0, -8), (0, -9), (0, -10), (0, -11), (0, -12), (0, -13), (0, -14), (0, -15), (0, -16), (0, -17),$
> independence test = gp_dc
> tau_min = 1
> tau_max = 15
> pc_alpha = [0.01]
> max_conds_dim = None
> max_combinations = 1
> ```

Have you tried gpdc_torch(). This implements the Gaussian Process Regression using gpytorch and is faster than sklearn. You can run it both on CPU and GPU over slurm. gpdc_torch() is platform agnostic, meaning it runs on GPU if present else falls back to CPU. We have tested for more than 50k samples on GPU. Look here for more details https://github.com/jakobrunge/tigramite/blob/master/tigramite/independence_tests/gpdc_torch.py
