### ISSUE TITLE
Corresponding endpoints enumeration for the internal causal graph

### ISSUE THREAD

**Issue by adam2392** [jakobrunge/tigramite#245]
Hi @jakobrunge thanks for this great resource!

I'm working with the Causal AI group at Columbia Uni. I am trying to leverage the PCMCI/LPCMCI code to run some experiments but I have a different way of encoding the graph.

When you simulate a VAR process, the VAR connectivity matrix is a `(n_nodes, n_nodes, max_lag + 1)` shaped array, which consist of coefficient values. However, when you encode a causal graph for say using it in a `OracleCITest`, it seems there needs to be some transformation into an array of strings. However, it is not very clear to me what that enumeration looks like.

Is there a clear documentation on what the internal causal graph with string representation of endpoints needs to look like? Especially for ADMGs, where there can be more than 1 endpoint on each node? 

Let me know if there's anything I can clarify. Thanks

**Comment by jakobrunge** [comment]
Hi there, 

the graph notations are either in docstrings or in tutorials:

For time series CPDAGs: https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_pcmciplus.ipynb

For time series PAGs: https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_latent-pcmci.ipynb

For ADMGs in causal effect estimation here: https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_general_causal_effect_analysis.ipynb

Best
Jakob
