### ISSUE TITLE
Financial time series - correct method?

### ISSUE THREAD

**Issue by andrewcz** [jakobrunge/tigramite#246]
Hi, I have started doing experiments with financial time series data. This is return based data  im am wondering if you had a method you would recommend for This style of data.

@jakobrunge

**Comment by sagarsimha** [comment]
Could you formulate the question with an example and state your aims for the analysis?

**Comment by andrewcz** [comment]
Thank you @sagarsimha ill give a bit of run down with screen shots.

So basically i am looking at the "lead lag" between different financial time series. I also want to calculate the time lag between the time series.

![image](https://user-images.githubusercontent.com/2296335/195977812-b836e835-1696-4d00-802f-c3d7f7deacf6.png)

**Comment by andrewcz** [comment]
running the code on the following on the sliding window gives the following output - 

![image](https://user-images.githubusercontent.com/2296335/195977884-fa8e7058-24ac-4916-8b9d-31bf6ca88830.png)

**Comment by andrewcz** [comment]
Im just not sure the best tutorial or strategy to start with.

**Comment by jakobrunge** [comment]
Seems to be too short sample sizes in the windows. I would construct synthetic datasets to get to known to the methods...
