### ISSUE TITLE
Request support for input of type X (n_samples, timesteps, variables) and Y (n_samples, timesteps, variables)

### ISSUE THREAD

**Issue by itsmohitanand** [jakobrunge/tigramite#247]
This is coming more from a machine learning side where most of the models require the input in the form of  X `(n_samples, timesteps, variables)` and Y `(n_samples, timesteps, variables)`. For example, I want to learn the relationship between climate and forest mortality. My samples are generally of the shape (100,12,3). That is 100 years of monthly data for precipitation, temperature and solar radiation. And then, I want to learn the relationship between 1 year of climate and forest mortality on a monthly scale (100,12). In the current setting, I think I will have to create a time series of both variables. Is there any plan to include the inputs where the models can take this X and Y. If something like this already exists, please let me know.

**Comment by jakobrunge** [comment]
But isn't that rather (100*12, 3) if you concatenate the years? Then it's the usual format in Tigramite.

But we now also have a MultiData-option, look here: https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_multiple_datasets.ipynb

**Comment by itsmohitanand** [comment]
The dataset I have is (n_samples, 12, 3), and these are randomized, so creating a long time series would be de-randomizing and concatenating (or going back to the original dataset). I will have a look at the tutorials. I can probably consider each sample as a dataset in itself. 
```
In [4]:
## Option 1: Data is 3D NumPy array

M = num_sample # number of datasets (considering each sample a dataset in itself)
T = 12 # number of time steps
N = 3 # number of variables
```

I think that should work, but I will have a look at it in detail.
