### ISSUE TITLE
Passing in 'selected_links' in `run_lpcmci` to indicate edges that are not present

### ISSUE THREAD

**Issue by adam2392** [jakobrunge/tigramite#248]
Hi,

In the current LPCMCI method, there is a parameter that can be passed in, called `selected_links` for `run_lpcmci`, which are the possible links that are present in the resulting graph (i.e. prior knowledge). However, when I run the algorithm and run some tests, it seems they are not used? I.e. all resulting edges are tested regardless and the same # of CI tests are ran.

Is there a way to restrict which edges are tested in learning the skeleton of the graph?

**Comment by jakobrunge** [comment]
The next master will have this functionality.
