### ISSUE TITLE
Prediction - train and test mask not applied

### ISSUE THREAD

**Issue by lcastri** [jakobrunge/tigramite#249]
Hi,

it seems that the train and test indices defined in Prediction constructor are not then used to build the corresponding masks.
The result of the prediction has exactly the same size of the original dataset.

Thanks,
Luca

**Comment by jakobrunge** [comment]
You are right, there was a bug due to np.copy not really making a deepcopy! It is fixed in the developer and will be pushed to master along with some other new features soon!

**Comment by lcastri** [comment]
Thanks a lot!
