### ISSUE TITLE
var_names dictionary

### ISSUE THREAD

**Issue by debmpaul** [jakobrunge/tigramite#25]
Hi Jakob. Great job with tigramite! I was having an issue with my dataset that was wider than it was tall. I was getting a Key error when I tried to use _print_significant_links, and I saw that self.var_names in __init__ is defined by using the length of the data. Should this be self.data.shape[1] since the rows are the time values, and the columns are the variables?

**Comment by jakobrunge** [comment]
A bug indeed, I will fix that in the next update.
