### ISSUE TITLE
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

### ISSUE THREAD

**Issue by gaonan0902** [jakobrunge/tigramite#250]
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.This problem occurs when installing this package. How to solve it. Thank you.

**Comment by sagarsimha** [comment]
Can you elaborate on what your question is precisely? llvmlite is a dependency for numba and is installed when numba is installed. We use numba to speed up numpy and other python methods. numba is one of the required packages for tigramite and is installed automatically when setup.py is run or pip installed.

**Comment by gaonan0902** [comment]
> Can you elaborate on what your question is precisely? llvmlite is a dependency for numba and is installed when numba is installed. We use numba to speed up numpy and other python methods. numba is one of the required packages for tigramite and is installed automatically when setup.py is run or pip installed.

Thank you for your kindness. I have solved this problem. Thank you for your answer

**Comment by gaonan0902** [comment]
> Can you elaborate on what your question is precisely? llvmlite is a dependency for numba and is installed when numba is installed. We use numba to speed up numpy and other python methods. numba is one of the required packages for tigramite and is installed automatically when setup.py is run or pip installed.

Excuse me， after I installed [tigramite] and ran the code, this error appears. 
UserWarning: [Errno 2] No such file or directory:'E: APP Anaconda lib site packages tigramite-5.1.0.5py3.9. egg gradient independence_ tests\\..\\..\\versions.py'warnings.warn(str(e))。
 I was so confused that I couldn't understand the reason.

**Comment by sagarsimha** [comment]
This is bug from our side. However, this warning will not affect any of the functionalities you intend to use. This will be solved soon in the next update.

**Comment by gaonan0902** [comment]
> This is bug from our side. However, this warning will not affect any of the functionalities you intend to use. This will be solved soon in the next update.

Thank you for your kindness.I really appreciate your help!

**Comment by Amr-Abdelaty-fathalla** [comment]
how can i fix this error , i have same this issue and i can't solve it 'ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall'
