### ISSUE TITLE
KeyError: 'q_matrix'

### ISSUE THREAD

**Issue by gaonan0902** [jakobrunge/tigramite#251]
E:/PROGRAM/Shaylee/coupled_network_causal_of_LAI.py:1512: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if monthly_data != []:
E:/PROGRAM/Shaylee/coupled_network_causal_of_LAI.py:1519: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if yearly_data != []:
Traceback (most recent call last):
  File "E:/PROGRAM/Shaylee/coupled_network_causal_of_LAI.py", line 1877, in <module>
    get_self_links()
  File "E:/PROGRAM/Shaylee/coupled_network_causal_of_LAI.py", line 1520, in get_self_links
    year_data_links = build_link_pcmci_noself(yearly_data.T,
  File "E:/PROGRAM/Shaylee/coupled_network_causal_of_LAI.py", line 1623, in build_link_pcmci_noself
    q_matrix = results_pcmci['q_matrix']
KeyError: 'q_matrix'

Process finished with exit code 1
Good evening, I'm very confused about this question

**Comment by gaonan0902** [comment]
Is it possible that the package is not completely installed？

**Comment by sagarsimha** [comment]
These errors and warnings does not seem to be from within Tigramite but from a program that uses it - coupled_network_causal_of_LAI.py
