### ISSUE TITLE
How to build a DAG in tigramite? 

### ISSUE THREAD

**Issue by georgewanglz2019** [jakobrunge/tigramite#256]
Hello, there!
Firstly, many thanks for your excellent work on causal discovery and share the code and idea.

I am trying to use your package to do my research and I'm confused about how to build my DAG.
## **I read your tutorial:**
graph = np.array([['', '-->', '-->', ''],
                  ['<--', '', '', '-->'],
                  ['<--', '', '', '-->'],
                  ['', '<--', '<--', '']], dtype='<U3')
hidden_variables = [(0,0)]
X = [(1,0)]
Y = [(3,0)]
causal_effects = CausalEffects(graph, graph_type='dag', X=X, Y=Y, S=None, 
                               hidden_variables=hidden_variables, 
                               verbosity=1)

var_names = ['$L$', '$X$', '$Z$', '$Y$']
tp.plot_graph(graph = causal_effects.graph,
        var_names=var_names, 
        figsize = (4, 4),
        ); plt.show()

![image](https://user-images.githubusercontent.com/46119396/202625791-754fa27f-19d9-4f55-8755-c6d677cb3dd1.png)

## **Question:**
From my point of view, the former np.array of 'graph' should be like this:
       L       X       Z       Y
L     ""    -->    -->     ""
X    <--   ""      ""      -->
Z     <--   ""      ""      -->
Y      ""   <--    <--     ""

However, the tp.plot_graph shows it is not the case, which makes me confused.
Could you please teach me how to understand and build the np.array "graph", then use data and SCM to fit?
Many thanks in advance!

**Comment by jakobrunge** [comment]
L is hidden and here a so-called latent projection on a directed acyclic 
mixed graph is shown. That is a graph in with which hidden confounding is 
represented by bidirectional edges.

Am 18. November 2022 06:30:16 schrieb georgewanglz2019 
***@***.***>:

**Comment by georgewanglz2019** [comment]
Thanks for your reply, I try to learn more details from your code.
