### ISSUE TITLE
Can you please change "sklearn" to "scikit-learn"

### ISSUE THREAD

**Issue by lavilesP** [jakobrunge/tigramite#257]
The sklearn package was already deprecated, and  it's quite difficult to install such an old package. The developers of sklearn recommend the users to replace it with scikit-learn. More details can be found https://pypi.org/project/sklearn/

**Comment by sagarsimha** [comment]
Hi. We indeed use scikit-learn package. You could see them mentioned in the Readme and setup.py. If you are referring to how the methods from scikit-learn are called, import sklearn is still the standard way to use methods as one can see in the documentation here, https://scikit-learn.org/stable/getting_started.html
