### ISSUE TITLE
multivariate time series

### ISSUE THREAD

**Issue by AngelaKoloi51** [jakobrunge/tigramite#259]
I am working with longitudinal data 2900 participants and 50 columns- health outcomes that change with time ( we do have 4 time points - year 2003,2004,2005,2007).
I had to convert them from wide to long. As they did here: https://datascienceplus.com/managing-longitudinal-data-conversion-between-the-wide-and-the-long/ so, 2900*4 = 11600 rows and 50 columns. 
So I assume we can say that its multivariate time series analysis 
It will be sth like this: 

subject.id tx time  measure
         1  A    1 27.61686
         2  A    1 41.46307
         3  A    1 33.97125
         4  A    1 31.03210
         5  A    1 28.27894
         6  A    1 37.97978

time take values, 1,2,3,4 for 2003,2004,2005,2007. 
The thing is that each row represents a participant. My question is can this converted data frame work as input for the PCMCI+ or the PCMCI plus? and if yes, what is the time series length? is it 4 wrt 4 different years or is it 11600 wrt the total number of rows?

**Comment by jakobrunge** [comment]
Maybe the Multidata functionality is suitable here: https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_multiple_datasets.ipynb
