### ISSUE TITLE
Testing Independence of Stocks

### ISSUE THREAD

**Issue by manujchandra** [jakobrunge/tigramite#26]
Hi,

A critical assumption of correlation is that the variables are [independent](https://www.investopedia.com/ask/answers/031015/how-can-you-calculate-correlation-using-excel.asp).

I am doing a [correlation analysis](https://github.com/dataBOT3DS/NIFTY50-52-week-Correlation-Analysis/blob/master/NIFTY50%20Correlation%2052%20week/NIFTY50%20Correlation%20Matrix.ipynb) of stock prices.

If we want to test the independence of stock prices (two or more stocks are independent of each other) for correlation analysis which of the following [tests](https://github.com/jakobrunge/tigramite/blob/master/tigramite_tutorial.ipynb) should be employed?

Thanks in advance.

**Comment by jakobrunge** [comment]
To test X indep of Y given Z, it depends on what type of dependency
between X,Y,Z you assume. These topics are
all treated in the publication

Runge, Jakob. 2018. “Causal Network Reconstruction from Time Series:
From Theoretical Assumptions to Practical Estimation.” Chaos: An
Interdisciplinary Journal of Nonlinear Science 28 (7): 075310.

~Jakob
