### ISSUE TITLE
How can we use PCMCI/ PCMCIplus for time-series that come from separately collected time windows?

### ISSUE THREAD

**Issue by f-arab** [jakobrunge/tigramite#262]
Hello,

We want to run PCMCI method on time-series that come from separately collected time windows instead of having one continuously recorded time-series. Does anyone know a quick way of implementing this on current PCMCI or PCMCIplus algorithms?

Thanks

**Comment by jakobrunge** [comment]
It seems you need this one here: https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_multiple_datasets.ipynb

**Comment by f-arab** [comment]
Great. Thanks @jakobrunge
