### ISSUE TITLE
How can we use the bootstrapping functionality in PCMCI/PCMCIplus methods?

### ISSUE THREAD

**Issue by f-arab** [jakobrunge/tigramite#264]
Hi everyone,

We want to do bootstrapping while running PCMCI or PCMCIplus methods on our data. We see that inside the code there is functionality for it but we are not exactly sure how to use that! Can anyone please point us to a quick way of using bootstrap functionality in PCMCI/ PCMCIplus methods?

Thanks

**Comment by jakobrunge** [comment]
This is not yet (fully) implemented.

**Comment by f-arab** [comment]
Okay, Thanks.
