### ISSUE TITLE
Add link to license in readme

### ISSUE THREAD

**Issue by darigovresearch** [jakobrunge/tigramite#265]
Thought it may be helpful/convenient to have a link to the license in the readme

**Comment by darigovresearch** [comment]
Pull request https://github.com/jakobrunge/tigramite/pull/266 wold resolve this if merged

**Comment by jakobrunge** [comment]
It's already there: 

"""
## License

Copyright (C) 2014-2022 Jakob Runge

See license.txt for full text.

GNU General Public License v3.0

TIGRAMITE is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version. TIGRAMITE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
"""
