### ISSUE TITLE
getting error while installing tigramite 4.2.0.1, please help

### ISSUE THREAD

**Issue by Akshayksagar** [jakobrunge/tigramite#267]
WARNING: Ignoring invalid distribution -cipy (c:\users\asus\anaconda3\envs\geo\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\asus\anaconda3\envs\geo\lib\site-packages)
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [14 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-dw0eq7eh\tigramite_c3add7e38b284a67861dbc7ac4a3fc00\setup.py", line 82, in <module>
      EXT_MODULES += define_extension("tigramite.tigramite_cython_code")
    File "C:\Users\ASUS\AppData\Local\Temp\pip-install-dw0eq7eh\tigramite_c3add7e38b284a67861dbc7ac4a3fc00\setup.py", line 48, in define_extension
      return cythonize([pyx_path])
    File "C:\Users\ASUS\anaconda3\envs\geo\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
      module_list, module_metadata = create_extension_list(
    File "C:\Users\ASUS\anaconda3\envs\geo\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "C:\Users\ASUS\anaconda3\envs\geo\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'C:\Users\ASUS\AppData\Local\Temp\pip-install-dw0eq7eh\tigramite_c3add7e38b284a67861dbc7ac4a3fc00\tigramite\tigramite_cython_code.pyx' doesn't match any files
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Ignoring invalid distribution -cipy (c:\users\asus\anaconda3\envs\geo\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\asus\anaconda3\envs\geo\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\asus\anaconda3\envs\geo\lib\site-packages)

**Comment by sagarsimha** [comment]
Are you sure you want to use 4.2.0.1? This is related to an error with cython. We have completely moved away from it. Consider installing the latest version 5.1.0.5

**Comment by Akshayksagar** [comment]
yes, i want to use old version. my codes are written in 4.2.0.1 version and are unable to run on 5.1.0.5.  please help me either installing old version or in runnning my codes in latest version.
thanks

**Comment by sagarsimha** [comment]
There are some major improvements with newer methods. The changed methods are documented. I would really recommend using the latest version. 

If you do need to run on 4.2.0.1, then make sure cython is installed with pip install Cython

**Comment by Akshayksagar** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/46590370/210514732-a44029f4-83c4-40eb-bb0b-a1b3cee9b28b.png)
![Screenshot (122)](https://user-images.githubusercontent.com/46590370/210514741-c4b3fe1c-5101-4dee-821e-d8328af65279.png)
![Screenshot (123)](https://user-images.githubusercontent.com/46590370/210514743-6906fa3a-30f0-4d49-bb96-f72bad5863c9.png)
![Screenshot (124)](https://user-images.githubusercontent.com/46590370/210514744-cb6b7cfc-5d46-41f7-b3c6-7d4b094c2241.png)


i am getting this error, can you help me in solving this ?

**Comment by Akshayksagar** [comment]
I have sent you snaps of error, please check.

**Comment by sagarsimha** [comment]
Can you ensure you are running matplotlib > 3.4?

**Comment by Akshayksagar** [comment]
yes sir, its 3.6, if i am doing show_colorbar = False, then code is running, else its showing error .

**Comment by sagarsimha** [comment]
I have now tested with matplotlib>=3.6. I don't see this error. This error was familiar when running matplotlib<3.4. As another check, can you ensure that the environment with matplotlib 3.6 is indeed the environment used with the jupyter notebook as well.

**Comment by sagarsimha** [comment]
Make sure to use the latest developer version

**Comment by Akshayksagar** [comment]
hello sir,
i am having this error while using tigramite. can you help me in this ?
akshay

**Comment by Akshayksagar** [comment]
Good evening sir,

i am akshay kumar from india and i am using your package tigramite.
i have generated causal graphs using that but i am unable to adjust
colorbar axis. please help me regarding this. Here attached is my code and
result.

thanks and regards

*AKSHAY KUMAR SAGAR*
*Research Scholar IMOD lab*
*Centre for Oceans, Rivers, Atmosphere and Land Sciences*
Indian Institute of Technology Kharagpur, INDIA
https://www.linkedin.com/in/akshay-kumar-sagar-261814152

**Comment by sagarsimha** [comment]
Hi. I don't see your attachment

**Comment by Akshayksagar** [comment]
Please check now

**Comment by sagarsimha** [comment]
I still don't see any attachments. You can attach just by dragging and dropping files.

**Comment by Akshayksagar** [comment]
![Screenshot (148)](https://user-images.githubusercontent.com/46590370/220943843-0daea72e-4ced-41e4-bc8a-ad85cf004b16.png)
![Screenshot (149)](https://user-images.githubusercontent.com/46590370/220943859-be386afe-7f0d-41a0-8b04-461266dc2afa.png)

**Comment by sagarsimha** [comment]
The function causal_plot() does not seem to be from tigramite's plotting.py functions.

**Comment by Akshayksagar** [comment]
Thanks, I'll check it out.
