### ISSUE TITLE
what's the difference between this model and dynamic graph model?

### ISSUE THREAD

**Issue by xiaoniaoyouhuajiang** [jakobrunge/tigramite#27]
I dont know whats the diference，Can you explain briefly?

**Comment by jakobrunge** [comment]
Dear xiaoniaoyouhuaj

PCMCI estimates a time series graphical model which is a graphical model for time series and is described here:
PCMCI: J. Runge et al. (2018): Detecting Causal Associations in Large Nonlinear Time Series Datasets. https://arxiv.org/abs/1702.07007v2
Generally: J. Runge (2018): Causal Network Reconstruction from Time Series: From Theoretical Assumptions to Practical Estimation. Chaos: An Interdisciplinary Journal of Nonlinear Science 28 (7): 075310. https://aip.scitation.org/doi/10.1063/1.5025050

Hope that helps.
~Jakob
