### ISSUE TITLE
how to best remove self loop in pcmci

### ISSUE THREAD

**Issue by dialuser** [jakobrunge/tigramite#270]
Hi

I am interested in quantifying the causal effect from multiple time series variables in X_t on target variable y_t, but without the dependencies on the antecedent states of y. By default, the full links include all lagged variables of y_t itself, i.e., y_{t-tau_min}...y{t-tau_max}. I can use selected_links to instruct run_pcmci to remove the self loop of y. 

For example, if the variable indices are 0, 1, 2, with 2 being the target variable, tau_min = 1 and tau_max = 2, the selected_links may be

{0: [(0, -1), (0, -2), (1, -1), (1, -2), (2, -1), (2, -2)], 1: [(0, -1), (0, -2), (1, -1), (1, -2), (2, -1), (2, -2)], 2: [(0, -1), (0, -2), (1, -1), (1, -2)]}

My question is do I need to remove all other links that also depend on antecedent y? In the above example, those may include (2,-1), (2, -2).

Thanks,
A

**Comment by jakobrunge** [comment]
Check out link_assumptions in the new overview tutorial.
