### ISSUE TITLE
Parallel PCMCI/PCMCI+

### ISSUE THREAD

**Issue by f-arab** [jakobrunge/tigramite#271]
Hi @jakobrunge ,

We tried to use the parallelized version of PCMCIplus which you provided on the Tigramite Github page to speed up the method. However, when are running the code, the process seems to be sequential (while we track the point in the code at which we are supposed to see the scattered jobs) and we also do not see any speed up. We want to make sure if we are missing something about this parallelization and how much speed up we should expect for PCMCI+?

Thanks

**Comment by sagarsimha** [comment]
Can you explain your setup? Are you running on a laptop, or on a cluster? If laptop, are you sure you are not running anything else under the hood. Even having browser open would have an effect. If on cluster, can you give a description of your setup?

**Comment by f-arab** [comment]
Hi @sagarsimha ,

Thanks. The following are the specs of the computer that I run my simulations:

Linux workstation with AMD 3970X 32-Core processor, GeForce RTX 2080 GPU, 512GB of RAM, and 7TB of disk space

I did not see any speed-up while switching to parallel PCMCI+ compared to PCMCI+.  I would like to know where in the main code for parallel PCMCI+, we expect to see the speed-up. I assumed that the parallelization is happening around lines 178-186 in the code for parallel PCMCI+, however, I cannot see this speed-up while trying for data with 91 nodes and around 5000 time samples.

**Comment by jakobrunge** [comment]
We've updated the master and removed the parallel script for now. Parallelization will be revised soon...
