### ISSUE TITLE
pip install leads to missing file error: tigramite/plotting.py:26: UserWarning: [Errno 2] No such file or directory: '/tigramite/../versions.py'

### ISSUE THREAD

**Issue by jjakenichol** [jakobrunge/tigramite#273]
Hello Jakob,

Each time I import the plotting library I get an error like this:

> home/.conda/envs/tigramite_test/lib/python3.9/site-packages/tigramite/plotting.py:26: UserWarning: [Errno 2] No such file or directory: 'home/.conda/envs/tigramite_test/lib/python3.9/site-packages/tigramite/../versions.py'

Reproducing it is easy. I am running in a conda environment and have installed tigramite using pip:
```
conda create -n tigramite_test python=3.9
source activate tigramite_test
conda install numpy scipy numba matplotlib networkx -y
pip install tigramite
```

Then enter a python environment
`python`
`>>> from tigramite import plotting as tp`
OUT:

> home/.conda/envs/tigramite_test/lib/python3.9/site-packages/tigramite/plotting.py:26: UserWarning: [Errno 2] No such file or directory: 'home/.conda/envs/tigramite_test/lib/python3.9/site-packages/tigramite/../versions.py'

I thought maybe running `python setup.py install` would resolve the issue, but that file is missing from the package directory. Next I will see if cloning from github instead of installing with pip will resolve the issue.

This is a small issue, it only clutters the terminal when I run many tests.

Thanks for your help and for tigramite, of course.

**Comment by jjakenichol** [comment]
Looks like cloning from github and running `python setup.py install` resolves the issue in a fresh conda environment. However, after uninstalling and reinstalling from github in an older environment, I still got the error. I'll have to dig into why that is.

**Comment by sagarsimha** [comment]
This has been fixed. The new master update will have this resolved

**Comment by jjakenichol** [comment]
Ah, good to know, thank you. Would you recommend installing from the developer branch? That's worked ok for me in the past but it can be challenging if the documentation is significantly different between master and developer.

**Comment by sagarsimha** [comment]
Developer version is constantly changing and being tested. I would recommend working with the master unless you have a specific feature/fix that the developer has been updated with.

**Comment by jakobrunge** [comment]
The master is now updated, also on pip.
