### ISSUE TITLE
Module 'Tigramite.toymodels' not found when I run basic Tigramite script

### ISSUE THREAD

**Issue by lykkes** [jakobrunge/tigramite#274]
When I try to run the basic script of Tigramite(copied from the original script) in my JupyterNotebook it doesn't find the module 'tigramite.toymodels'. See the error message below. How to read that module correctly?

Lykke

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/k0/sm1j0n_j7bd3wx71yjfr68hr836h64/T/ipykernel_43403/2200673252.py in <module>
     11 import tigramite
     12 from tigramite import data_processing as pp
---> 13 from tigramite.toymodels import structural_causal_processes as toys
     14 
     15 from tigramite import plotting as tp

ModuleNotFoundError: No module named 'tigramite.toymodels'

**Comment by sagarsimha** [comment]
Are you running the notebook in appropriate kernel which has tigramite installed?

**Comment by klwiza** [comment]
I have a similar issue a lykkes. 
The path to toymodels is: /opt/conda3/lib/python3.8/site-packages/tigramite-5.1.0.3-py3.8.egg/tigramite/toymodels/
 Yet I get this error: TypeError: cannot unpack non-iterable NoneType object

**Comment by lykkes** [comment]
I have Python 3.8.5.

**Comment by lykkes** [comment]
This issue was resolved, but a new one appears.
