### ISSUE TITLE
Node labels overlapping in tp.plot_time_series_graph() subplots 

### ISSUE THREAD

**Issue by emfons** [jakobrunge/tigramite#275]
I want to arrange several time_series_graphs in subplots of a single figure, using the fig_ax argument, but when I do, all the node labels from the different graphs overlap in the same location, even when trying to change the label_space_left argument. 

fig,axes = plt.subplots(2, len(graph_list), figsize = (4*len(graph_list),10), gridspec_kw={'width_ratios': [1,0.9,0.75,0.5]})
for i,g in enumerate(graph_list): 
    var_names = var_names_list[i]
    tp.plot_graph(g['graph'], var_names = var_names, fig_ax= (fig,axes[0,i]), label_fontsize=18)
    tp.plot_time_series_graph(g['graph'],
                          var_names = var_names,  
                          fig_ax= (fig,axes[1,i]),
                         label_fontsize=18, 
                             label_space_left = 0 - i*0.25, 
                             label_space_top=0.45)
    axes[0,i].set_title(graph_names[i]) 

![image](https://user-images.githubusercontent.com/77484008/214843772-9cec2082-4299-4984-a63b-7dedb72aba8c.png)

**Comment by sagarsimha** [comment]
Can you reduce the label_fontsize for time series graphs and check? 

Which version of tigramite are you using? The developer is the latest as of today. It also has some changes to plotting function.

To look further, please send a minimal reproducible example in a .ipynb.

**Comment by jakobrunge** [comment]
The master is now updated, also on pip. Does this problem persist?

**Comment by jakobrunge** [comment]
I fixed this in the latest master by removing any dependence on the figure object. Please try!
