### ISSUE TITLE
tigramite.plotting documentation is missing

### ISSUE THREAD

**Issue by Master-Chandler** [jakobrunge/tigramite#276]
The documentation for the tigramite.plotting seems missing. Could you provide this documentation?

**Comment by sagarsimha** [comment]
That is a problem we are looking into. For now, please look into the [tutorials ](https://github.com/jakobrunge/tigramite/tree/developer/tutorials)folder and the [plotting.py](https://github.com/jakobrunge/tigramite/blob/developer/tigramite/plotting.py) doctrings to get a description of methods and individual parameters.

**Comment by jakobrunge** [comment]
The master is now updated, also on pip.
