### ISSUE TITLE
plot specific links 

### ISSUE THREAD

**Issue by Master-Chandler** [jakobrunge/tigramite#277]
If I obtain a many causal links, I want to plot some specific links and mask other links, by keeping all the nodes. How should I do?

**Comment by sagarsimha** [comment]
Hi. 
Following this tutorial, https://github.com/jakobrunge/tigramite/blob/developer/tutorials/causal_discovery/tigramite_tutorial_basics.ipynb

have a look at the "graph" parameter in plot_graph() - https://github.com/jakobrunge/tigramite/blob/c877f0b578c357b1c26f666764be07676193d4dc/tigramite/plotting.py#L2367

You can manipulate this parameter to your requirement.
