### ISSUE TITLE
Having trouble interpreting the results

### ISSUE THREAD

**Issue by klwiza** [jakobrunge/tigramite#279]
To learn how to interpret my results, I ran PCMCI_plus for 39 years of Oct-Dec Rains in East Africa (EAR), El Nino, NAO, and Indian Ocean Dipole index (DMI). It is well established that the short rains (as they called) in East Africa are strongly influenced by El Nino, followed by DMI and to a lesser extent by NAO. I get the image below for my causal links

![image](https://user-images.githubusercontent.com/124171366/218876489-41fdea10-e866-407e-9475-6065386587d0.png)

Nino affecting DMI is well known
Nino controlling EAR is  cceptable
**but**
EAR controlling Nino does not make sense
EAR  impacting DMI  is not likely
NAO affecting DMI could happen but not likely

How do I get rid of or minimize the false results.

**Comment by jakobrunge** [comment]
This is not a bug, please post in Discussions.
