### ISSUE TITLE
TypeError: print_significant_links() got an unexpected keyword argument 'q_matrix'

### ISSUE THREAD

**Issue by lykkes** [jakobrunge/tigramite#281]
When I run the basic script Tigramite on Jupyter 6.5.2 with ipykernel 3 I get this error. I have reinstalled anaconda, pandas and tried with and without pip install Tigramite and matplotlib, but this error doesn't go away. Until 2 weeks ago I had no problems running the same code for more than a year.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/k0/sm1j0n_j7bd3wx71yjfr68hr836h64/T/ipykernel_9231/52582853.py in <module>
      1 q_matrix = pcmci.get_corrected_pvalues(p_matrix=results['p_matrix'], fdr_method='fdr_bh')
----> 2 pcmci.print_significant_links(
      3         p_matrix = results['p_matrix'],
      4         q_matrix = q_matrix,
      5         val_matrix = results['val_matrix'],

TypeError: print_significant_links() got an unexpected keyword argument 'q_matrix'

**Comment by sagarsimha** [comment]
Hi. The q_matrix is the p_matrix once corrected for false discovery rate. You would have to pass the q_matrix to the parameter "p_matrix" as below. "q_matrix" as an explicit parameter does not exist.

pcmci.print_significant_links(
        p_matrix = q_matrix,
        val_matrix = results['val_matrix'])

**Comment by lykkes** [comment]
Thank you for replying, but with this change I run into an error in the next set of code:
link_matrix = pcmci.return_significant_links(pq_matrix=q_matrix,
                        val_matrix=results['val_matrix'], alpha_level=0.05)['link_matrix']

return_significant_links() is DEPRECATED: now run_pcmci(),  run_mci() and all variants directly return the graph based on thresholding the p_matrix at alpha_level. The graph can also be updated based on a (potentially further adjusted) p_matrix using get_graph_from_pmatrix(). A dictionary of parents can be obtained with return_parents_dict().
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/k0/sm1j0n_j7bd3wx71yjfr68hr836h64/T/ipykernel_9231/1717797097.py in <module>
----> 1 link_matrix = pcmci.return_significant_links(pq_matrix=q_matrix,
      2                         val_matrix=results['val_matrix'], alpha_level=0.05)['link_matrix']

TypeError: 'NoneType' object is not subscriptable

**Comment by sagarsimha** [comment]
As the warning suggests, "link_matrix" is deprecated. Use the "graph" parameter instead. Refer to this tutorial for further guide - https://github.com/jakobrunge/tigramite/tree/developer/tutorials
Make sure you are using the latest version. Please use the developer as of now. The master will be the latest soon.

**Comment by lykkes** [comment]
Ok, thank you for guidance.


21 feb. 2023 kl. 15:34 skrev Sagar Nagaraj Simha ***@***.***>:

﻿

As the warning suggests, "link_matrix" is deprecated. Use the "graph" parameter instead. Refer to this tutorial for further guide - https://github.com/jakobrunge/tigramite/tree/developer/tutorials
Make sure you are using the latest version. Please use the developer as of now. The master will be the latest soon.
