### ISSUE TITLE
Make install requires dependencies softer

### ISSUE THREAD

**Issue by adam2392** [jakobrunge/tigramite#284]
In the current requirements, is it possible to make the dependencies "soft"? I.e. any version greater than or equal to what is there right now?

https://github.com/jakobrunge/tigramite/blob/3387693e7562c076c2fa47271f18d163f57ceb1b/setup.py#L36

Otherwise, sticking a hard dependency of e.g. exactly `scipy==1.8.0` makes it hard to install tigramite with other packages that might have say... `scipy==^1.8.1`

**Comment by sagarsimha** [comment]
Yes, this will be addressed in the master update next week. Thanks for the feedback.

The issue was  - numba had a specific version compatibility with numpy (and scipy with numpy). Hence, we had decided to freeze the dependencies. This has been addressed by numba and we will now relax this on our end as well.

**Comment by sagarsimha** [comment]
Correction - The dependency issue persists. numba is always released for compatibility with a lower version of numpy as compared to the latest release. As of today, numba 0.56.4 is compatible with numpy <1.24,>=1.18 . So, yes, we can have a soft dependency but yet within the range that numba is compatible with numpy.

**Comment by adam2392** [comment]
Ah I see. Okay yea the soft dependency would be great! Lmk if you need a PR, or if it's already done.

**Comment by jakobrunge** [comment]
The master is now updated, also on pip. Does this problem persist?

**Comment by adam2392** [comment]
Yes this works now! 

FYI @jakobrunge EB said he would get back to you. Excited to start chatting soon
