### ISSUE TITLE
 External test 

### ISSUE THREAD

**Issue by MatteoSerafino** [jakobrunge/tigramite#285]
I'm trying to pass an external independence test,  but I am having some issued in doing so. 
Can you help me with this?

**Comment by jakobrunge** [comment]
What is the problem?

**Comment by MatteoSerafino** [comment]
Hello @jakobrunge, 
I'm trying to implement the RCot test.

I installed R on my conda and the library: https://github.com/ericstrobl/RCIT.
I check the RCot tet is working. 

Now I would like to use this as an independent test, but honestly not clear. 

I am using h following: 

`import pandas as pd
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
import rpy2.robjects as robjects

class RCITTest():
    
    def __init__(self, **kwargs):
        self._measure = importr('RCIT')
        
    def _p_value(self,x,y,x)    
        p_value(self, x, y, z):
        # convert pandas dataframes to R dataframes
        rx = robjects.DataFrame(x.values)
        ry = robjects.DataFrame(y.values)
        rz = robjects.DataFrame(z.values)
        
        # run RCIT test
        result = self._measure.RCoT(rx, ry, rz)
        
        # extract p-value from result
        p_val = result[0][0]
        
        return p_val`
but I have no clear how to proceed.

**Comment by jakobrunge** [comment]
I had similar problems with the link to R and cannot further help here, unfortunately.
