### ISSUE TITLE
Stationarity and _check_stability function

### ISSUE THREAD

**Issue by sujoyrc** [jakobrunge/tigramite#287]
Would like to check for any reference for the _check_stability function in structural_causal_process module. Trying to understand what is the underlying basis for the same.

Also is this check used on the estimated graph generated by the PCMCI algorithm.

**Comment by jakobrunge** [comment]
This is standard linear stability theory of VAR-processes: see, eg, https://statmath.wu.ac.at/~hauser/LVs/FinEtricsQF/FEtrics_Chp2.pdf

Stability is a property of an time-dependent model/process, not of a graph, so it is not relevant for PCMCI.
