### ISSUE TITLE
get_predictors() : selected_links is DEPRECATED

### ISSUE THREAD

**Issue by ef93** [jakobrunge/tigramite#320]
https://github.com/jakobrunge/tigramite/blob/f38ca3f5cd6eb153d5119c5467c8f1436aa0635c/tigramite/models.py#L1666

It seems that the selected_links parameter in get_predictors function in models file is DEPRECATED. This function aims to estimate predictors using PC1 algorithm and wraps around PCMCI.run_pc_stable, so selected_links should be changed to link_assumptions.

**Comment by jakobrunge** [comment]
That was a bug, thanks for spotting it. Fixed now in Master, please check!
