### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes 

### ISSUE THREAD

**Issue by shaypal5** [jakobrunge/tigramite#33]
Hello there. :)

Thanks again for this great package (and the research it is based on), and all the hard work.

I'm getting the following error (see stack trace below) thrown by the `get_lagged_dependencies` method of the `PCMCI` class. I'm calling it with `tau_max=144`. Also, the `PCMCI` object for which it is called was initialized with following arguments:

- `dataframe` - A tigramite dataframe of shape (8640, 13); so 13 variables, each a time series of 8640 time steps. All values or non-negative integers.
- `cond_ind_test` - An instance of the `CMIsymb` class (initialized with all `None` arguments).
- `selected_variables` - The list `[5, 6, ..., 12]` (so it is not required to find causal parents for the first five variables).
- `verbosity` - A value of 10.

As you can see below, the method runs through thousands of links before throwing this error:

```bash
        with conds_y = [ ]
        with conds_x = [ ]
        val = 0.006

        link (i4 -138) --> i1 (1443/1884):
        with conds_y = [ ]
        with conds_x = [ ]
        val = 0.005

        link (i4 -139) --> i1 (1444/1884):
        with conds_y = [ ]
        with conds_x = [ ]
Traceback (most recent call last):
  File "/usr/local/bin/poseidon", line 11, in <module>
    load_entry_point('poseidon', 'console_scripts', 'poseidon')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/poseidon-app/poseidon_package/scripts/poseidon_cli.py", line 51, in infer_causality
    timestep_len_in_seconds=tsteplen,
  File "/poseidon-app/poseidon_package/poseidon/core.py", line 124, in run_poseidon
    timestep_in_sec=timestep_len_in_seconds,
  File "/poseidon-app/poseidon_package/poseidon/infer_causality.py", line 220, in infer_causality
    epsilon=None,
  File "/poseidon-app/poseidon_package/poseidon/util.py", line 23, in find_max_lag
    correlations = pcmci.get_lagged_dependencies(tau_max=timesteps_in_a_day)
  File "/poseidon-app/tigramite/tigramite/pcmci.py", line 1171, in get_lagged_dependencies
    val = self.cond_ind_test.get_measure(X, Y, Z=Z, tau_max=tau_max)
  File "/poseidon-app/tigramite/tigramite/independence_tests.py", line 493, in get_measure
    return self._get_dependence_measure_recycle(X, Y, Z, xyz, array)
  File "/poseidon-app/tigramite/tigramite/independence_tests.py", line 373, in _get_dependence_measure_recycle
    return self.get_dependence_measure(array, xyz)
  File "/poseidon-app/tigramite/tigramite/independence_tests.py", line 2345, in get_dependence_measure
    hist = self._bincount_hist(array, weights=None)
  File "/poseidon-app/tigramite/tigramite/independence_tests.py", line 2318, in _bincount_hist
    flathist[:len(result)] += result
ValueError: operands could not be broadcast together with shapes (144,) (145,) (144,)
```

Any help at all with finding the source of this error will be greatly appreciated.

**Comment by jakobrunge** [comment]
Dear Shay

could you attach a dataset to reproduce this? I imagine it has to do with the symbols you have in the array.

Thanks
Jakob

**Comment by shaypal5** [comment]
Hey Jakob,

I've added here a Python script + a CSV file to reproduce the bug.
Please take a look and let me know if it works (meaning causes the error in question).

Thank you very very much!
Shay

[example_problem_for_jakob.zip](https://github.com/jakobrunge/tigramite/files/3207186/example_problem_for_jakob.zip)

**Comment by shaypal5** [comment]
Also, can my (non-)choice for `selected_links` be related to this error? See issue #35.

**Comment by jakobrunge** [comment]
Thanks for all this nice testing!
I looked at the example and found that your first column in data is the time index. Hence, the maximum value of data is 8639. This first column is not in selected_variables in your code, but that's still dangerous.

But I found that n_symbs is set wrongly in the code and fixed that in the developer branch. Thanks! Your script should work now, except that pc_alpha=0.1 is not available for CMIsymb.

**Comment by shaypal5** [comment]
Hey Jakob! 

Thanks for the help with my various issues. :)

About the first column in my data - you're right, I had a silly bug in the way I use `pandas.read_csv()`; it should be used like this:
```python
df = pd.read_csv('final_input_example.csv', index_col=0)
```


I fixed it in my code since then but have forgotten to update the example I've provided here.

That's awesome, you finding that bug! Thanks! Glad to have helped this somehow, even though it was unintentionally. 

One final question - what do you mean by `pc_alpha=0.1` not being available for `CMIsymb`?

**Comment by jakobrunge** [comment]
I meant pc_alpha=None not being available for CMIsymb...

**Comment by shaypal5** [comment]
Oh. Yeah, I found that out. I don't remember, though, if the exception thrown made this apparent or if I had to dig through the code. Thanks!
