### ISSUE TITLE
I found there was ever a tigramite with gui but I can't find it 

### ISSUE THREAD

**Issue by GELIELEO** [jakobrunge/tigramite#34]
I found there was ever a tigramite with gui but I can't find it, can you share with me. I want to try the version of GUI.

**Comment by jakobrunge** [comment]
There was a GUI a long time ago. I prefer jupyter notebooks since they are much more flexible regarding building pipelines and preprocessing etc.

**Comment by GELIELEO** [comment]
I think jupyter is flexible as well but it is not Intuitive enough for me.  So  can you share it?Thankyou a lot.

**Comment by jakobrunge** [comment]
The GUI is for an old and different version (not the same method) and not supported, unfortunately.  I hope the jupyter tutorials show that it's pretty easy...

**Comment by GELIELEO** [comment]
it is fine, thank you:)
