### ISSUE TITLE
consider specific link and discard the remaining by comparing the magnitude of the val_matrix with a certain threshold

### ISSUE THREAD

**Issue by asha24choudhary** [jakobrunge/tigramite#348]
Hi. I was going through the previous issues that were posted here and I found [this one](https://github.com/jakobrunge/tigramite/issues/277). This issue is quite similar to the thing I am aiming for. I want to do something similar, i.e., plot the links using the 'plot_time_series_graph' function based on the magnitude of the val_matrix after performing lpcmic. If the magnitude of the val_matrix is above a certain threshold value, then, that link should be plotted and vice-versa. However, the link to the tutorial that you shared before is not working. I also looked myself, unfortunately there is no basic tutorial on causal discovery. Could you please help me?

**Comment by jakobrunge** [comment]
There now is a whole folder for tutorials in causal discovery, including an overview tutorial: https://github.com/jakobrunge/tigramite/tree/master/tutorials/causal_discovery

You can always adapt the graph to only plot specific links, eg, based on val_matrix, just use standard numpy:

```
my_graph = np.copy(graph)

my_graph[np.abs(val_matrix) < threshold] = ""
```

...or similar.

**Comment by asha24choudhary** [comment]
oK thank you so much:)
