### ISSUE TITLE
ylimits for plotting should not be rounded

### ISSUE THREAD

**Issue by rebeccaherman1** [jakobrunge/tigramite#355]
@jakobrunge 

The default values for `minimum` and `maximum` in [`setup_args`](https://github.com/jakobrunge/tigramite/blob/9b6b9316af2fe49dc21fd49ffd32e17fc0d19e4a/tigramite/plotting.py#L453C4-L456C28) are `-1` and `1`. When using `plot_lagfuncs` to plot correlations, these are the most extreme one could possibly desire, but if the absolute value of the correlations are small, one might desire to zoom in farther. For some reason, in the most updated version of the code, the type of `minimum` and `maximum` is requested to be an `int`, which is not logical because it would make it impossible to zoom in. I think the actual problem is coming from use of [`_myround`](https://github.com/jakobrunge/tigramite/blob/9b6b9316af2fe49dc21fd49ffd32e17fc0d19e4a/tigramite/plotting.py#L51) . Can this be removed from [the code for `setup_args`](https://github.com/jakobrunge/tigramite/blob/9b6b9316af2fe49dc21fd49ffd32e17fc0d19e4a/tigramite/plotting.py#L574C1-L596C22)? Any choice of coarseness will create a minimum zoom, and I don't think there should be one. Perhaps the logic is that small correlations are unlikely to be significant, but this should depend on the amount of data.

**Comment by jakobrunge** [comment]
I don't see where they are required to be int, I just see this in the docstring, which I will fix. Python doesn't require typed variables usually...

**Comment by rebeccaherman1** [comment]
It isn't required in the code to be an int, but it is rounded to the nearest half-int or something using `_myround`. In my original post I've linked to the code for _myround and where _myround is invoked, and I ask that it be removed. Here is the link again: https://github.com/jakobrunge/tigramite/blob/9b6b9316af2fe49dc21fd49ffd32e17fc0d19e4a/tigramite/plotting.py#L574C1-L596C22

**Comment by jakobrunge** [comment]
If you want to create a fix and pull request, please go ahead.

**Comment by jakobrunge** [comment]
Thanks for the catch, maximum and minimum can be floats, fixed in the docstring now, and you can adjust the tick_marks by the "y_base" argument.
