### ISSUE TITLE
Is it possible to use CMIknn as TDMI ?

### ISSUE THREAD

**Issue by Uiuran** [jakobrunge/tigramite#36]
Hi Jakob, beautiful work you got.

I cant state cleary from the paper, since the definitions of CMI and MI are different, if its possible to use your CMIknn algorithm as a TimeDelayMI estimator. There is Matlab implementations for this, but i need python. Some guys relay on histogram but i found binning noisy. 

Iam aiming to use the measure as a evidence of low dimensionality, so it's MI and not CMI i need. Further development of my work in time series may use the CMIknn too. 

plus question: this package is on pip/conda ? 

Thank you in advance.

**Comment by jakobrunge** [comment]
Sure, that is possible just initiate the pcmci class with the CMIknn conditional independence test and then run pcmci.get_lagged_dependencies(tau_max=20). this does not exclude the effect of autocorrelation or common drivers of course ...

For now it is only on GitHub.
