### ISSUE TITLE
Do I need to manually select links for run_pcmci? Warning: Link specified in selected links that is outside the scope of the selected variables

### ISSUE THREAD

**Issue by shaypal5** [jakobrunge/tigramite#37]
Hey there,

So somewhat related to issue #35 , I'm guessing, but I think warranting it's own issue (because my intuition regarding the right answer is the opposite of the case there):

I'm initializing a `PCMCI` object with `selected_variables` set to some subset of the variables found in the used dataframe (say we have variables 0 through 6, and I set `selected_variables=[0, 1, 2]`).

When calling `run_pcmci(tau_max=8, pc_alpha=0.1)` (just random numbers here), I get:
```
Warning: Link specified in selected links that is outside the scope of the selected variables
```

Now, indeed the documentation for `selected_links` states:
```selected_links (dict or None) – Dictionary of form {0:all_parents (3, -2), …], 1:[], …} specifying whether only selected links should be tested. If None is passed, all links are tested.```

But on the other hand, the documentation for `selected_variables` says:
```selected_variables (list of integers, optional (default: range(N))) – Specify to estimate parents only for selected variables. If None is passed, parents are estimated for all variables.```

...which implies links like 1 -> 4 (meaning, links corresponding to causal parents of unselected variables, like variable 4) will not be checked.

So which is right? The documentation or the warning? The documentation suggests that setting `selected_variables` is enough, and that non-relevant links will be skipped, but the warning suggests that I need to manually match the scope of selected links to that of selected variables.

I would greatly appreciate your help (and I wish to thank you again for all your help so far),
Shay

**Comment by shaypal5** [comment]
Hmm. So while digging through `tigramite`'s code (in attempt to debug issue #38), I encountered this piece of code in `run_pc_stable()`. 

I think it means (if I'm reading it correctly) that at least the PC part does behave like the optimistic option, and that `selected_links` is built so it is made of all causal links in which a variable in `selected_variables` is the son (caused), but for every possible variable and lag as the parent (causing).

```python
if selected_links is None:
    selected_links = {}
    for j in range(self.N):
        if j in self.selected_variables:
            selected_links[j] = [(var, -lag)
                for var in range(self.N)
                for lag in range(tau_min, tau_max + 1)
            ]
        else:
            selected_links[j] = []
```

Am I making sense?

**Comment by jakobrunge** [comment]
Yes.

**Comment by shaypal5** [comment]
Cool. So maybe this means that the warning should be removed, no?
