### ISSUE TITLE
Relationship Polarity for Discrete Variables

### ISSUE THREAD

**Issue by AdeLouis** [jakobrunge/tigramite#379]
Hi, thanks for creating this package. I have a question about the polarity (i.e., positive or negative) of inferred causal relationships from discrete variables. I noticed that when using the Squared test (recommended for this data type), the output tells me about the causal relationships found, but does not tell me whether the cause is positive or negative. Typically, I check the "val_matrix", but it is all positive numbers even when I expect a negative causal relationship. 

Is this a limitation of the GSquared test since it uses mutual information?

**Comment by jakobrunge** [comment]
Yes.
