### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by Martin-Molinero** [jakobrunge/tigramite#400]
- `tigramite` 5.2.5.1 (latest) depends on numba 0.56.4 which doesn't work in py 3.11, ref https://pypi.org/project/numba/0.56.4/

Could python 3.11 support be added?

**Comment by micycle1** [comment]
Any ETA on this? I see one of PRs was last updated Mar 28.

**Comment by jakobrunge** [comment]
Works now!
