### ISSUE TITLE
tigramite issue

### ISSUE THREAD

**Issue by Akshayksagar** [jakobrunge/tigramite#401]
while running the tigramite, following issue occurs. Also numba is creating the problem. I have python 3.9 and all the dependecies are fulfilled
![Screenshot (236)](https://github.com/jakobrunge/tigramite/assets/46590370/d01f46a5-28a2-4f43-96e8-7078bb93c24c)

**Comment by liziyue17** [comment]
Same with Python 3.8
![image](https://github.com/jakobrunge/tigramite/assets/48009017/ad339e1d-bcfa-41d2-8baf-98dce37c603b)

**Comment by tudor-suciu** [comment]
Hi both @Akshayksagar @liziyue17,

I had the same problem when I tried to install tigramite, both on python3.10 and python3.7. This is what I managed to do to fix the installation, maybe it helps you too:

Initially, I created a conda environment and installed **tigramite** from source (cloned the repo) using `python3 setup.py install`. This created my the same problem with importing the **numba** as yours:

 - `SystemError: initialization of _internal failed without raising an exception`.

What I have done to fix this:

- checked **numba**'s documentation, where it says:

<img width="918" alt="Screenshot 2024-03-27 at 15 39 13" src="https://github.com/jakobrunge/tigramite/assets/39918190/1e0c76bf-98a8-4ef5-9deb-7f6f811158cc">

- I installed said dependencies from there; in my case, for MAC OSX (M1), I installed: `conda install clang_osx-arm64` and `conda install clangxx_osx-arm64`
- I reinstalled **numba**, specifying the version: `conda install numba==0.56.4`
- then, the importing of **tigramite** and **numba** started to work, but I was missing to more dependencies: **networkx** and **dcor**. I installed those with `conda install networkx` and `pip install dcor`
- everything worked. 

Hope this works for you as well!

@jakobrunge, many thanks for the package!
