### ISSUE TITLE
Issue with plotting graph: tp.plot_graph() in Tigramite 5.2.5.0 

### ISSUE THREAD

**Issue by muszyna25** [jakobrunge/tigramite#406]
Hi,

I'm trying to use `tigramite.plotting.plot_graph()` function to plot a network consisting of two nodes and one link, however; the function makes the nodes elongated (see the attached screenshot). This doesn't happen when I use the function to plot a network with three nodes.

I've tried using the default function configuration and different values for these two arguments `node_size` and `node_aspect`, but neither of them works.

Would you be able to advise how I can fix this so that the nodes aren't elongated when the network only has two nodes?

Thanks!

![tigramite_plot_issue](https://github.com/jakobrunge/tigramite/assets/6480374/79cbd973-058d-4dc1-b04a-e7ba8c8be3c5)

**Comment by jakobrunge** [comment]
I know, I have found it hard to solve that nicely. Patches welcome!
