### ISSUE TITLE
Scaling CMI estimation

### ISSUE THREAD

**Issue by kenneth-lee-ch** [jakobrunge/tigramite#407]
I was using the method here: https://github.com/jakobrunge/tigramite/blob/master/tigramite/independence_tests/cmisymb.py.
There was an error thrown when the conditioning set size was larger than 32 from the following line

```
    _, hist = crosstab(*(np.asarray(np.split(array, len(xyz), axis=0)).reshape((-1, T))), levels=levels,
                        sparse=False)
```
The error was coming from scipy :
```
    count = np.zeros(shape, dtype=int)
ValueError: maximum supported dimension for an ndarray is 32, found 34
```

Is this an known issue? Any suggestions on resolving this issue?

**Comment by jakobrunge** [comment]
That's a memory error issue due to too many value dimensions. You need fewer categories in the categorical variables or decrease the number of variables.
