### ISSUE TITLE
Maybe bug with return_significant_parents() 

### ISSUE THREAD

**Issue by semvijverberg** [jakobrunge/tigramite#41]
Tigramite 4:

I got an inconsistency between  pcmci.print_significant_links() and pcmci.return_significant_parents()

output pcmci.print_significant_links()

## Significant links at alpha = 0.05:

Variable t2mmax_E-US has 10 link(s):
        ([1, '0_1_sst', 0] 0): pval = 0.00001 | qval = 0.00001 | val = 0.287
        ([18, '1_1_sst', 0] 0): pval = 0.00001 | qval = 0.00001 | val = 0.287
        ([7, '0_7_sst', 0] 0): pval = 0.00001 | qval = 0.00001 | val = 0.286
        ([19, '1_4_sst', 0] -1): pval = 0.00002 | qval = 0.01361 | val = -0.278
        ([6, '0_6_sst', 0] 0): pval = 0.00030 | qval = 0.00030 | val = 0.234
        ([4, '0_4_sst', 0] 0): pval = 0.00062 | qval = 0.00062 | val = -0.222
        ([5, '0_5_sst', 0] 0): pval = 0.00155 | qval = 0.00155 | val = 0.205
        ([21, '1_6_sst', 0] 0): pval = 0.00172 | qval = 0.00172 | val = 0.203
        ([19, '1_4_sst', 0] 0): pval = 0.00192 | qval = 0.00192 | val = -0.201
        ([25, '1_5_sst', 0] 0): pval = 0.00497 | qval = 0.00497 | val = 0.183

output pcmci.return_significant_parents()
![image](https://user-images.githubusercontent.com/35559713/59785160-6529e300-92c4-11e9-8add-5dfa99a828ab.png)

return_significant_parents() seems to only give back link [19, '1_4_sst', 0] -1). According to the qvalues printed, all of them are lower then 0.05.. 

When qvalue is printed, it says : print(q_matrix[p[0], j, abs(p[1])])), p being a list of sorted_links:
![image](https://user-images.githubusercontent.com/35559713/59800764-bac3b700-92e7-11e9-9118-9a79bf3476bb.png)
 
when qvalue is 'returned', it says: np.argwhere(pq_matrix[:, j, 1:] <= alpha_level)

where is this '1:' based on in np.argwhere(pq_matrix[:, j, 1:] <= alpha_level)? Is it correct?

Thanks in advance!
Sem

**Comment by semvijverberg** [comment]
I believe the '1:' results in the fact that only parents of tau larger then -1 are returned.

The following code gave also physically more meaningfull results:

    def return_sign_parents(pc_class, pq_matrix, val_matrix,
                                alpha_level=0.05):
          # Initialize the return value
        all_parents = dict()
        for j in pc_class.selected_variables:
            # Get the good links
            good_links = np.argwhere(pq_matrix[:, j, :] <= alpha_level)
            # Build a dictionary from these links to their values
            links = {(i, -tau): np.abs(val_matrix[i, j, abs(tau) ])
                     for i, tau in good_links}
            # Sort by value
            all_parents[j] = sorted(links, key=links.get, reverse=True)
        # Return the significant parents
        return {'parents': all_parents,
                'link_matrix': pq_matrix <= alpha_level}

    return_sign_parents(pcmci, pq_matrix = q_matrix,
                                   val_matrix = results['val_matrix'],
                                   alpha_level = alpha_level)['parents']

**Comment by jakobrunge** [comment]
Parents in PCMCI can only come from lags <= -1. Hence, the '1:' in return_significant_parents(). But the same function also returns 'link_matrix', which is just p_matrix <= alpha_level (or q_matrix). Hence, this matrix also contains links at lag 0. It's a link, not a parent. print_significant_links is also based on all links at any lag... But I will think about a parameter to also return lag 0 links in the all_parents dictionary...
