### ISSUE TITLE
print_significant_links returns extra links for orientable contemporaneous links when running PCMCI+

### ISSUE THREAD

**Issue by kslote1** [jakobrunge/tigramite#423]
When running PCMC+, the logs didn't match the output or `print_sginificant_links`.

PCMC+ found orientable contemporaneous links. When I passed the results to `print_sginificant_links` the links going the opposite direction of the orientation were also found to be significant. 

Maybe this is a feature and not a bug.

**Comment by jakobrunge** [comment]
Significance in the p-value matrix only concerns adjacencies, not the orientation of the link. That is why the matrix is symmetrized.

**Comment by kslote1** [comment]
Ok! Thanks for the clarity. I look forward to citing your work!
