### ISSUE TITLE
connection direction problem “x-x”

### ISSUE THREAD

**Issue by xkg10** [jakobrunge/tigramite#424]
Hi, I am encountering an issue where the connection direction is labeled as 'x-x' in my PCMCI results. According to the tutorials I've followed, the expected directions should only be '-->' or '<--'. Does anyone know why the 'x-x' direction appears in the results?

![屏幕截图 2024-09-02 191603](https://github.com/user-attachments/assets/9f7babe6-eb68-463f-94b5-dc3b8f926778)

**Comment by jakobrunge** [comment]
These x indicate orientation conflicts, see the PCMCI+ tutorial: https://github.com/jakobrunge/tigramite/blob/master/tutorials/causal_discovery/tigramite_tutorial_pcmciplus.ipynb

**Comment by xkg10** [comment]
> These x indicate orientation conflicts, see the PCMCI+ tutorial: https://github.com/jakobrunge/tigramite/blob/master/tutorials/causal_discovery/tigramite_tutorial_pcmciplus.ipynb

Thank you for your response; I have read the tutorial you provided, but I am still a bit unclear. If I encounter 'x-x' in my results, does this mean that my results are not accurate?
