### ISSUE TITLE
Could not import packages for CMIknn and GPDC estimation

### ISSUE THREAD

**Issue by ranbix666** [jakobrunge/tigramite#43]
I am truly sorry that I am asking dummy questions. But I met a problem importing package,

> Could not import packages for CMIknn and GPDC estimation
> Could not import r-package RCIT

ImportError                               Traceback (most recent call last)
<ipython-input-4-38684b8104d1> in <module>
----> 1 from tigramite import tigramite_cython_code

ImportError: cannot import name 'tigramite_cython_code' from 'tigramite' (C:\Users\ranbix\Documents\summer_19\summer_19\tigramite-master\tigramite-master\tigramite\__init__.py)

Could you please give me any help? Thanks!

**Comment by Yassir-Alharbi** [comment]
same here

**Comment by jakobrunge** [comment]
What steps did you do?

Note that you may need to install cython... for CMIknn and rpy2 for RCOT. You'll also need to run the script to install r-packages. See the docs.

If you run "!pip install git+https://github.com/jakobrunge/tigramite.git" in Google's Colaboratory jupyter notebook, everything works...

**Comment by ranbix666** [comment]
Hi Jakob, thank you for quick reply!
I followed your docs. (I installed all required packages)
1. python setup.py install
2. run jupyter notebook example
3. Could not import packages for CMIknn and GPDC estimation
4. `from tigramite import tigramite_cython_code`
5. 

> ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-38684b8104d1> in <module>
----> 1 from tigramite import tigramite_cython_code

ImportError: cannot import name 'tigramite_cython_code' from 'tigramite' (C:\Users\ranbix\Documents\summer_19\summer_19\tigramite-master\tigramite-master\tigramite\__init__.py)
__________________________________________________________________________________________

I tried Colab, it solves CMIknn issue. But it showed that "could not import RCIT".
so I ran thhe following code in Colab and failed.
`import rpy2
import rpy2.robjects as robjects
robjects.r('''
           
.libPaths()
''')

from rpy2.robjects.packages import importr
utils = importr("utils") 

packnames = ('devtools', 'MASS')
from rpy2.robjects.vectors import StrVector
utils.install_packages(StrVector(packnames)) 

robjects.r('''
        # create a function `f`
library(devtools)

install_github("ericstrobl/RCIT")

library(RCIT)

RCIT(rnorm(1000),rnorm(1000),rnorm(1000))
        ''') `


Again, I am truly sorry for asking dummy question. I just want to make it work. Thanks!

**Comment by ranbix666** [comment]
> What steps did you do?
> 
> Note that you may need to install cython... for CMIknn and rpy2 for RCOT. You'll also need to run the script to install r-packages. See the docs.
> 
> If you run "!pip install git+https://github.com/jakobrunge/tigramite.git" in Google's Colaboratory jupyter notebook, everything works...

I fixed the issue on Colab. Thank you!
