### ISSUE TITLE
Parallelization using Dask

### ISSUE THREAD

**Issue by matthieubulte** [jakobrunge/tigramite#45]
Hi,

I have been using Tigramite over the last week and have been trying out different ways to parallelize it.

There are two levels of parallelization that where interesting for me:
1. Parallelizing at the node level, the way you are doing it in your MPI-based script
2. Parallelizing the knn-based independence test -- this is new.

An obvious 3rd level (not relevant for me) is to parallelize over the selection of the level of significance for the id-tests.

Since I (and probably other people as well) am not an MPI user, I worked a little bit on implementing my own parallelization using dask's `distributed` library (https://distributed.dask.org/en/latest/). 

Some point about this:
- I started with Python's `multiprocessing` library, but it doesn't allow to easily scale over one machine and it's a pain to manage multiple levels of parallelization (node > significance > id test), which is why I didn't end up using it.
- Each parallelizable part of the code (pc_algo, id test) is given a cluster client in order to make it easy for the tigramite user to distribute the work on hiss own infrastructure (dask distributed provides many possible configurations)
- Dask is really just used as a distributed work queue in which each job can create subjobs, but it also comes with many interesting features -- I would encourage you to check Dask out!
-  I didn't think yet about the best way to distribute the data, so there is still a lot of data being copied around, but this could be improved
 
Would you be interested in me preparing a PR for this? If not, I wouldn't spend time documenting and cleaning up the code, so let me know!

**Comment by ewengillies** [comment]
I'll leave the final decision to @jakobrunge, but here's my thoughts:

 * Dask is great!  I love `dask`.
 * Were I to revisit the code to parallelize it, `dask` would 100% be my choice.
 * Parallelizing the code represents a large overhead in maintenance.  Mainly, its really hard to test, and even harder to ensure it works "out of the box" with the users without asking too much of them.

If @jakobrunge (and yourself) have the appetite to build, test, implement, and maintain this new feature, by all means!

An alternative would be to provide a Jupyter notebooks that has the basic setup you describe.  This would function like a github gist, just to get users who are concerned about performance off to the right foot.  I'm not sure how possible this is, as in, can we use dask + the existing `tigramite` API to achieve parallelism succinctly? If so, this could be a strong option for the developers and future users.

That's my 2 cents.  Thanks for the work on your end, I'm sure we will be able to include it in some capacity.  Good work!

**Comment by matthieubulte** [comment]
Hi, thank you for the feedback. I very much agree on the maintenance and testing costs of implementing this feature, it's a rather small code change that could break a lot of things! However, I think it could also be distributed the same way tigramite currently distributes optional features such as R interop and cython acceleration.

> can we use dask + the existing `tigramite` API to achieve parallelism succinctly? If so, this could be a strong option for the developers and future users.

If I understand your question properly, the changes required for me on the user side where simply the following:

```python
from distributed import Client, LocalCluster
from dask.distributed import worker_client

cluster = LocalCluster()
client = Client(cluster)

id_test = CMIknn(dask_client_getter=worker_client)

pcmci = PCMCI(dataframe=tdf,
                  cond_ind_test=id_test,
                  verbosity=0,
                  dask_client_getter=lambda: client)
# ... 
```

So, the `dask_client_getter` parameter is not the prettiest, but this shouldn't be too hard to improve. The nice thing is that the user can define his own cluster without tigramite having to change anything.

Note that the changes in tigramite itself aren't huge either, it's really just about broadcasting the right variables and distributing a couple of for-loops. But still, there is a lot of room for mistakes or bad decisions ;)
