### ISSUE TITLE
Tigramite and Event Data

### ISSUE THREAD

**Issue by gmcampedelli** [jakobrunge/tigramite#46]
Hello. 
This is a general question regarding the correct way to implement the algorithmic framework provided by the (great) package. I am trying to estimate causality between different time series in which all data are count (e.g., number of events i at time t, number of events j at time t, number of people affected k at time t). I was wondering whether this requires to implement the "Symbolic Time-Series" specification or is it just fine to use the "classic" setup. 
By the way, I have tried both ways but when running 
`results = pcmci_cmi_symb.run_pcmci(tau_max=10, pc_alpha=0.2)`
I get the following error: 
`ValueError: operands could not be broadcast together with shapes (169,) (173,) (169,)`
My data are stored into a np array of dimension (1096,4) in int64 format. I was trying to understand what the issue was, but I am currently struggling to find a solution.

Thanks for your help.

**Comment by jakobrunge** [comment]
You would need to provide the CMIsymb class with integer-type data and, depending on numpy, int64 might me too much and you should use int32. You won't have that many symbols anyways, I hope, since this is based on numpy.bincount and you cannot have too high dimensionality and/or symbols...
