### ISSUE TITLE
Data processing problem

### ISSUE THREAD

**Issue by Pacifique-code** [jakobrunge/tigramite#47]
Dear Jacob,
I was going trough your impressive work on tigramite, following your codes in notebook but I am getting errors: if I try this for example
np.random.seed(42)     # Fix random seed
links_coeffs = {0: [((0, -1), 0.7), ((1, -1), -0.8)],
                1: [((1, -1), 0.8), ((3, -1), 0.8)],
                2: [((2, -1), 0.5), ((1, -2), 0.5), ((3, -3), 0.6)],
                3: [((3, -1), 0.4)],
                }
T = 1000     # time series length
data, true_parents_neighbors = pp.var_process(links_coeffs, T=T)
T, N = data.shape

# Initialize dataframe object, specify time axis and variable names
var_names = [r'$X^0$', r'$X^1$', r'$X^2$', r'$X^3$']
dataframe = pp.DataFrame(data, 
                         datatime = np.arange(len(data)), 
                         var_names=var_names)

 **I get the following error:**

TypeError                                 Traceback (most recent call last)
<ipython-input-10-fbdba21bff07> in <module>()
     13 dataframe = pp.DataFrame(data, 
     14                          datatime = np.arange(len(data)),
---> 15                          var_names=var_names)

TypeError: __init__() got an unexpected keyword argument 'datatime'

**what is causing this?**
Thank you for your help

**Comment by jakobrunge** [comment]
I checked, but I cannot reproduce this problem, datatime is a proper keyword in both the developer and master branch. Check the developer branch, it will be rolled out very soon. If the problem is still there, let me know.

**Comment by nemomar** [comment]
Dear Jacob,

I have a similar problem when running the basic example:
np.random.seed(42)     # Fix random seed
links_coeffs = {0: [((0, -1), 0.7), ((1, -1), -0.8)],
                1: [((1, -1), 0.8), ((3, -1), 0.8)],
                2: [((2, -1), 0.5), ((1, -2), 0.5), ((3, -3), 0.6)],
                3: [((3, -1), 0.4)],
                }
T = 1000     # time series length
data, true_parents_neighbors = pp.var_process(links_coeffs, T=T)
T, N = data.shape
print(T,N)
# Initialize dataframe object, specify time axis and variable names
var_names = [r'$X^0$', r'$X^1$', r'$X^2$', r'$X^3$']
dataframe = pp.DataFrame(data, datatime = np.arange(len(data)), var_names=var_names)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-715ff99825d4> in <module>
     11 # Initialize dataframe object, specify time axis and variable names
     12 var_names = [r'$X^0$', r'$X^1$', r'$X^2$', r'$X^3$']
---> 13 dataframe = pp.DataFrame(data, datatime = np.arange(len(data)), var_names=var_names)

TypeError: __init__() got an unexpected keyword argument 'datatime'

What is causing it?
Thank you for your help
