### ISSUE TITLE
Performance Improvements 

### ISSUE THREAD

**Issue by dynamite9999** [jakobrunge/tigramite#48]
Dear Tigramite Experts,

   I am trying to figure out how to improve the running time of the CMIknn approach. I tried to cythonize modules that I thought could help, but no luck.
On my data, very 9 variables about 280 data points each . similar to the provided datasets  synthetically generated,  it takes about 20hrs to run using CMIknn and was wondering what I can try to improve.

I profiled (cProfile) and tried to cythonize but still takes tremendous amounts of time.

Attached is a cProfile snippet showing several iterations.
tigramite.performance.profile.log

QUESTIONS:

1. Can anyone comment on the issues found, they are not typical file, linenumber, function, but seem to be library functions ?

2. Can anyone comment on the thread locks, I am not using multi threading so suspect they are from libraries, I know there were issues prior to Python 3.4, but I am using Python 3.7, so wondering if the libraries may be using multi threads can be optimized further - not sure how other than refactoring the source ?

3. What would be the most impactful optimization in terms of reducing the run time of CMI knn ?

4. Can anyone comment if these bottlenecks can be improved by cython. I am not sure if these are numpy libraries that are already optimized or if there is any opportunities to further improving the run time

Summary of cProfile:
-----------------------
959190 2.239 0.000 163.029 0.000 <array_function internals>:2(amax)
479595 1.014 0.000 141.947 0.000 <array_function internals>:2(amin)
958958 66.351 0.000 121.180 0.000 _methods.py:167(_var)
958958 7.890 0.000 129.251 0.000 _methods.py:215(_std)
959190 3.327 0.000 158.242 0.000 fromnumeric.py:2504(amax)
479595 1.426 0.000 139.728 0.000 fromnumeric.py:2629(amin)
1919469 10.597 0.000 308.358 0.000 fromnumeric.py:73(_wrapreduction)

10911915 133.044 0.000 142.921 0.000 {built-in method numpy.array}
6624081/6135824 21.769 0.000 424.868 0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
1089000 0.783 0.000 0.783 0.000 {built-in method numpy.core._multiarray_umath.normalize_axis_index}
5288396 366.798 0.000 366.798 0.000 {method 'reduce' of 'numpy.ufunc' objects}

I had originally made my code single threaded, and still had this thread lock issue, not sure where its coming from, but suspect from libraries ?

19183800 2400.066 0.000 2400.066 0.000 {method 'acquire' of '_thread.lock' objects}
3836760 23.542 0.000 2188.027 0.001 threading.py:264(wait)
3836760 5.878 0.000 25.006 0.000 threading.py:499(init)
11510280 3.144 0.000 3.144 0.000 threading.py:507(is_set)
3836760 21.753 0.000 61.568 0.000 threading.py:763(init)
3836760 18.968 0.000 2321.026 0.001 threading.py:834(start)
3836760 7.950 0.000 276.880 0.000 threading.py:1012(join)
3836760 6.278 0.000 264.014 0.000 threading.py:1050(_wait_for_tstate_lock)
[github.tigramite.performance.profile (1).log](https://github.com/jakobrunge/tigramite/files/3805288/github.tigramite.performance.profile.1.log)

Any ideas welcomed.

**Comment by shaypal5** [comment]
For me the main time-consuming process was the analytic significance test performed for each conditional independence test. You can avoid them by providing a fixed threshold against which the resulting dependence measure will be compared.

Code-wise, you can do this by using the following two parameters when constructing the object representing the conditional independence test you use:

- `significance = "fixed_thres"`
- `fixed_thres = 0.1 . # you can use any number here`

See the documentation of the `tigramite.independence_tests.CondIndTest` class:
[https://jakobrunge.github.io/tigramite/#tigramite.independence_tests.CondIndTest](https://jakobrunge.github.io/tigramite/#tigramite.independence_tests.CondIndTest)

**Comment by jakobrunge** [comment]
Just to add: for CMIknn and CMIsymb the threshold is a bit tricky since those estimators are biased for higher dimensions. This means that for larger conditioning sets the CMI value becomes often smaller... But if you simply understand fixed_thres as a hyperparameter and not in a hypothesis testing way, it's fine...

**Comment by jakobrunge** [comment]
In the latest version CMIknn and GPDCtorch provide much faster run times. Try it out!

**Comment by shaypal5** [comment]
Amazing! :)

**Comment by JOHNPAUL-ADIMS** [comment]
Hi @jakobrunge, I am currently using the latest version, but the runtime takes more time to run about 23+ hours. Is there a new way of optimizing this?
