### ISSUE TITLE
Model selection not implemented for cmi_knn

### ISSUE THREAD

**Issue by ComplexNetSystem** [jakobrunge/tigramite#49]
Dear Runge and contributors:

I am trying to use CMIknn as the cond_ind_test in the function of PCMCI, but getting the error of "Model selection not implemented for cmi_knn". What does it mean, and could you please help me?

PS: just want to change the ParCorr to CMIknn or CMIsymb. Thanks a lot.

    cond_ind_test = CMIknn(mask_type=None,
                  significance='shuffle_test',
                  fixed_thres=None,
                  sig_samples=len,  # data length
                  sig_blocklength=3,
                  knn=10,
                  confidence='bootstrap',
                  conf_lev=0.9,
                  conf_samples=len, # data length
                  conf_blocklength=1,
                  verbosity=0)
    pcmci = PCMCI(dataframe=dataframe, cond_ind_test=cond_ind_test)
    results = pcmci.run_pcmci(tau_max=2, pc_alpha=None)
I am looking forward to hearing from you.

**Comment by jakobrunge** [comment]
Just use pc_alpha=0.2 or 0.1. Using None is only suitable for ParCorr. THere the function fits a linear model of the parents to variable j and returns the score. It's used to determine the optimal pc_alpha value.

**Comment by ComplexNetSystem** [comment]
Good evening, Runge! Thank you very much for your prompt reply. 

I succeeded to solve the problem. However, I am getting another error for the CMIknn model saying "nans after standardizing, possibly constant array!". I debugged my codes and found an array containing a row of nan.
        if self.transform == 'standardize':
            # Standardize
            array = array.astype('float')
            array -= array.mean(axis=1).reshape(dim, 1)
            array /= array.std(axis=1).reshape(dim, 1)
            # FIXME: If the time series is constant, return nan rather than
            # raising Exception
            if numpy.isnan(array).sum() != 0:
                raise ValueError("nans after standardizing, "
                                 "possibly constant array!")
        elif self.transform == 'uniform':
            array = self._trafo2uniform(array)
something wrong here. I need to fix the source codes manually?


For CMIsymb model, my codes report an error as well:  "operands could not be broadcast together with shapes". I know what the problem is.

        if weights is None:
            result = numpy.bincount(multisymb)
            # print result
        else:
            result = (numpy.bincount(multisymb, weights=multiweights)
                      / multiweights.sum())

        **flathist[:len(result)] += result    #### HERE !!!!**

        hist = flathist.reshape(tuple([self.n_symbs, self.n_symbs] +
                                      [self.n_symbs for i in range(dim - 2)])).T

This line requires that the length of the **flathist** can not be smaller than the length of **result**. But I am not sure why in an iteration, my codes get these two lists (flathist and result) that do not meet the requirement. 

Actually, it's not safe for me to change the source codes without your permission. So...I need your help. Thanks again. Really appreciate it. Have a nice weekend.

Jie Li

**Comment by jakobrunge** [comment]
CMIknn: Is your data containing constant time series? Are the numbers real-valued? No missing or NaNs? You can print the data just before the error occurs to debug...

CMIsymb: This requires the data to be integer type and every integer is a symbol. Note that you shouldn't have too many symbols since this dramatically increases the dimension. Discrete entropy estimation is a tough problem...

Don't worry to write into the code in order to debug:) I'm always happy to receive easy to debug minimal examples:)

**Comment by ComplexNetSystem** [comment]
CMIknn: the numbers in my dataset are all real-valued, but contain a lot of zeros. The error occurs when the **array** is:
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.2        0.         0.         0.         0.9230769  0.06666667
  0.         0.9230769  0.9230769  0.         0.9230769  0.9230769 ]]
numbers in the first row are all zeros (Constant!!). that 's why I got the error. Note that there is no row (the whole time series) whose numbers are all zeros. 

CMIsymb: Yes, entropy estimation is indeed a tough job. The error occurs when the **symb_array** is:
[[  0   0   0   0 100   0   0   0   0   0 150   1]
 [  0   0   0   0   0   0   1   0   0   0   0   0]]
leading to that the length of **result** (length: 151) is much greater than the length of **flathist** (length: 4). 
Thanks so much.

**Comment by jakobrunge** [comment]
CMIsymb: The array [[ 0 0 0 0 100 0 0 0 0 0 150 1] is not a proper input since you should use an "alphabet" where every symbol occurs at least once. There are not 150 different symbols here. So, just transform the data to something like 0 0 0 0 1 0 0 0 0 0 2  3...
