### ISSUE TITLE
Weird results from running tigramite on our data

### ISSUE THREAD

**Issue by romankesler** [jakobrunge/tigramite#52]
Hi,
we work with Shay Palachy whom you corresponded with in a few other issues. We using tigramite on sparse time series. After another run we investigated results of pairs of time series with high score and found some strange behavior. Two time series have no common (or close) activity surprisingly got a high causality score. We were wondering what you think could explain it, whether it's a bug or another explanation. Attaching a figure of the two time series - the difference between the last non-zero value of the bottom time series and the first non-zero value of the top one is over a week and we defined the max lag as 4 hours.
Any insight you might have would be very appreciated.

Thanks in advance,
Roman and Michal
![Screen Shot 2019-11-13 at 15 31 36](https://user-images.githubusercontent.com/11397691/69557944-150c2680-0fb0-11ea-97f2-0eb2fa245232.png)

**Comment by jakobrunge** [comment]
You would need to provide much more info to talk about this. Which CI test etc. Not all estimators are useful for such datasets.

**Comment by shaypal5** [comment]
Hey Jakob,

Attached here - in a `zip` file - is a Python script and two `csv` files. The script reproduces the results on both the original data and on a small subset of it. Running it on the full data can take some time, so you may want to start with the smaller file (suffixed with `_toy`).

Thank you very much for your help, :)
Shay and the rest of the team

[example52.zip](https://github.com/jakobrunge/tigramite/files/3916115/example52.zip)
