### ISSUE TITLE
Pip repo contains an old version of the library

### ISSUE THREAD

**Issue by andreipruteanu** [jakobrunge/tigramite#53]
Please upload the latest version of the library to pip. Currently it has reached version 4.1 while on Pip repo I could find 3.0b. This leads to errors while running the examples in your docs such as:

TypeError: __init__() got an unexpected keyword argument 'var_names'
>>> med = LinearMediation(dataframe=dataframe)

**Comment by jakobrunge** [comment]
I will!

**Comment by gioxc88** [comment]
up for this, same here. Still outdated on pip

**Comment by gioxc88** [comment]
Is there any reason why this is still outdated on pypi?

**Comment by jakobrunge** [comment]
Tigramite 4.2 is now in pip: just type

pip install tigramite

(currently only works on Linux)
