### ISSUE TITLE
print_significant_links and return_significant_parents: clarification and consistency between names

### ISSUE THREAD

**Issue by gioxc88** [jakobrunge/tigramite#56]
Hello and thank you for this amazing package.
I was testing it out this afternoon after reading the article and the supplementary materials and I would like to get a clarification (maybe my understanding is wrong):

after creating the PCMCI instance (and having called the run_pcmci) I get those two methods print_significant_links and return_significant_parents: the former refers to significant links and the latter refers to significant parents. 

Is it true though that significant links and significant parents are the same thing (at least from my understanding of the theory)?

If that is true I would suggest to change the name to avoid confusion.

Many thanks

**Comment by jakobrunge** [comment]
I now switched to a new name "return_significant_links" with new keyword "include_lagzero_links" and kept the old function, too, with a Deprecation warning...

**Comment by gioxc88** [comment]
thank you!
