### ISSUE TITLE
How to deal with 'almost' deterministic time-series?

### ISSUE THREAD

**Issue by fipeop** [jakobrunge/tigramite#57]
Thanks for the great package Jakob! I am dealing with time-series (coming from a physical model) that have very small noise, and are closely correlated such as the following:

Original curves
![image](https://user-images.githubusercontent.com/43591071/76325954-4dfdac00-62be-11ea-8d80-f577d0f3f921.png)

First difference

![image](https://user-images.githubusercontent.com/43591071/76261967-96bb5380-6231-11ea-8a35-7ce271705cb3.png)

Do you have any recommendations to deal with them? I am pretty sure that they don't satisfy PCMCI's assumptions. When I try to run run_pcmci, I get the following error:

/usr/local/lib/python3.6/dist-packages/tigramite/independence_tests.py in _get_single_residuals(self, array, target_var, standardize, return_means)
   1064             array /= array.std(axis=1).reshape(dim, 1)
   1065             if np.isnan(array).sum() != 0:
-> 1066                 raise ValueError("nans after standardizing, "
   1067                                  "possibly constant array!")

I would like to identify which one of the first five time series has the most impact on the 6th time series (power). I would appreciate any reference to some appropriate approach.

Thank you!

**Comment by jakobrunge** [comment]
You could either add dynamical noise (NOT on the time series output by the model) or run the analysis with random initial conditions and then input those time series (in some way) to PCMCI. The latter would require more deliberation...

**Comment by fipeop** [comment]
Thanks, I didn't use PCMCI in the end; but great work!
