### ISSUE TITLE
Save results of run_pcmci in instance attribute

### ISSUE THREAD

**Issue by gioxc88** [jakobrunge/tigramite#59]
I noticed that after running the run_pcmci method, the results are not stored in the class instance, hence once the method is run, if you don't store the values in a separate variable they are lost.

I think it would be useful to store the results inside the instance with something like  self.results = self.run_mci()

thank you

**Comment by ewengillies** [comment]
thanks for using the library!  While I understand why would help for your use case, its largely considered an anti-pattern to have calculator-like objects (in this case, the the `PCMCI` class) store results.  This would make the calculator "stateful".  

Here is a discussion on statefulness that summarizes the key points: https://dzone.com/articles/stateful-or-stateless-classes

In general, PCMCI stores method parameters in `self.`, but not the results.  Instead, the results are passed to the user as a dictionary.  The recommended way to keep the results is, as you say, to store them in a variable like:

```
results = pcmci_instance.run_pcmci()
```

**Comment by gioxc88** [comment]
I understand. Thank you for the explanation.
