### ISSUE TITLE
 FutureWarning: rcond parameter will change to the default of machine precision times max(M, N) where M and N are the input matrix dimensions. To use the future default and silence this warning we advise to pass rcond=None, to keep using the old, explicitly pass rcond=-1.

### ISSUE THREAD

**Issue by yuditsabet** [jakobrunge/tigramite#61]
Hi,
Thank you for TIGRAMITE!
I have this error when run:
pcmci.run_pcmci(tau_min =1, tau_max=30, pc_alpha=0.1)

independence_tests.py:1144: FutureWarning: rcond parameter will change to the default of machine precision times max(M, N) where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass rcond=None, to keep using the old, explicitly pass rcond=-1.
beta_hat = numpy.linalg.lstsq(z, y)[0]
Traceback (most recent call last):
File "tigramite_era_geo_corpar.py", line 53, in
results_pcmi = pcmci.run_pcmci(tau_min =1, tau_max=3, pc_alpha=0.1)
File "/home/yuditsabet/.local/lib/python3.7/site-packages/tigramite/pcmci.py", line 1385, in run_pcmci
max_combinations=max_combinations,
File "/home/yuditsabet/.local/lib/python3.7/site-packages/tigramite/pcmci.py", line 718, in run_pc_stable
print("\n## Variable %s" % self.var_names[j])
KeyError: 132

Besides, when run:
pcmci.run_gpdc(tau_min =1, tau_max=30, pc_alpha=0.1) not end
how long does it take if the process is not parallelized??

**Comment by jakobrunge** [comment]
Would you have a minimal working example? Also, try the developer branch and see whether the same error appears...

**Comment by yuditsabet** [comment]
Im sorry,
I am working with a 2D (140x1296) matrix of precipitable water; where the observations are time (months) and the variables are grids in space. I want to find linear or non-linear dependencies with lag of up to 30 months. Did I understand from the bibliography that gpdc helps you find possible non-linear links?

I don't have the error on my computer run_pcmi for numpy == 1.16, however when I run it on another computer with the same library versions it returns that error

**Comment by jakobrunge** [comment]
Are you ruse 140 is the time dimension? I tested it with Pythin 2.7 and 3.6 and 3.7. Standard numpy through anaconda.
GPDC works for nonlinear dependencies, but takes much longer than ParCorr, try this first.

**Comment by yuditsabet** [comment]
Yes 140 is time
 UserWarning: data.shape = (140, 1296), is it of shape (observations, variables) ?
  " is it of shape (observations, variables) ?")
FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  beta_hat = numpy.linalg.lstsq(z, y)[0]
Traceback (most recent call last):
  File "tigramite_era_geo_corpar.py", line 53, in <module>
    results_pcmi = pcmci.run_pcmci(tau_min =1, tau_max=3, pc_alpha=0.1)
  File "/home/yuditsabet/.local/lib/python3.7/site-packages/tigramite/pcmci.py", line 1385, in run_pcmci
    max_combinations=max_combinations,
  File "/home/yuditsabet/.local/lib/python3.7/site-packages/tigramite/pcmci.py", line 718, in run_pc_stable
    print("\n## Variable %s" % self.var_names[j])
KeyError: 140

I understand that ParCorr does not find nonlinear dependencies so I want to test ParCor with run_pcmi for linear dependencies and GPDC with run_gpdc for nonlinear dependencies
There is some simple way to parallelize the latter. I have no experience in parallelization sorry.
Thank you!

**Comment by jakobrunge** [comment]
I would need a minimal example to reproduce... In any case data.shape = (140, 1296) seems too high-dimensional for causal inference...

**Comment by yuditsabet** [comment]
Thank you Jakob. 
Your help has been very helpful to me. I applied the dimensionality reduction and I was left with 10 components. data.shape = (10,1296). It is also exaggerated?
