### ISSUE TITLE
Could not import r-package RCIT

### ISSUE THREAD

**Issue by heiheisao** [jakobrunge/tigramite#62]
Hellow! I met a error "Could not import r-package RCIT". Do I need to download the rcit package in R?  I didn't find this package in 3.6.3 or 4.0.0 version.

**Comment by jakobrunge** [comment]
If you want to use the RCOT (part of rcit package) [conditional independence test](https://jakobrunge.github.io/tigramite/#tigramite.independence_tests.RCOT), then run the bash script shipped with tigramite to install the required r-packages. Else, it's not needed.

**Comment by heiheisao** [comment]
> If you want to use the RCOT (part of rcit package) [conditional independence test](https://jakobrunge.github.io/tigramite/#tigramite.independence_tests.RCOT), then run the bash script shipped with tigramite to install the required r-packages. Else, it's not needed.

thanks for you repeat!!

**Comment by jakobrunge** [comment]
RCOT has been removed from official support... integrating R is just a pain. But you can still use the old RCOT class!
