### ISSUE TITLE
Complex multivariate time series

### ISSUE THREAD

**Issue by shiyishu** [jakobrunge/tigramite#64]
Thanks for providing such a useful time series analysis tool!
Does this toolbox support complex number case or it only support real number? Will the performance degrade if I divide a complex multivariate time series into two real parts and analysis seperately?

**Comment by jakobrunge** [comment]
You mean whether PCMCI deals with single time series that are two-dimensional (real and imaginary value) and the answer is no (currently). I would say dividing up the analysis and look at the network among only the real parts and the network among only the imaginary part is an option, but it misses cross-interdependencies. Or you use polar coordinates if the radius makes more sense...

**Comment by shiyishu** [comment]
Thanks for your reply and I can't agree with you more!  I'm also considering that perhaps conducting Conditional Independence Test in a complex way can address this problem.
