### ISSUE TITLE
Question  regarding tigramite_tutorial_missing_masking

### ISSUE THREAD

**Issue by egalytska** [jakobrunge/tigramite#65]
Dear Jakob, 
I have a question regarding the description of the Masking procedure in the **tigramite_tutorial_missing_masking**. 
In the description of the tutorial, it is written that if we are interested in winter months only, then we should mark "_all winter month data in ( 𝑋1,𝑋2,𝑋3 ) in mask with a 1 (or True)._ "  

But in the python example of the same tutorial, I understood that in order to focus on winter half year, the masking is set for summer months as true values: 
....
        # Summer half year
        data_mask[[t, t-1]] = True
....

This brings some confusion.  

Plotting timeseries **_plot_timeseries_** with masking I would expect grey to stand for values that are not intended to be used in the analysis. But if I follow the description and mask winter months (set these months as True or 1), they appear as grey in the timeseries plot. 

So my questions are: 
(i) if I interested in winter month only, should I mask winter months? Or should I mask other seasons? 
(ii) black lines in  **_plot_timeseries_** stand for values that will be used by tigramite, grey - that will be 'ignored'?  
Thanks in advance. 
Best regards,
Evgenia

**Comment by jakobrunge** [comment]
You spotted a typo! Mask=1 means that this sample is NOT used. I'll fix it in the developer branch that will be pushed sometime soon.

**Comment by egalytska** [comment]
Great, thanks. Then all is clear. 
Cheers,
Evgenia
