### ISSUE TITLE
How to make PCMCI picture?

### ISSUE THREAD

**Issue by yubaocheng258** [jakobrunge/tigramite#67]
![mci_schematic](https://user-images.githubusercontent.com/66513596/84453584-c479c380-ac8a-11ea-8bbc-213f57a019e7.png)
I want to use my own data to make PCMCI picture like that, I wonder what should I do? Sorry I can't understand the instruction well. Could you make a explanation? Thank you very much.

**Comment by jakobrunge** [comment]
That picture was drawn by hand, but you can generate time series graphs automatically from tigramite output with the plotting.py module. Find examples in the tutorials!
