### ISSUE TITLE
why I get a full connected graph?

### ISSUE THREAD

**Issue by SimplyWenjing** [jakobrunge/tigramite#68]
Thanks for providing such a useful time series analysis tool which is quite interesting but I faced the following potential bottlenecks as having no in-depth knowledge:

I have a time series dataset including 8 variables (all data were z-score transferred). I followed the example of TIGRAMITE to constructed their causal relationships. Unfortunately, I got a full connected graph, and the mean false positive is more than 0.5.
I see that there is a parameter “links_coeffs” in the example. However, I don’t know any dependencies among variables. Without this parameter, can I get the true causality?

I think maybe my data is nonstationary, which leads to a full connected graph. Is there a method of stationarity test in order to know whether the data is suitable for using the PCMCI algorithm?
Attached is my data and code. Hope your little insight guidance will solve my BIG PROBLEM. 
[learn causality from time series data.zip](https://github.com/jakobrunge/tigramite/files/4843342/learn.causality.from.time.series.data.zip)

**Comment by jakobrunge** [comment]
I would suggest to go through the papers and tutorials to understand PCMCI.

Likely your data has some unobserved common driver that makes them dependent and is manifest through a non-stationary behavior. If you can model that driver, you should remove it from the time series... This might be through smoothing residuals or something similar...

**Comment by SimplyWenjing** [comment]
> I would suggest to go through the papers and tutorials to understand PCMCI.
> 
> Likely your data has some unobserved common driver that makes them dependent and is manifest through a non-stationary behavior. If you can model that driver, you should remove it from the time series... This might be through smoothing residuals or something similar...

Thanks for your reply. I will follow your suggest to deal with my data. Thanks!
