### ISSUE TITLE
Improve Tutorials and Documentation

### ISSUE THREAD

**Issue by ewengillies** [jakobrunge/tigramite#7]
While the current tutorial and documentation are comprehensive, we should ensure that new users have all they need to get started.  Here is a list of possible improvements:

 - [x] Factor current tutorial into smaller tutorials
 - [ ] Factor existing documentation page into smaller pages
 - [ ] Write a quick-start guide
 - [ ] Extend tutorials to also cover the definition/effects of the various parameters

**Comment by manujchandra** [comment]
Hi,

If we want to test the independence of stock prices (two or more stocks are independent of each other) for correlation analysis which of the [following](https://github.com/jakobrunge/tigramite/blob/master/tigramite_tutorial.ipynb) tests should be employed?

Thanks.

**Comment by ewengillies** [comment]
perhaps you commented on this thread by mistake.  if you'd like an answer, please open a new issue.  this issue is about "Improve Tutorials and Documentation" for `tigramite`.  I'm closing it now as my development on this project has finished some time ago.
