### ISSUE TITLE
plot_graph: control space between nodes and edges

### ISSUE THREAD

**Issue by dadelforge** [jakobrunge/tigramite#70]
When I plot a graph with custom coordinates with the `node_pos` argument, I obtain an important buffer between the nodes and the edges (see figure below). So far, I haven't been able to control this parameter. Is there any workaround?

![téléchargement](https://user-images.githubusercontent.com/25319678/86130066-ea54f400-bae3-11ea-8900-31f54a9ddedc.png)

**Notes**

My coordinates are
```python
ycoord= np.array([25, 25, -20, -20, -20, 10, 13,  8, 14, 0, 9])
xcoord= np.array([16, 32,  24,   8,  40, 22, 32, 39, 17, 5, 7])
```
Package versions are:
tigramite version: 4.1
matplotlib version: 3.2.1
networkx version: 2.4

**Remarks**
I just spot a typo in the documentation for the 3 graphs (dag, time-series and mediation) :
```python
curved_radius, float, optional (default: 0.2)
        Curvature of links. Passed on to FancyArrowPatch object.
```
change into
```python
curved_radius :  float, optional (default: 0.2)
        Curvature of links. Passed on to FancyArrowPatch object.
```

**Comment by jakobrunge** [comment]
We are working on an updated plotting currently and hope to release it in the next days/weeks. Thanks for spotting the typo! If you want to play around yourself, you have to adjust the parameters

shrinkA, shrinkB : scalar, optional (default: 2)
Shrinking factor of the tail and head of the arrow respectively

**Comment by jakobrunge** [comment]
It's updated now, raise another issue if you see one!
