### ISSUE TITLE
OUT_OF_MEMORY (exit code 0): run_pcmi_paralell.py 

### ISSUE THREAD

**Issue by yuditsabet** [jakobrunge/tigramite#72]
Hello Jacob,
I am trying to run the parallelization script for a 10x1296 array and no matter how much memory I allocate, the process kills me for 35 min due to memory problems. I'm allocating up to 50GB of memory and it seems to demand a lot more. When you ran the script how many nodes did you need, how many tasks per node, and how much memory?
Thank you

Job ID: 18178
Cluster: xxx
User/Group: yyy/users
State: OUT_OF_MEMORY (exit code 0)
Cores: 1
CPU Utilized: 00:46:57
CPU Efficiency: 99.16% of 00:47:21 core-walltime
Job Wall-clock time: 00:47:21
Memory Utilized: 54.79 GB
Memory Efficiency: 99.63% of 54.99 GB

**Comment by jakobrunge** [comment]
Are you sure your time-dimension is just 10 and there are 1296 variables? This is not a feasible problem...
