### ISSUE TITLE
Multiple samples causality testing

### ISSUE THREAD

**Issue by 27Topquark** [jakobrunge/tigramite#76]
Hello Jakob,
In your papers, you use a single instance of a multivariate time series. Consequently, the p-values for the causal connections tested are obtained by applying tests within this single time series. 

What would be the method to obtain p-values if one is using multiple instances of the same multivariate time series of different lengths?

Say one connection is causal and significant in one instance and not in the other, how would one summarise such a connection.

Thank you for any help or suggestions.

**Comment by jakobrunge** [comment]
Good question. you could apply FDR to the individual links across the ensemble. That gives you a corrected q-value for the individual links.
