### ISSUE TITLE
Regime-PCMCI

### ISSUE THREAD

**Issue by 27Topquark** [jakobrunge/tigramite#77]
Hello Jakob,
I was looking for the part of the code mentioned in your paper: Reconstructing regime-dependent causal relationships from
observational time series.

How can we run this version of the PCMCI algorithm?

Thank you for your help

**Comment by jakobrunge** [comment]
Hi, this paper/method is still under review and code will follow later...

**Comment by andrewcztrack** [comment]
hi @jakobrunge !! I hope your well!
i have been following this package from the very beginning and I love its growth!
any update on the above methods.
Kind regards and thanks,
Andrew

**Comment by leizan** [comment]
Hi everyone,
So finally, does the code for this method been released or not ?

Thank you for your answer!
