### ISSUE TITLE
NameError: name 'tigramite_cython_code' is not defined - independence tests not working

### ISSUE THREAD

**Issue by edaltorrione** [jakobrunge/tigramite#78]
Dear Dr. Runge, 

I am trying to use tigramite to recover the causal structure of some economic time series. I am not an expert of python, so my question could be trivial, and I know this issue has already been rised, but it seems that I still cannot get around the problem . When I perform the GDPC test I get the error NameError: name 'tigramite_cython_code' is not defined.
 It probably has to do with the installation of the package. This is the output I get when I install tigramite from the command prompt. 

`running install
running bdist_egg
running egg_info
writing tigramite.egg-info\PKG-INFO
writing dependency_links to tigramite.egg-info\dependency_links.txt
writing requirements to tigramite.egg-info\requires.txt
writing top-level names to tigramite.egg-info\top_level.txt
reading manifest file 'tigramite.egg-info\SOURCES.txt'
writing manifest file 'tigramite.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
creating build\bdist.win32\egg
creating build\bdist.win32\egg\tigramite
copying build\lib.win32-3.7\tigramite\data_processing.py -> build\bdist.win32\egg\tigramite
copying build\lib.win32-3.7\tigramite\independence_tests.py -> build\bdist.win32\egg\tigramite
copying build\lib.win32-3.7\tigramite\models.py -> build\bdist.win32\egg\tigramite
copying build\lib.win32-3.7\tigramite\pcmci.py -> build\bdist.win32\egg\tigramite
copying build\lib.win32-3.7\tigramite\plotting.py -> build\bdist.win32\egg\tigramite
copying build\lib.win32-3.7\tigramite\tigramite_cython_code.cp37-win32.pyd -> build\bdist.win32\egg\tigramite
copying build\lib.win32-3.7\tigramite\__init__.py -> build\bdist.win32\egg\tigramite
byte-compiling build\bdist.win32\egg\tigramite\data_processing.py to data_processing.cpython-37.pyc
byte-compiling build\bdist.win32\egg\tigramite\independence_tests.py to independence_tests.cpython-37.pyc
byte-compiling build\bdist.win32\egg\tigramite\models.py to models.cpython-37.pyc
byte-compiling build\bdist.win32\egg\tigramite\pcmci.py to pcmci.cpython-37.pyc
byte-compiling build\bdist.win32\egg\tigramite\plotting.py to plotting.cpython-37.pyc
byte-compiling build\bdist.win32\egg\tigramite\__init__.py to __init__.cpython-37.pyc
creating stub loader for tigramite\tigramite_cython_code.cp37-win32.pyd
byte-compiling build\bdist.win32\egg\tigramite\tigramite_cython_code.py to tigramite_cython_code.cpython-37.pyc
creating build\bdist.win32\egg\EGG-INFO
copying tigramite.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying tigramite.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying tigramite.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying tigramite.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying tigramite.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
writing build\bdist.win32\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
tigramite.__pycache__.tigramite_cython_code.cpython-37: module references __file__
creating 'dist\tigramite-4.1.0-py3.7-win32.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing tigramite-4.1.0-py3.7-win32.egg
creating c:\python37\lib\site-packages\tigramite-4.1.0-py3.7-win32.egg
Extracting tigramite-4.1.0-py3.7-win32.egg to c:\python37\lib\site-packages
Adding tigramite 4.1.0 to easy-install.pth file

Installed c:\python37\lib\site-packages\tigramite-4.1.0-py3.7-win32.egg
Processing dependencies for tigramite==4.1.0
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using c:\python37\lib\site-packages
Searching for scipy==1.1.0
Best match: scipy 1.1.0
Adding scipy 1.1.0 to easy-install.pth file

Using c:\python37\lib\site-packages
Searching for numpy==1.15.2
Best match: numpy 1.15.2
Adding numpy 1.15.2 to easy-install.pth file

Using c:\python37\lib\site-packages
Finished processing dependencies for tigramite==4.1.0`
>

Also, when I try to import GDPC, CMInkk, i get the following output:
`from tigramite.independence_tests import ParCorr, GPDC, CMIknn, CMIsymb`

Could not import packages for CMIknn and GPDC estimation
Could not import rpy package
Could not import r-package RCIT

Thank you for your help!

**Comment by jakobrunge** [comment]
Please check the latest tigramite version, which now can also be installed via 
pip install tigramite

It was more tested in Linux, but I hope it also works under Windows...
