### ISSUE TITLE
Dealing with non-stationarity

### ISSUE THREAD

**Issue by Cristhiant** [jakobrunge/tigramite#79]
Hi, first, thanks for such a valuable contribution to causality tools. 

In my pipeline implementation I added a function to identify non-stationary time series by ADF Tests and then convert them to stationary data. We know that this conversion is not always possible. So, reading your papers, you mention the option of piecewise stationary processes by including background knowledge on the stationary regimes and estimate the graphs separately. My questions: 

- Is there any function available in tigramite dealing with this piecewise methodology resulting in a single output graph? (considering closed systems, so confounding is not an option to remove non-stationarity)
- If not, How do you recommend dealing with it in order to satisfy the stationarity assumption?
- What do you mean by "include background knowledge"?

I have checked the tutorials and they just mention that stationarity is covered in other Notebooks. In case it is still an open issue, i would be interested in collaborating.

Thank you!  again

**Comment by jakobrunge** [comment]
> Is there any function available in tigramite dealing with this piecewise methodology resulting in a single output graph? (considering closed systems, so confounding is not an option to remove non-stationarity)

It's the masking option explained in a tutorial. You get a single graph for a mask that you choose and should cover the stationary part of your sample. The knowledge of which time sample corresponds to which regime is the background knowledge...

**Comment by jakobrunge** [comment]
I want to add, that in a recent modification of PCMCI, co-authors and I have addressed a particular kind of non-stationarity, namely if the causal relations change depending on discrete regimes, see here: https://arxiv.org/abs/2007.00267

**Comment by andrewcztrack** [comment]
@jakobrunge thank you! Has this been added to the toolkit 
Cheers Andrew

**Comment by jakobrunge** [comment]
Not yet...

**Comment by andrewcz** [comment]
Hi @jakobrunge  I hope your well!
I was just wondering if the package has been updated with the above.
Is there a possible eta.

Kind regards and sincere thanks,
Andrew

**Comment by andrewcz** [comment]
@jakobrunge I hope your well. Has this possibility been added to the package.

Kind regards and thanks,
Andrew

**Comment by sagarsimha** [comment]
@andrewcz We are yet to integrate Regime-PCMCI and is planned for in the coming months. We will write back when done.

**Comment by andrewcz** [comment]
Hi @jakobrunge ! I hope your well!

Just wondering if there was an update on the above.

kind regards and thanks,
Andrew.

**Comment by sagarsimha** [comment]
Hi. The R-PCMCI is yet to be integrated. Watch out for the release notes (on developer and master) for the latest update respectively.

**Comment by andrewcz** [comment]
Thank you @sagarsimha much appreciated 🙂! Do you possibly have a rough ETA on when it maybe released.
Kind regards and thanks,
Andrew

**Comment by sagarsimha** [comment]
Tough to say. But we can share the code we have for R-PCMCI. However, it is still in developing mode.

**Comment by andrewcz** [comment]
Thank you @sagarsimha ! much appreciated. Its ok, i will wait for the update to the main repo.

Cheers!
Andrew

**Comment by andrewcz** [comment]
Hi all! @sagarsimha was just wondering if I could get update on the above

**Comment by leizan** [comment]
Hi. Do you have something new about this issue? 

Thanks,
Lei

**Comment by leizan** [comment]
Hello @sagarsimha! I hope you're doing well. 
Would it be possible for you to share the R-PCMCI code, even if it's still in development? 
I need it for testing purposes. 

Kind regards, 
Lei.

**Comment by jakobrunge** [comment]
Sorry for the looooooong delay, I finally managed to re-write the code using open-source code for the optimization step. 

Have a look at https://github.com/jakobrunge/tigramite/blob/master/tutorials/causal_discovery/tigramite_tutorial_regime_pcmci.ipynb

And please let us now any issues/bugs!

**Comment by leizan** [comment]
Fantastic! I believe this will prove immensely beneficial to me.

Thanks again,
Lei.

**Comment by jakobrunge** [comment]
Please play around with hyper-parameters. You can discuss your findings and post questions on the Discussion page.
