### ISSUE TITLE
plotting.py Index Error - on my own data

### ISSUE THREAD

**Issue by dynamite9999** [jakobrunge/tigramite#81]
Dear tigramite experts,

I ran the jupyter notebooks with no issues. 
however when I used my own data, I ran into this strange error in the following cell:    
I was wondering if anyone had any suggestions on how to go about resolving this ? I am pretty sure the data is in the correct shape, as the same data ran fine with ParrCorr, GPDC. It errrors only in CMIknn.

cmi_knn = CMIknn(significance='shuffle_test', knn=0.1, shuffle_neighbors=5, transform='ranks')
    pcmci_cmi_knn = PCMCI(
        dataframe=dataframe, 
        cond_ind_test=cmi_knn,
        verbosity=2)
    results = pcmci_cmi_knn.run_pcmci(tau_max=2, pc_alpha=0.05)
    pcmci_cmi_knn.print_significant_links(
            p_matrix = results['p_matrix'], 
            val_matrix = results['val_matrix'],
            alpha_level = 0.01)
    print(results)
    link_matrix = pcmci_cmi_knn.return_significant_links(pq_matrix=results['p_matrix'],
                        val_matrix=results['val_matrix'], alpha_level=0.01)['link_matrix']
    tp.plot_graph(
        val_matrix=results['val_matrix'],
        link_matrix=link_matrix,
        var_names=var_names,
        link_colorbar_label='cross-MCI',
        node_colorbar_label='auto-MCI',
        vmin_edges=0.,
        vmax_edges = 0.3,
        edge_ticks=0.05,
        cmap_edges='OrRd',
        vmin_nodes=0,
        vmax_nodes=.5,
        node_ticks=.1,
        cmap_nodes='OrRd',
        ); plt.show()

Plotting.py in Basics notebook on my own data
...

     .
..
        [0.   , 0.209, 0.074],
        [0.922, 0.559, 0.889],
        [0.346, 0.299, 0.734],
        [0.   , 0.578, 0.037],
        [0.83 , 0.849, 0.63 ],
        [1.   , 0.713, 0.166]]]), 'q_matrix': None, 'conf_matrix': None}
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-9eb448648418> in <module>
     26         vmax_nodes=.5,
     27         node_ticks=.1,
---> 28         cmap_nodes='OrRd',
     29         ); plt.show()
     30 

~/dev2/rootcause/src/t1/tigramite/plotting.py in plot_graph(val_matrix, var_names, fig_ax, figsize, sig_thres, link_matrix, save_name, link_colorbar_label, node_colorbar_label, link_width, link_attribute, node_pos, arrow_linewidth, vmin_edges, vmax_edges, edge_ticks, cmap_edges, vmin_nodes, vmax_nodes, node_ticks, cmap_nodes, node_size, arrowhead_size, curved_radius, label_fontsize, alpha, node_label_size, link_label_fontsize, lag_array, network_lower_bound, show_colorbar)
   1397         link_colorbar_label=link_colorbar_label,
   1398         network_lower_bound=network_lower_bound,
-> 1399         show_colorbar=show_colorbar,
   1400         # label_fraction=label_fraction,
   1401         # inner_edge_style=inner_edge_style

~/dev2/rootcause/src/t1/netengine/plotting.py in _draw_network_with_curved_edges(fig, ax, G, pos, node_rings, node_labels, node_label_size, node_alpha, standard_size, standard_cmap, standard_color, log_sizes, cmap_links, cmap_links_edges, links_vmin, links_vmax, links_edges_vmin, links_edges_vmax, links_ticks, links_edges_ticks, link_label_fontsize, arrowstyle, arrowhead_size, curved_radius, label_fontsize, label_fraction, link_colorbar_label, inner_edge_curved, inner_edge_style, network_lower_bound, show_colorbar)
    997 
    998             if ring == 0:
--> 999                 ax.text(pos[n][0], pos[n][1], node_labels[n],
   1000                         fontsize=node_label_size,
   1001                         horizontalalignment='center',

IndexError: list index out of range

**Comment by jakobrunge** [comment]
Hm... I've just updated the plotting function in the developer branch. Can you check again and provide a minimal working example?

**Comment by dynamite9999** [comment]
Dear Dr. Runge, 
I updated plotting.py with your updated version, and have a different but similar error, see below. 

Here is my code snippet, dataframe is based on attached csv file. This same file works fine on previous versions.

    cmi_knn = CMIknn(significance='shuffle_test', knn=0.1, shuffle_neighbors=5, transform='ranks')
    pcmci_cmi_knn = PCMCI(
        dataframe=dataframe, 
        cond_ind_test=cmi_knn,
        verbosity=2)
    results = pcmci_cmi_knn.run_pcmci(tau_max=2, pc_alpha=0.05)
    pcmci_cmi_knn.print_significant_links(
            p_matrix = results['p_matrix'], 
            val_matrix = results['val_matrix'],
             alpha_level = 0.01)
    print(results)
    link_matrix = pcmci_cmi_knn.return_significant_links(pq_matrix=results['p_matrix'],
                        val_matrix=results['val_matrix'], alpha_level=0.01)['link_matrix']
    tp.plot_graph(
        val_matrix=results['val_matrix'],
        link_matrix=link_matrix,
        var_names=var_names,
        link_colorbar_label='cross-MCI',
        node_colorbar_label='auto-MCI',
        vmin_edges=0.,
        vmax_edges = 0.3,
        edge_ticks=0.05,
        cmap_edges='OrRd',
        vmin_nodes=0,
        vmax_nodes=.5,
        node_ticks=.1,
        cmap_nodes='OrRd',
        ); plt.show()


=====================================================================================
..
..
..
[0.951, 0.984, 0.973],
 [0.005, 0.043, 0.007],
 [0.982, 0.702, 0.807],
 [0.875, 0.171, 0.765],
 [0.   , 0.026, 0.   ],
 [0.945, 0.967, 0.998],
 [1.   , 0.948, 0.995],
 [0.844, 0.896, 0.961]],

[[0.318, 0.471, 0.386],
 [0.852, 0.85 , 0.683],
 [0.889, 0.862, 0.66 ],
 [0.263, 0.442, 0.918],
 [0.456, 0.188, 0.428],
 [0.   , 0.183, 0.073],
 [0.914, 0.623, 0.885],
 [0.344, 0.328, 0.748],
 [0.   , 0.574, 0.023],
 [0.844, 0.842, 0.692],
 [1.   , 0.754, 0.161]]]), 'q_matrix': None, 'conf_matrix': None}
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-47-339460a0f668> in <module>
26         vmax_nodes=.5,
27         node_ticks=.1,
---> 28         cmap_nodes='OrRd',
29         ); plt.show()
30 

~/dev2/rootcause/src/t1/tigramite/plotting.py in plot_graph(val_matrix, var_names, fig_ax, figsize, sig_thres, link_matrix, save_name, link_colorbar_label, node_colorbar_label, link_width, link_attribute, node_pos, arrow_linewidth, vmin_edges, vmax_edges, edge_ticks, cmap_edges, vmin_nodes, vmax_nodes, node_ticks, cmap_nodes, node_size, node_aspect, arrowhead_size, curved_radius, label_fontsize, alpha, node_label_size, link_label_fontsize, lag_array, network_lower_bound, show_colorbar, inner_edge_style)
1818         link_colorbar_label=link_colorbar_label,
1819         network_lower_bound=network_lower_bound,
-> 1820         show_colorbar=show_colorbar,
1821         # label_fraction=label_fraction,
1822     )

~/dev2/rootcause/src/t1/tigramite**/plotting.py in _draw_network_with_curved_edges**(fig, ax, G, pos, node_rings, node_labels, node_label_size, node_alpha, standard_size, node_aspect, standard_cmap, standard_color, log_sizes, cmap_links, cmap_links_edges, links_vmin, links_vmax, links_edges_vmin, links_edges_vmax, links_ticks, links_edges_ticks, link_label_fontsize, arrowstyle, arrowhead_size, curved_radius, label_fontsize, label_fraction, link_colorbar_label, inner_edge_curved, inner_edge_style, network_lower_bound, show_colorbar)
1467                     pos[n][0],
1468                     pos[n][1],
-> 1469                     node_labels[n],
1470                     fontsize=node_label_size,
1471                     horizontalalignment="center",

IndexError: list index out of range





[a.zip](https://github.com/jakobrunge/tigramite/files/5113256/a.zip)

**Comment by dynamite9999** [comment]
Dear Dr. Runge,

its now working. I ran against the latest build today, and now its working.  Thank you. 
dk

**Comment by jakobrunge** [comment]
Great! It is now the Master and also in pip...
