### ISSUE TITLE
cython installation error on linux

### ISSUE THREAD

**Issue by gioxc88** [jakobrunge/tigramite#84]
I created a new virtual environment with python -venv venv then activate the venv and run pip install tigramite

but I got the following error:

    ERROR: Command errored out with exit status 1:
     command: /home/gperciaccante/dev/envs/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3mtg8suu/tigramite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3mtg8suu/tigramite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7a8okhy4
         cwd: /tmp/pip-install-3mtg8suu/tigramite/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3mtg8suu/tigramite/setup.py", line 71, in <module>
        EXT_MODULES += define_extension("tigramite.tigramite_cython_code")
      File "/tmp/pip-install-3mtg8suu/tigramite/setup.py", line 44, in define_extension
        return cythonize(Extension(extension_name, source_files))
      File "/home/gperciaccante/dev/envs/test/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 972, in cythonize
        aliases=aliases)
      File "/home/gperciaccante/dev/envs/test/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/gperciaccante/dev/envs/test/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'tigramite/tigramite_cython_code.pyx' doesn't match any files

**Comment by jakobrunge** [comment]
Using Anaconda it should work, we're looking into what might be the issue here...

**Comment by mbruhns** [comment]
I'm not able to reproduce the error, can you provide further information on the system/setup you're using?

**Comment by vvoutilainen** [comment]
I was getting the same error as well on Windows machine. The following three attempts `pip install tigramite`,  `conda activate myenv; python /path/to/tigramite/setup.py install`, and  `conda activate myenv; python /path/to/tigramite/setup.py develop` all led to the error. However, once I moved the command directory to cloned _tigramite_ folder and ran `python setup.py install` I was able to install _tigramite_ into my conda environment.

**Comment by jakobrunge** [comment]
I've adapted the setup.py in the developer branch. Can you test it again?

**Comment by gioxc88** [comment]
tested on linux both python 3.7 and python 3.8 and it works for me.
On windows I never had this problem

**Comment by jakobrunge** [comment]
Cool, I will push this to master and pip soon...
