### ISSUE TITLE
Does `selected_links` affect the handling of missing data?

### ISSUE THREAD

**Issue by dadelforge** [jakobrunge/tigramite#85]
The documentation states that the algorithm dismisses all time slices of samples where missing values occur in any variable and also flags samples for all lags up to 2*tau_max. The argument `selected_links` allows working on a subset of a dataframe. If I do so, are the overlapping time slices of missing values identified on a subset defined based on `selected_links` or dismissed on the full dataframe?

For instance, let us consider 3 independent output variables for a system, each of them potentially explained by 3 variables. I am therefore not interested in the direct interactions between the 3 output variables because they cannot physically interact. The output variables have an unequal amount and time distribution of missing data and dismissing all time slices of samples where missing values occur in any variable could be a problem if too few samples remain. I wonder if running the analysis with the 6 variables dataframe, with `selected_links` to avoid considering interactions between the output variables, would yield to the same results as running the analysis  3 times with the 4 variables dataframe? What is the best recommendation to avoid bias?

**Comment by jakobrunge** [comment]
> are the overlapping time slices of missing values identified on a subset defined based on selected_links or dismissed on the full dataframe?

The latter. selected_links is not considered here. I see what you want and this is indeed something we should adapt. For now you have to adapt the code in data_processing.py yourself and add a selected_links attribute to DataFrame.

**Comment by dadelforge** [comment]
Thanks for your answer.

I would like to check that I really understand how this works. Is there a way to output the final size of the sample set after dismissing time slices with missing values? In particular, as I have an irregular distribution of missing values, I would like to check up to which tau_max I can go while keeping enough data for a robust outcome.

The example below shows how I understand it with a simple pandas example. This is also an example of a problematic case as with only 10% missing data, only one valid sample. Is that the correct procedure for dismissing time slice with missing values?

Example dataframe
```python
import numpy as np
import pandas as pd
np.random.seed(1)
df = pd.DataFrame(np.random.rand(10,3), columns=['A', 'B', 'C'])
# add 10% nan
df = df.mask(np.random.random(df.shape) < .1)
df
```
>>>
```
          A         B         C
0       NaN  0.720324  0.000114
1  0.302333  0.146756  0.092339
2  0.186260  0.345561       NaN
3  0.538817  0.419195  0.685220
4  0.204452  0.878117  0.027388
5  0.670468  0.417305  0.558690
6  0.140387  0.198101       NaN
7  0.968262  0.313424  0.692323
8  0.876389       NaN  0.085044
9  0.039055  0.169830  0.878143
```

Adding lagged values and dropping no data
```python
tau_max = 1
# create the array with delays
df_full = pd.DataFrame()
for col in df.columns: 
    for lag in range(tau_max*2+1):
        df_full[f'{col}.{lag}'] = df[col].shift(lag)
print(df_full)
print('Final sample size = ', len(df_full.dropna()))
```
>>>
```
        A.0       A.1       A.2       B.0       B.1       B.2       C.0  \
0       NaN       NaN       NaN  0.720324       NaN       NaN  0.000114   
1  0.302333       NaN       NaN  0.146756  0.720324       NaN  0.092339   
2  0.186260  0.302333       NaN  0.345561  0.146756  0.720324       NaN   
3  0.538817  0.186260  0.302333  0.419195  0.345561  0.146756  0.685220   
4  0.204452  0.538817  0.186260  0.878117  0.419195  0.345561  0.027388   
5  0.670468  0.204452  0.538817  0.417305  0.878117  0.419195  0.558690   
6  0.140387  0.670468  0.204452  0.198101  0.417305  0.878117       NaN   
7  0.968262  0.140387  0.670468  0.313424  0.198101  0.417305  0.692323   
8  0.876389  0.968262  0.140387       NaN  0.313424  0.198101  0.085044   
9  0.039055  0.876389  0.968262  0.169830       NaN  0.313424  0.878143   

        C.1       C.2  
0       NaN       NaN  
1  0.000114       NaN  
2  0.092339  0.000114  
3       NaN  0.092339  
4  0.685220       NaN  
5  0.027388  0.685220  
6  0.558690  0.027388  
7       NaN  0.558690  
8  0.692323       NaN  
9  0.085044  0.692323 
Final sample size =  1
```

**Comment by jakobrunge** [comment]
You can see the sample size for each test with a higher verbosity parameter in the output.

I think you do it wrong above. You don't dismiss missing values prior to PCMCI, you keep the whole dataarray in DataFrame, but use the missing_flag=999. and set missing values to 999. (or any other number). See the missing value tutorial.

**Comment by dadelforge** [comment]
Indeed, thank you, when I run PCMCI parcorr with a verbosity level of 4, I indeed get the print of `Constructed array of shape (2, 1)`. I guess the value 1 is the final sample size I was looking for in my above example. Then, I guess the way I calculate the final sample size is somehow ok.
