### ISSUE TITLE
Efficient GP Implementation

### ISSUE THREAD

**Issue by jejjohnson** [jakobrunge/tigramite#86]
I noticed that the Gaussian process (GP) implementation uses the [sklearn](https://scikit-learn.org/stable/modules/gaussian_process.html) package. It's not the most efficient nor it is the most scalable. 

* I was wondering is there any interest in using more scalable and more efficient approaches? Is it important?
* What is the typical number of samples and features that this package typically deals with?
* Are there any dependency constraints in hardware (e.g. CPUs only, GPUs possible, etc)?

**Comment by mbruhns** [comment]
Thanks for pointing that out! As a matter of fact we're currently working on a high performance implementation of some functions of TIGRAMITE, including the GP implementation.

**Comment by jejjohnson** [comment]
Sounds great! I just wanted to offer help/suggestions in case they were needed. If you're looking for a resource, [this](https://jejjohnson.github.io/gp_model_zoo/software/) might be helpful.

**Comment by sagarsimha** [comment]
@jejjohnson We have now implemented Gaussian process regression using [GPyTorch](https://gpytorch.ai/) for large samples and if optionally GPU is intended to be leveraged. It stands alongside sklearn.
