### ISSUE TITLE
PCMCI across data samples

### ISSUE THREAD

**Issue by augo92** [jakobrunge/tigramite#87]
Hello,
Does anyone have guidance for using PCMCI+ over multiple samples from the same environment (e.g., N separate time series from the same environment)? Every example I've seen for its use has been for a single time series. I have tried concatenating but this causes spurious causes.

Thanks!
Augo92

**Comment by jakobrunge** [comment]
What exactly do you mean? PCMCI operates not on single time series, but estimates time series graphs among N time series. Ig uess you mean M multivariate time series datasets, each of shape (time, N)? I call that the ensemble case and this is indeed something we are working on.

**Comment by augo92** [comment]
Yes, sorry, I did mean multiple datasets, where each data set is a multivariate time series. For example, this could be measuring brain activity for multiple subjects, or for the same subject on different days. Glad to hear you are working on it! Any suggestions for how to handle it in the meantime?

Also, are there any ways to incorporate priors over the graph? This would be useful for cases where data is too limited to obtain a good graph estimate, but some causal relations can be assumed with some level of certainty. I can only think to create a generative model to produce the data but am wondering if there is an easier way to implement priors in tigramite.

Thanks!
Augo92

**Comment by jakobrunge** [comment]
For the ensemble case I would estimate graphs for each subject and then investigate how robust the links are. See here for an example of mine: https://iopscience.iop.org/article/10.1088/0967-3334/36/4/813

We are also working on how to incorporate prior knowledge. For now the selected_links parameter allows to restrict the search, but not to fix particular links.

~Jakob

**Comment by augo92** [comment]
Jakob,

Thank you for the link. My interpretation is that ensembling here would be done by averaging causal effects for each edge across subjects after their individual causal matrix/graphs have been estimated produced. If this is the correct interpretation, wouldn’t this underreport true positives?

It seems safe to assume full dynamics may simply not be sampled for certain subjects. If so, it could be that we cannot reject the null hypothesis for some edges because the values for which causal variables would produce causes were simply not sampled from some subjects. In Markov modeling terms, some states may never be sampled for a subject, so their state transitions were not observed. This is a different type of lack of evidence vs. actually observing certain states and seeing that they do not transition to other certain states.
Also, averaging across individually estimated graph estimates would seem to ignore the possibility that a cause would increase significance by aggregating samples across subjects for edges that are causal but where no subject reach significance due to low sample size.
Am I misinterpreting?

I have some other questions but I’ll open other issues for those.

Thanks again,
Augo92

**Comment by jakobrunge** [comment]
Dear Augo
This is really just a way of visualizing multiple graphs. It's not a statistical test across the ensemble. The link width depicts the fraction of subjects where a particular link is significant. I think I truncated too small link widths in that paper, but it's up to you. The link color is then the average link strength (here MCI Conditional Mutual Information = Momentary Information Transfer). 

Of course, if you, for example, concatenate the time series and produce one graph, you could get more significant links. But you could also loose significant links, for instance, if processes have opposite sign and cancel, or if the effect is only there in few subjects. But this is another hypothesis. It all depends on what you want to look at. In that paper it was about graphs for individual subjects and looking at differences between healthy and sick ones.

Best wishes
Jakob
