### ISSUE TITLE
FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2)

### ISSUE THREAD

**Issue by bsolino** [jakobrunge/tigramite#88]
I've encountered this warning when the github installation cythonizes `tigramite/tigramite_cython_code.pyx` (emphasis mine):

> FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). **This will change in a later release!**

I've digged a bit into this and the language level can be set either on the compiler call or inside the file itself:

> `language_level` (2/3/3str)
>     Globally set the Python language level to be used for module compilation. Default is compatibility with Python 2. To enable Python 3 source code semantics, set this to 3 (or 3str) at the start of a module or pass the “-3” or “–3str” command line options to the compiler. The 3str option enables Python 3 semantics but does not change the str type and unprefixed string literals to unicode when the compiled code runs in Python 2.x. Note that cimported files inherit this setting from the module being compiled, unless they explicitly set their own language level. Included source files always inherit this setting.
https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives

Furthermore, it defaults to Python 2 for "pyx" files:

> language_level – The source language level to use: 2 or 3. The default is to use the language level of the current Python runtime for .py files and Py2 for .pyx files.
https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#arguments

I couldn't find any information on the development branch about whether python 2 or 3 should be used to compile this file, and it seems this warning is probably still present there.

**Comment by jakobrunge** [comment]
Cython is now removed and replaced by numba.
