### ISSUE TITLE
networkx dependency listed as specifically 1.10.0, is that correct?

### ISSUE THREAD

**Issue by bsolino** [jakobrunge/tigramite#89]
Today I noticed a problem trying to prepare a conda environment for tigramite. The required packages (https://github.com/jakobrunge/tigramite/blob/master/README.md#required-python-packages) as given in the readme say that the networkx version has to be specifically 1.10.0. However, the lowest available version that I found was 1.11

I checked other issues, and I noticed that someone was running networkx 2.4 https://github.com/jakobrunge/tigramite/issues/70, apparently without causing issues, so I wonder if that dependency is correct.

**Comment by jakobrunge** [comment]
No, it's networkx>=2.4 in the setup.py, but the Readme was old on that. I'll remove those numbers in further releases.
