### ISSUE TITLE
Using Tigramit to detect Air conditioning effect on indoor temperature.

### ISSUE THREAD

**Issue by FlorencDemrozi** [jakobrunge/tigramite#90]
Dear authors, 
First of all, I congratulate you on the excellent library you have provided.
I created a synthetic dataset containing data about:

- The temperature of room A,
- The temperature of room B,
- Door status [0 close, 1 open] that connects A and B,
- Air Conditioning status [0 off, 1 on] of room B,
- Heating status [0 off, 1 on] of room B.
Every hour, we have a new observation of such inputs.
For example, we know that if the temperature of room B decreases by delta degrees every hour if the AC is on, increases of delta if the Heating is on and increases and decreases of delta if the Door is opened.  

My question is, what type of information can tigramet provide to me? 
I already tested it, but I obtain a graph of 5 nodes, and i do not understand the meaning of such a graph. 
Can you please help me by providing some more information on how to read the results?
Finally, is tigramite able to tell me, for example, that if AC=1 at time t, then at time t+1 temperature of room A decreases and in case of how much?

**Comment by jakobrunge** [comment]
I suggest to look at the tutorials to better understand the methods.
