### ISSUE TITLE
Running PCMCI+ on new data

### ISSUE THREAD

**Issue by augo92** [jakobrunge/tigramite#93]
Hello,
Is there a way to save off results from data already analyzed with PCMCI+ and to pick up from there when new data comes in to update the estimated causal graph? For example, one may want to analyze time points in the last day, and then add data for the next day, and so on. Or someone may want to rerun for every new time step. It would be preferable if at each new time step, PCMCI+ would not have to be rerun over the full history to update the causal predictions.

Thanks,
Augo92

**Comment by jakobrunge** [comment]
No, this is not possible with this kind of algorithm.

Am 12. Dezember 2020 02:11:47 schrieb augo92 <notifications@github.com>:
