### ISSUE TITLE
Impact of negative feedback loops

### ISSUE THREAD

**Issue by augo92** [jakobrunge/tigramite#94]
Hello,
I tried developing a simple three node causal model with a negative feedback loop to keep the model relatively stationary. That is, node_A has a positive cause on node_B, which has a positive cause on node_C, which has a negative cause on node_A. Each cause has a time lag of 1 time step. 
When I ran PCMCI+ on the time series generated from this model, it did not find any significant causes. Are there any assumptions this model is violating? The mode is clearly cyclic, but I was hoping that the fact that it was time lagged would enable PCMCI+ to estimate it (e.g., no faithfulness violation). Is this an appropriate assumption in general?

Other details in case useful:
I tried both linear and nonlinear causes:
- I tried both additive and multiplicative causes for the edges.
- I tried setting activation thresholds or no thresholds for the nodes.
- I tried a variety of different magnitudes for the causes.

Note: I would like to generate many possible models (e.g., different nodes and edges). If anyone knows of code for an existing model generator that should work well for testing causal discovery methods like PCMCI+ on a variety of cases, please let me know!

Thanks,
Augo92

**Comment by jakobrunge** [comment]
PCMCI is asymptotically consistent and will hence estimate the causal structure if:
- Causal Sufficiency is fulfilled
- Markovity is fulfilled
- Faithfulness is fulfilled
- The process is acyclic in its time-resolved structure. If there are only lagged dependencies, this is always the case
- the conditional independence test class is correct, i.e., for every CI test done in PCMCI, the assumptions underlying that test are fulfilled. E.g. for all linear processes ParCorr is correct. CMIknn should work for any nonlinear process, but for CMIknn no theoretical consistency results exist, only numerical simulations
- the process is stationary. For linear VAR models simple criteria exist, but for nonlinear processes this is much more difficult or no results are available. In my Science Advances paper I used a nonlinear model class for which such results exist.
- the sample size is large enough

If any of these is violated, there are no guarantees, but it could still work.

The latest Tigramite release has a very flexible model generator function called  `structural_causal_process(links,` T, noises=None, seed=None)`

I hope this helps.
