### ISSUE TITLE
Double dot link in graph + selected_links

### ISSUE THREAD

**Issue by vladbragoi** [jakobrunge/tigramite#95]
Hi all,
Thank you for such a useful tool.

Trying to understand your example-notebooks, I found that it is not clear what links with double dots (at source and target) mean. For instance, in this example ![example](https://user-images.githubusercontent.com/24266220/102634024-900f2480-4151-11eb-83d3-5db722ed01e8.png) you can see that variable `ac_c` has an orange link with variable `internal_temp`, with dots at the beginning and at the end of the link that connects the two variables, and the same occurs with timeseries plot:
![timeseries](https://user-images.githubusercontent.com/24266220/102634650-67d3f580-4152-11eb-920f-7d548aa2ca4a.png)

Another thing is how the `selected_links` vector in "tigramite_tutorial_assumptions.ipynb" must be created, or better, why are you creating tuples with `lag in  range(tau_min, tau_max + 1)`:
```
# Only estimate parents of variables 0, 1, 2
selected_links = {}
for j in range(4):
    if j in [0, 1, 2]:
        selected_links[j] = [(var, -lag) for var in range(4)
                         for lag in range(tau_min, tau_max + 1)]
    else:
        selected_links[j] = []
pcmci_parcorr = PCMCI(
    dataframe=dataframe, 
    cond_ind_test=parcorr,
    verbosity=0)
results = pcmci_parcorr.run_pcmci(tau_min=tau_min, tau_max=tau_max, pc_alpha=0.2, 
                                  selected_links=selected_links)
```

Could you please help me to understand these details about your framework, or can you tell me which notebook better answers my questions?
Thank you

**Comment by vladbragoi** [comment]
I will add a few more information to let you better understand my question.

I think with `selected_links` I could define the only relationships we are interested in. For example, we know that the `internal_temp` does not affect `ac_c` or `ac_f`, so to have a more precise final graph, it would be useful to tell Tigramit that we are not interested in the relation: `internal_temp` implies a variation of `ac_c` or `ac_f`. Furthermore, we are not interested in the relation between `ac_c` and `ac_f` (boolean variables) since such variables will always be contrary except when they are both zero (they will never be both equal to one at the same time). 
Is it possible with `selected_links` (or with a different method, could you suggest which one?) to achieve this?

Thank you

**Comment by vladbragoi** [comment]
Last question: could you please tell me why I'm getting 3 links between `ac_c` and `internal_temp`? One with double dots presented above and the others oriented.

**Comment by jakobrunge** [comment]
You can find information about interpreting the links in the tutorial tigramite_tutorial_pcmciplus.ipynb
o--o stands for an undirected contemporaneous link.
The fact that there may be three links in the plot_graph() is due to summarizing the information in the time series graph. This is explained in the basic tutorial.

With selected_links you can limit which links are tested and conditioned on.

**Comment by vladbragoi** [comment]
Thank you Jakob. So, how can the `selected_links` vector be constructed?

**Comment by jakobrunge** [comment]
This is explained in the docstring:

```
        selected_links : dict or None
            Dictionary of form {0:[(0, -1), (3, -2), ...], 1:[], ...}
            specifying whether only selected links should be tested. If None is
            passed, all links are returned.
```
That example dictionary would only test and condition on links [(0, -1), (3, -2), ...] for variable 0 in the array. Here (3, -2) stands for the link from variable 3 at lag -2 to variable 0.

**Comment by vladbragoi** [comment]
But what if I need to ignore for example only the edge between two variables and not all nodes from one variable?

**Comment by jakobrunge** [comment]
But that's exactly what the parameters allows you to do. There is a 
dictionary entry for every link.

Am 22. Dezember 2020 18:13:32 schrieb Vlad Bragoi <notifications@github.com>:

**Comment by vladbragoi** [comment]
> But that's exactly what the parameters allows you to do. There is a dictionary entry for every link. Am 22. Dezember 2020 18:13:32 schrieb Vlad Bragoi <notifications@github.com>:
> […](#)
> But what if I need to ignore for example only the edges between two variables and not all nodes from one variable? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I asked that because tigramite haa thrown me an exception with a message similar to "values need to be symmetric" and I found that It was the PC_ALPHA parameter passed to None, so I deleted the question maybe a few minutes before your answer. 
Anyway, thank you for tour quick reply

**Comment by jakobrunge** [comment]
Check whether that is now solved in the developer!
