### ISSUE TITLE
pip install from github working, pypi not so much for me

### ISSUE THREAD

**Issue by microprediction** [jakobrunge/tigramite#96]
I have no problem installing:
 
       `pip install git+https://github.com/jakobrunge/tigramite.git`

However, pip install from PyPI results in 

`ValueError: '/private/var/folders/g2/6p5lz9hn36vbnv165bk7yj7r0000gn/T/pip-install-t58aruyc/tigramite_9982fbefe8d54823a03079e37b28eef3/tigramite/tigramite_cython_code.pyx' doesn't match any files`

I have cython installed.

**Comment by jakobrunge** [comment]
I'll look into it...

**Comment by jakobrunge** [comment]
Hi, can you try pip again? Version 4.2.1.2 hopefully works on your platform...

**Comment by microprediction** [comment]
Success! Thanks for that and great library btw.

**Comment by microprediction** [comment]
Just for clarity. I tested on Catalina 10.15.6 and also colab.
